### ISSUE TITLE
Create a provider for ILoggingEvent#getMessage()

### ISSUE THREAD

**Issue by nithril** [logstash/logstash-logback-encoder#100]
The raw message add another way of categorizing log event.

eg. search for all event using the logger `security` and with the raw message equals to `Connection Unauthorized from ip:{}`.

Again, if you agree with the proposal, I could give it a try to a pull request.

**Comment by philsttr** [comment]
Sounds good to me.

I would not include this provider by default (in `LogstashEncoder`), but it would be good to have as a provider that could be included in the composite encoder/layout.

**Comment by nithril** [comment]
I agree. 

Do you  require a PR?

**Comment by philsttr** [comment]
PR would be great!

**Comment by nithril** [comment]
PR done. Please have a look.

**Comment by philsttr** [comment]
Looks great!  Thanks!  Merged.

**Comment by nithril** [comment]
Thanks!

**Comment by philsttr** [comment]
4.4 has been released with this fix
