### ISSUE TITLE
TCP appender does not send messages to logstash

### ISSUE THREAD

**Issue by alinbutura** [logstash/logstash-logback-encoder#101]
Hi guys,

I am trying to send log messages using net.logstash.logback.appender.LogstashTcpSocketAppender, with the following logback.xml:
`<configuration>
    <appender name="stash"
        class="net.logstash.logback.appender.LogstashTcpSocketAppender">
           <remoteHost>127.0.0.1</remoteHost>
           <port>4560</port>
           <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
           <keepAliveDuration>5 minutes</keepAliveDuration>
    </appender>
    <root level="DEBUG">
           <appender-ref ref="stash" />
    </root>
</configuration>`

On the logstash side, the configuration is:
`input {
   tcp {
     port => 4560
     codec => json_lines
   }
}
output {
   stdout {
     codec => rubydebug
   }
}`

The testcase run from within Eclipse logs 100 messages but none of them reach logstash.
If I debug the testcase then some of them will be eventually sent. I added a breakpoint in the doEncode() of net.logstash.logback.encoder.CompositeJsonEncoder and saw that, indeed, the method gets called randomly which explains why not all messages reach logstash.
I telnet-ed the 4560 port of logstash and it works just fine. The port is in LISTEN mode. So the problem is on the logback side.
Am I doing something wrong?
Thanks!

Regards,
Alin

**Comment by philsttr** [comment]
Hi Alin,

One likely cause is that the JVM is shutting down before the async thread that sends messages across the wire has had a chance to send all the messages.

To ensure all logged messages are sent, you should [shutdown logback](http://logback.qos.ch/manual/configuration.html#stopContext) prior to shutting down the JVM.  The shutdown logic will ensure all events are flushed.

**Comment by alinbutura** [comment]
True, it works just fine if I stop the LoggerContext of logback classic. Thanks again!

**Comment by leiboo** [comment]
Thank for you answer, it works well@philsttr
