### ISSUE TITLE
Extended MDC to allow Object as value in MDC.put 

### ISSUE THREAD

**Issue by nithril** [logstash/logstash-logback-encoder#107]
Slf4j MDC only accepts String as value and I do not think [it will change](http://jira.qos.ch/browse/SLF4J-168). I have look at `LogbackMDCAdapter` and it should be possible to have the same behaviour but with a map of object. 

Unfortunately It may imply some hack:
- In order to set the `MDC#adapter` a class in the `org.slf4j`package should be created
- The `LogbackMDCAdapter` class must be cloned and adapted. 
- Like this class seems to implement a copy on put, the `LogbackMDCAdapter#getCopyOfContextMap` may only return the string/string map embed in a adapter of string/object map.

Does it make sense to you to have this feature into the logstash-logback-encoder ?

**Comment by philsttr** [comment]
I'd personally rather not include this feature in logstash-logback-encoder, as I think it is a little outside of the scope of this project.

Having said that, if you _do_ implement it (in another project), be wary of threadsafety concerns.  I imagine that slf4j's MDC is limited to `String` values to ensure threadsafety and immutability.  Keep in mind that values might be written in different threads when asynchronous appenders are used.  Therefore, it is important that the object's `toString()` accurately reflect the state of the object at the time it was added into the MDC. 

For example, in [SLF4J-168](http://jira.qos.ch/browse/SLF4J-168), the description mentions including `httpServletRequest` in the MDC.  This would be a problem if async appenders (such as the TCP appender in logstash-logback-encoder) are used on platforms (such as jetty) that reuse `HttpServletRequest` objects.  By the time the event is written (by the async appender), the `httpServletRequest` will no longer reflect the state at which it was added to the MDC.  It could be have been recycled for use by completely different request!

**Comment by nithril** [comment]
I understand. Thanks for your reply!

**Comment by Kidlike** [comment]
Sorry for grave-digging. But I was trying to do the same.

It would be very helpful to add this feature.
The alternative right now is to add a marker on every single log entry, AND get the object from a self-managed ThreadLocal. Which is a pain to say at least.

I believe the following way is safe to allow this feature:

**A flag inside the \<mdc> section of logback.xml, to indicate that a specific key is expected to be a json.
Then, when adding the entry, convert it to String with Jackson (manually).**
e.g.:
```
public static <T> void addObjectToMdc(T object) {
    try {
        MDC.put("someKey", objectMapper.writeValueAsString(object));
    } catch (JsonProcessingException e) {
        MDC.put("someKey", "{error: \"Object could not be processed by Jackson.\"}");
    }
}
```

**Comment by Kidlike** [comment]
Well, I have found a solution for this on the Logstash side. These are the relevant parts:

```
input {
	file {
		path => "the.log"
		codec => json {
			charset => "UTF-8"
		}
	}
}

filter {
    json {
        source => "someKey"
        target => "someKey"
    }
}
```
