### ISSUE TITLE
Release with StructuredArguments

### ISSUE THREAD

**Issue by fdouchant** [logstash/logstash-logback-encoder#109]
Hi,

I'm using your logback to logstash appender in my project and it works really well :-)

However in your documentation, you mention that we can use "Event-specific custom fields" but it is only available on your branch and therefore it has never been released (or deployed to maven central).

Did you already plan to release it ? And if you did, when will that be :-) ?

Thanks a lot,

Fabrice D.

**Comment by philsttr** [comment]
Hi Fabrice.

It will be released soon.

I'm doing a little more testing on it first. 

Probably next week.

**Comment by philsttr** [comment]
4.4 has been released

**Comment by fdouchant** [comment]
Thx :-)
