### ISSUE TITLE
ShortenedThrowableConverter prints warnings during initialisation

### ISSUE THREAD

**Issue by dimas** [logstash/logstash-logback-encoder#112]
The ShortenedThrowableConverter class allows specifying special values for properties like maxDepthPerThrowable - in addition to a numeric value you can put "full" and other special keywords - these are handled by this method: https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java#L212

However I assume that it is Logback's "plugin framework" tries to parse that XML configuration and inject proper values into all the configured appenders / formatters etc. And when it sees a property of type "int", it tries parse value as int. As the result there are warnings during the application startup:

```
20:38:26,478 |-WARN in ch.qos.logback.core.joran.util.PropertySetter@a16a0cb - Failed to set property [maxDepthPerThrowable] to value "full".  ch.qos.logback.core.util.PropertySetterException: Conversion to type [int] failed.
```

My only idea how to handle that is to change all these fields to Strings and add a parsed version of each of them which will be "int".

**Comment by philsttr** [comment]
Yeah, those special keywords are currently only usable when it the converter is used in a `conversionRule` as described in the [javadoc for ShortenedThrowableConverter](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java#L59-L85).  They don't currently work when configured as part of an encoder, as you have found out.

And yeah, the only way to fix this would be to have String setters for those properties.

**Comment by dimas** [comment]
Any way to involve the original author into this? :) Or we are expected to fix it ourselves?

**Comment by philsttr** [comment]
A PR would be great.

However, do you really need to use `full`/`short` when configuring this via XML?  You can always just use int values.  I believe `full`/`short` was only added to make it similar to logback's befault `ThrowableProxyConverter`, as documented [here](http://logback.qos.ch/manual/layouts.html#ex).

**Comment by dimas** [comment]
Of course it is possible to use numbers instead, but when you use "full", your intentions are much more clear compared to situation where you need to type in a max integer...
I forked repo intending to do the fix when I realised that "full" is already a default for two out of three configurable options. Only the max depth default is not full for some reason. I would prefer full to be default for all of them because it just seems logical that everything is kept by default and only when you want it shorter, you start configuring these.
But given that two of them are ok by default, I think I won't need support for special string anymore. So feel free to close this item.

**Comment by Martin-Wegner** [comment]
Same problem here :( When using multiple `<exclude>` elements I got an error for each element:

> Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION

**Comment by philsttr** [comment]
Hi @Martin-Wegner 

Can you provide your logback xml configuration?  I want to confirm if your problem is the same as the original report.

**Comment by Martin-Wegner** [comment]
logback 1.1.7 and logstash 4.6

```
ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventJsonProviders] for [providers] property
ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider] for [timestamp] property
ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LogLevelJsonProvider] for [logLevel] property
ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.ThreadNameJsonProvider] for [threadName] property
ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggerNameJsonProvider] for [loggerName] property
ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.CallerDataJsonProvider] for [callerData] property
ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.MessageJsonProvider] for [message] property
ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.StackTraceJsonProvider] for [stackTrace] property
ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION
ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION
ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION
ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION
```

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

  <property name="fileNamePrefix" value="${maven.filter.logFileNamePrefix}" />

  <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>${fileNamePrefix}.log</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <!-- daily rollover -->
      <fileNamePattern>${fileNamePrefix}.%d{yyyy-MM-dd}.log</fileNamePattern>
      <!-- keep 10 days' worth of history -->
      <maxHistory>10</maxHistory>
    </rollingPolicy>
    <!-- encoders are assigned the type
         ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
    <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
      <providers>
        <timestamp>
          <fieldName>timestamp</fieldName>
        </timestamp>
        <logLevel>
          <fieldName>logLevel</fieldName>
        </logLevel>
        <threadName>
          <fieldName>threadName</fieldName>
        </threadName>
        <loggerName>
          <fieldName>loggerName</fieldName>
        </loggerName>
        <callerData>
          <classFieldName>className</classFieldName>
          <methodFieldName >methodName</methodFieldName>
          <fileFieldName>[ignore]</fileFieldName>
          <lineFieldName>lineNumber</lineFieldName>
        </callerData>
        <message />
        <stackTrace>
          <fieldName>stackTrace</fieldName>
          <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
            <exclude>java\..*</exclude>
            <exclude>net\.sf\.cglib\..*</exclude>
            <exclude>org\.springframework\..*</exclude>
            <exclude>sun\..*</exclude>
            <maxDepthPerThrowable>30</maxDepthPerThrowable>
            <rootCauseFirst>true</rootCauseFirst>
          </throwableConverter>
        </stackTrace>
      </providers>
    </encoder>
  </appender>

  <logger name="de.bayern.abdsb.arbis.arbismonitor" level="${maven.filter.logLevel}" />

  <root level="WARN">
    <appender-ref ref="FILE" />
  </root>

</configuration>
```

**Comment by philsttr** [comment]
Hi @Martin-Wegner,

The warnings/errors you are seeing are only seen with logback 1.1.7.  They are not seen when using logback 1.1.6.  I have created #160 to fix these.

I'll track this issue on #160 instead of here (#112)

**Comment by Martin-Wegner** [comment]
OK thanks :)

**Comment by Martin-Wegner** [comment]
@philsttr my warnings are all fixed in 1.1.8 :)

**Comment by philsttr** [comment]
In 5.0, the default value for `maxDepthPerThrowable` is unlimited/full.  This brings this configuration option inline with the default values for `maxLength` and `shortenedClassNameLength`, which are also unlimited/full by default

**Comment by cttw** [comment]
I am getting the same error for below configuration

<?xml version="1.0" encoding="UTF-8"?>
<configuration>

  
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
      <encoder class="net.logstash.logback.encoder.LogstashEncoder">
          <nestedField>
              <fieldName>NESTED</fieldName>
              <providers>
                  <message />
              </providers>
          </nestedField>

      </encoder>
  </appender>
  
  <appender name="ASYNCSTDOUT" class="ch.qos.logback.classic.AsyncAppender">
      <includeCallerData>true</includeCallerData>
    <appender-ref ref="STDOUT" />
  </appender>

  <root level="INFO">
    <appender-ref ref="ASYNCSTDOUT" />
  </root>

</configuration>



can we add two different encoders in a single appender?
if I want to use net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder and also  net.logstash.logback.encoder.LogstashEncoder in the same console appender, how do I use it?
