### ISSUE TITLE
maven-shade-plugin should be upgraded to >= 2.3 

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#120]
The `maven-shade-plugin` should be upgraded to at least version 2.3 to benefit from the following bug fixes:
- https://issues.apache.org/jira/browse/MSHADE-167

**Comment by philsttr** [comment]
+1 Definitely

**Comment by brenuart** [comment]
Do you want me to create a PR or will you do it on master yourself?

**Comment by philsttr** [comment]
I can handle this

**Comment by philsttr** [comment]
upgraded to 2.4.1 in commit f53490c45dabeb98bafbfbca718765e0a69aacb8
