### ISSUE TITLE
Unable to set KeepAliveCharset via log back configuration

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#121]
Unable to set `keepAliveCharset` via XML configuration. The following configuration fragment causes an error when log back configures itself:

```
<appender name="STASH" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
    <keepAliveCharset>UTF-8</keepAliveCharset>
    ...
</appender>
```

Logback complains with the following error:
```
Exception in thread "main" java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@38:24 - no applicable action for [keepAliveCharset], current ElementPath  is [[configuration][appender][keepAliveCharset]]
```

Apparently Logback doesn't recognise this parameter as a valid Java Bean property. This is probably caused by the fact that the corresponding getter and setter do not have the same type:

- `setKeepAliveCharset(String): void`: takes as String as input
- `getKeepAliveCharset(): Charset`: returns a `Charset`

**Comment by philsttr** [comment]
PR #122 merged
