### ISSUE TITLE
unable to use StructuredArguments with akka.event.slf4j.Slf4jLogger

### ISSUE THREAD

**Issue by danielAparicio** [logstash/logstash-logback-encoder#123]
Hi!
First of all I guess that this is not a problem related with this fantastic library , but maybe there is a workaround for this.

I'm using Spray.io that is using the akka.event.slf4j.Slf4jLogger:

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel = INFO

everything is working fine until I try to use StructuredArguments that is not working, they are being taken as NonStructuredArguments

The point is that if I use directly the akka.event.slf4j.Logger:
    Logger.root.info("log message {}", keyValue("aaaa", "bbbb"))
is working but is a blocking logging

It's supposed that the log in akka.event.slf4j.Slf4jLogger is the same type as the log in akka.event.slf4j.Logger  that is an org.slf4j.Logger

Thanks

**Comment by danielAparicio** [comment]
bf
76541

**Comment by philsttr** [comment]
Unfortunately, logstash-logback-encoder cannot do anything about this.  This problem is in `akka.event.slf4j.Slf4jLogger`.

`Slf4jLogger` collapses everything down into a string. 
See [here](https://github.com/akka/akka/blob/v2.3.9/akka-slf4j/src/main/scala/akka/event/slf4j/Slf4jLogger.scala#L71)
