### ISSUE TITLE
Add logback contextName to the json log entry

### ISSUE THREAD

**Issue by akiraly** [logstash/logstash-logback-encoder#124]
LogstashEncoder supports many different parts of logback but it seems contextName is not yet among them.

Could it be added? Currently I go with this workaround (in logback xml) so it is picked up as part of the context properties:

```xml
<property scope="context" name="contextName" value="${CONTEXT_NAME}" />
```

Logback manual on contextName-s ("Setting the context name" chapter):
http://logback.qos.ch/manual/configuration.html#contextName

**Comment by philsttr** [comment]
Provider for adding context name to output will be available when 4.6 is released.

**Comment by philsttr** [comment]
4.6 has been released and is on its way to maven central

**Comment by lintghi** [comment]
hi, i use  4.11

logback.xml

<contextName>test</contextName>
<appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
		    <destination>logstash:4560</destination>
			<keepAliveDuration>5 minutes</keepAliveDuration>
		    <reconnectionDelay>5 second</reconnectionDelay>
		
		    <encoder class="net.logstash.logback.encoder.LogstashEncoder" >
		    	<shortenedLoggerNameLength>25</shortenedLoggerNameLength>
		    	<includeContext>true</includeContext>
		    </encoder>
</appender>

and i can not found the contextName in  kibana:

_source:
@timestamp:September 12th 2017, 20:57:05.895 level:INFO port:63,513 thread_name:main level_value:20,000 @version:1 host:172.16.8.210 logger_name:c.i.z.a.s.Application message:Started Application in 5.393 seconds (JVM running for 6.681) _id:AV52JJGJ64ycIOMdNTie _type:%{[@metadata][type]} _index:%{[@metadata][beat]}-2017.09.12 _score: -

**Comment by philsttr** [comment]
Hi @lintghi 

When `includeContext==true` the context _properties_ will be added to the event, not the context _name_.

To get the context _name_ added to the event, you must add the `contextName` provider.

Unfortunately, it's a little messy to add this provider to a LogstashEncoder, but it can be done as follows:

```xml
<contextName>test</contextName>
<appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
    <destination>logstash:4560</destination>
    <keepAliveDuration>5 minutes</keepAliveDuration>
    <reconnectionDelay>5 second</reconnectionDelay>

    <encoder class="net.logstash.logback.encoder.LogstashEncoder" >
        <shortenedLoggerNameLength>25</shortenedLoggerNameLength>
        <includeContext>true</includeContext>
        <provider class=net.logstash.logback.composite.loggingevent.ContextNameJsonProvider/>
    </encoder>
</appender>
```
