### ISSUE TITLE
LogstachTcpSocketAppender: Roundrobin multiple IPs for single hostname

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#125]
It would be nice if the appender had an option to consider every IP addresses that might be assigned to a single hostname and behave as if multiple destinations were manually configured.

Activation of the feature should be optional.
If disabled, the default resolution would apply, ie one of the IP is selected "at random".
If enabled, all IPs are added as destinations. Their ordering (primary vs. secondaries) is undetermined however...

**Comment by philsttr** [comment]
Closing this because I'm not aware of an easy way to fetch all the IPs associated with a single hostname from java.  Feel free to reopen with a suggested way of doing so.  Or a PR.
