### ISSUE TITLE
AsyncDisruptorAppender: log event when buffer is full

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#127]
The current implementation issues logs a warning to logback's context when the event buffer is full.
Unfortunately, this information is logged locally and won't be available remotely together with the rest of the logged events. It would be nice if the appender automatically generates a log event when the buffer becomes ready again to accept new events. The auto-generated event would then be added to the buffer and transmitted remotely - it would eventually end-up in the remote storage and would be available for further post-processing/fault detection.

Ideally, the event would report how long and how many messages were dropped, together with any other available information that could help sysadmins to troubleshoot the issue.

**Comment by magro** [comment]
+1, any plans here?

**Comment by philsttr** [comment]
@magro  I would like to add some callbacks for various events (as mentioned in #159), but no work has been put towards this yet.  Contributions welcome.

**Comment by philsttr** [comment]
Appender listeners have been added in 5.0.

The listeners give you the ability to monitor the appenders and act on failures.

The behavior requested in this ticket could be implemented with a listener.
