### ISSUE TITLE
AbstractLogstashTCPSocketAppender: InetSocketAddress.getHostString() requires Java 1.7

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#129]
`InetSocketAddress.getHostString()` requires Java 1.7
This breaks 1.6 compatibility

**Comment by brenuart** [comment]
Strange the `animalsniffer-maven-plugin` didn't notice it...

**Comment by philsttr** [comment]
Gah!  Yeah, definitely strange.

**Comment by brenuart** [comment]
Should we fix it immediately?

**Comment by philsttr** [comment]
Yeah, I'll try to fix it later today.

**Comment by brenuart** [comment]
`InetSocketAddress.getHostString()` does actually exist in 1.6 but is `private`. Wouldn't be surprised if this is confusing animal sniffer...

**Comment by philsttr** [comment]
Fixed in 34e6b22e24e08122d2bcae7711f6c2227616be31 for 4.5.1
