### ISSUE TITLE
LogstashTcpSocketAppender: fails silently when connecting to destination fails 

### ISSUE THREAD

**Issue by raboof** [logstash/logstash-logback-encoder#132]

**Comment by raboof** [comment]
Looking a bit closer, it's not actually silent, but I didn't have a statusListener configured in logback which caused this logging to go to /dev/null. A better upstream default here would be nice :/.

**Comment by raboof** [comment]
Created http://jira.qos.ch/browse/LOGBACK-1097 upstream.

**Comment by philsttr** [comment]
I think the logback-logstash-encoder behavior is correct here.

Do you have any recommendations?

**Comment by raboof** [comment]
My recommendation is we fix this upstream in logstash. Comments, votes, design discussion on http://jira.qos.ch/browse/LOGBACK-1097 very welcome :)

Personally I like leaving this 'downstream' issue open (with an appropriate tag) until the problem is solved 'upstream': that way we can keep track of 'external' work that will improve the experience of working with logstash-logback-encoder, and perhaps see if we can find another workaround when the problem remains unresolved upstream. But that might be a matter of personal preference :).

**Comment by bugmakesprogress** [comment]
It s better to add failed connecction log in default configuration. I m a newbee to logstash-logback-encoder. When my LogstashTcpSocketAppender destination configuration failed to connect logstash, it made me confused cause no single failure log were shown on my console.  Of course we can get failure logs by extending [listener](https://github.com/logstash/logstash-logback-encoder/tree/logstash-logback-encoder-5.3#appender-listeners). It s still a good idea to add a first time connection failure log for better debuging experience of  logstash-logback-encoder.

**Comment by wsargent** [comment]
The solution of adding to `OnConsoleStatusListener` is overkill for the appender, because it doesn't just log the errors, it also logs all the INFO messages to console.  It would work much better to have an "on error" status listener that didn't spam data to the console

**Comment by philsttr** [comment]
@wsargent, please file a new issue

**Comment by wsargent** [comment]
done
