### ISSUE TITLE
Documentation Incorrectly Describes How To Change Field Names

### ISSUE THREAD

**Issue by kurron** [logstash/logstash-logback-encoder#135]
The documentation that describes how to override and disable the field names used by LogstashEncoder is partially incorrect.  It states that we can use the field names in `LogstashFieldNames` to override what is generated.  Some of the fields, such as `logger_name`, have to be specified using a different value.  In this example,  `logger` will do the trick.  If you set a breakpoint in `LoggerNameJsonProvider.setFieldNames` you can see the values that are actually used.  Here is the XML I had to use to gain the control I required:

```
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <includeContext>false</includeContext>
            <timeZone>UTC</timeZone>
            <fieldNames>
                <timestamp>timestamp</timestamp>
                <message>message</message>
                <logger>component</logger>
                <version>[ignore]</version>
                <thread>[ignore]</thread>
                <levelValue>[ignore]</levelValue>
            </fieldNames>
        </encoder>
```

Great library, by the way.  I'm using it send messages from a Docker container, wrapped in a syslog format off to Loggly.  Loggly will parse the JSON and work its magic.

**Comment by philsttr** [comment]
Hah.  I meant the java field names in that class.  e.g. private String *logger*

I'll make the doc more clear.

Thanks for the report!
