### ISSUE TITLE
Issues with consolidating custom key/values for both console (non JSON) output and logstash JSON output

### ISSUE THREAD

**Issue by mdedetrich** [logstash/logstash-logback-encoder#136]
Due to the design of logstash logback encoder, it appears to be very cumbersome to log custom key/value fields for both console logging, and for JSON style logging. Here is a simple use case, lets say we want to log with some extra info (in this case, just a userId), we currently have 2 options

First one is with structured arguments
```java
logger.error("Some message {}", kv("user_id",userId);
```
The other one is with logstash markers
```java
logger.error(append("user_id",userId),"Some message")
```

Unfortunately, either case has cons which are quite annoying.

**With structured arguments**
Pros
+ Really easy to consolidate output for basic console (where you don't want to output JSON, but formatted strings), and the actual JSON output for Logback

Cons
+ Configuring the `net.logstash.logback.encoder.LogstashEncoder` (or the base class `net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder`) to actually provide the structured arguments in the JSON is really annoying. There is no sane default, i.e. doing
```xml
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <providers>
                <arguments/>
            </providers>
        </encoder>
```
Means that all you will get the JSON (for logback) a `"message": "Some message userId=1"`, instead of what you want, which would be 2 key values, one being `"message": "Some message"` and the other being `"user_id":1`
+ Appears that you need to know which key values you want to output as seperate key/values for the JSON, instead of outputting all of the key/values from structured arguments (which is what you want by default). If this is the case, its not really usable since the user doesn't have a real idea of all of the possible key/values

**With logstash markers**
Pros
+ No additional configuration needed to add the key/values in the logstash outputted JSON. They appear just as you expected
+ All marker values are added, you don't need to explicitly specify which ones

Cons
- Since the `net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder` outputs JSON, if you are using this encoder to append to console (i.e. basic local development), you get a giant glob of JSON which is really difficult to read. You can't use `ch.qos.logback.classic.encoder.PatternLayoutEncoder`, since none of your markers will appear (and its apparently impossible to change this)

For the reasons above, it seems that logstash-logback-encoder is in a weird middle ground. I (assume) that the basic default case (with default configuration), is that for console based output you want what structured arguments happens to output, and for JSON you want what logstash markers happen to output, however both seems really hard

There may be some configuration for `net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder` to do what I need to do (i.e. glob all of the the `key=value`'s out of message and put it as proper key/value in JSON), however I have no idea how to do this (and if so, its not really documented).

If this is intentional, maybe the best solution is to provide some pattern which transforms the JSON produced from `net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder` to a string based format that people typically are accustomed to when using `ch.qos.logback.classic.encoder.PatternLayoutEncoder` (for local/console based logging). 

By default this would do something as simple as flattening the key/values from the JSON (most log based formats don't output JSON that is greater than 1 level deep, it tends to be a flat key/value structure)

Alternately you can do something that will pretty print the JSON in a format like CSON (https://github.com/bevry/cson), would definitely be happy if the example JSON can be printed to something like

```cson
message: "Some message"
user_id: 1
```

Which would like fine on the console (and regardless of the how nested the JSON is, it would look as good as possible)

**Comment by philsttr** [comment]
Hi,

If you want multi-line, formatted output on the console, you can configure a pretty printer like [this](https://github.com/logstash/logstash-logback-encoder#customizing-json-factory-and-generator).  You can also disable field name quoting by disabling `JsonGenerator.Feature.QUOTE_FIELD_NAMES`.

The downside to multi-line output is that if multiple threads are writing to the console, then the lines can interleave.  However, you can avoid that by using a `LoggingEventAsyncDisruptorAppender` to delegate all the output to be from one thread.

Here is a complete example:

First, define a `JsonFactoryDecorator`:

```java
public class UnquotedFieldNameJsonFactoryDecorator implements JsonFactoryDecorator {
    @Override
    public MappingJsonFactory decorate(MappingJsonFactory factory) {
        return (MappingJsonFactory) factory.disable(JsonGenerator.Feature.QUOTE_FIELD_NAMES);
    }
}
```

And a `JsonGeneratorDecorator`:

```java
public class PrettyPrintingJsonGeneratorDecorator implements JsonGeneratorDecorator {
    @Override
    public JsonGenerator decorate(JsonGenerator generator) {
        return generator.useDefaultPrettyPrinter();
    }
}

```

And configure your console appender like this

```xml
    <appender name="console" class="net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender">
        <appender class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
                <jsonGeneratorDecorator class="PrettyPrintingJsonGeneratorDecorator"/>
                <jsonFactoryDecorator class="UnquotedFieldNameJsonFactoryDecorator"/>
                <providers>
                    <message/>
                    <arguments/>
                </providers>
            </encoder>
        </appender>
    </appender>
```

Then logging a message like this:

```java
LOGGER.info("Some message", kv("user_id", 1));
```

will output this:

```
{
  message: "Some message",
  user_id: 1
}
```

Is that close to what you want?

I know it's pretty complicated.  Unfortunately, logback was not designed for structured logging, so the logstash-logback-encoder has to work within the bounds of logback itself  (i.e. arguments are always substituted into placeholders in the message, and logback's encoders/layouts do not append markers).  I'd love to redesign logback so it has first-class support for structured logging.

**Comment by mdedetrich** [comment]
Thanks, I will attempt to use generator/decorator, that looks like what I am looking for.

One other thing (that is slightly confusing), with

```xml
    <appender name="console" class="net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender">
        <appender class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
                <jsonGeneratorDecorator class="PrettyPrintingJsonGeneratorDecorator"/>
                <jsonFactoryDecorator class="UnquotedFieldNameJsonFactoryDecorator"/>
                <providers>
                    <message/>
                    <arguments/>
                </providers>
            </encoder>
        </appender>
    </appender>
```

Can you use a `net.logstash.logback.encoder.LogstashEncoder` instead of a `net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder`? I basically want the same behaviour as `net.logstash.logback.encoder.LogstashEncoder`, I just want to add some K/V fields

**Comment by philsttr** [comment]
Hi @mdedetrich 

Sorry for the late reply.  I didn't notice your comment until I was reviewing open issues.

Yes, you should be able to use `net.logstash.logback.encoder.LogstashEncoder` as follows:

```xml
    <appender name="console" class="net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender">
        <appender class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LogstashEncoder">
                <jsonGeneratorDecorator class="PrettyPrintingJsonGeneratorDecorator"/>
                <jsonFactoryDecorator class="UnquotedFieldNameJsonFactoryDecorator"/>
                <provider class="net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider"/>
            </encoder>
        </appender>
    </appender>
```

It's an oversight that the `ArgumentsJsonProvider` is not configured by default in the `LogstashEncoder`.  Will get that fixed in a future release.

**Comment by philsttr** [comment]
I created #169 to add structured arguments support to `LogstashEncoder` and `LogstashLayout`

Closing this issue.
