### ISSUE TITLE
LogstashAccessEncoder does not support global custom fields

### ISSUE THREAD

**Issue by avallen** [logstash/logstash-logback-encoder#139]
Would be good to point this out in the documentation which is not clear about this.

I wonder why this is and if the suggested alternative is to configure a `AccessEventCompositeJsonEncoder` together with a Pattern JSON provider.

**Comment by philsttr** [comment]
Hi @avallen ,

It's just an oversight.

Yes, the current way to do this would be to use a pattern JSON provider.

You can add a pattern provider to a `LogstashAccessEncoder` like this:

```xml
<encoder class="net.logstash.logback.encoder.LogstashAccessEncoder">
    <provider class="net.logstash.logback.composite.accessevent.AccessEventPatternJsonProvider">
        <pattern>{"foo":"bar"}</pattern>
    </provider>
</encoder>
```

Or you can use `AccessEventCompositeJsonEncoder` instead of a `LogstashAccessEncoder` like you mentioned.

**Comment by harbulot** [comment]
@philsttr I was unable to get the configuration you suggested in your previous comment to work. However, the PR (#157) I've just submitted adds support for these fields with `<customFields />`. It seems to work.

**Comment by philsttr** [comment]
PR #157 merged to master.  Will be included in next release.
