### ISSUE TITLE
Does LogstashAccessEncoder support temporarily store unsent log to local storage?

### ISSUE THREAD

**Issue by hbprotoss** [logstash/logstash-logback-encoder#140]
We use logback on Android to log to logstash. If the App terminated with logs unsent, the logs are lost. May I ask whether it is possible to store unsent log to local storage, and resend when the App recovers?

**Comment by philsttr** [comment]
Hi @hbprotoss,

Unfortunately, the `LogstashTcpSocketAppender` only buffers to memory, not disk

**Comment by hbprotoss** [comment]
@philsttr OK

**Comment by sridhar1982** [comment]
is that configurable? i.e how much memory can be used for buffer?

**Comment by philsttr** [comment]
Yes.  You can specify the appender's [ringBufferSize](https://github.com/logstash/logstash-logback-encoder/blob/b0e7400ca16d5ec8211c0b5fe4b7203975bc30ad/src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java#L104-L113)

For example:
```xml
    <appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <ringBufferSize>4096</ringBufferSize>
```

This is the max number of log events that will be buffered, and must be a power of 2.  Default is 8192.

The actual amount of memory consumed will vary based on your log event size.
