### ISSUE TITLE
Nested field application.home in message

### ISSUE THREAD

**Issue by cchantep** [logstash/logstash-logback-encoder#141]
It seems a `application.home` field is present in the JSON object provided as value for the `message` field. 

When the `json` codec is configured in the Logstash configuration, then an error is raised as `application.home` is an invalid field name for document in ES.

Is there any way to fix/workaround that?

**Comment by philsttr** [comment]
A field named `application.home` is not explicitly written by `LogstashEncoder`.  That field must be coming from your application.

It could potentially be a property defined in your logback context.  See [here](https://github.com/logstash/logstash-logback-encoder#loggingevent_context) for how to disable output of logback context properties.
