### ISSUE TITLE
What kind of interface does it support ?

### ISSUE THREAD

**Issue by cppexpert** [logstash/logstash-logback-encoder#144]
Does this appender uses Logstash Beats interface or Logstash Lumberjack interface ?

**Comment by philsttr** [comment]
The [UDP appender](https://github.com/logstash/logstash-logback-encoder#udp) uses UDP.  You can configure logstash with a 'udp' input or a 'syslog' input, like this:

```
input {
  syslog {
    codec => "json"
  }
}
```

The [TCP appenders](https://github.com/logstash/logstash-logback-encoder#tcp) use newline-delimited JSON over TCP.  You can configure logstash with a 'tcp' input, like this:

```
input {
    tcp {
        port => 4560
        codec => json_lines
    }
}
```
