### ISSUE TITLE
DateTime fields for ObjectAppendingMarker

### ISSUE THREAD

**Issue by jama707** [logstash/logstash-logback-encoder#145]
Hi,
Is there any way of converting Joda's `DateTime` object to its string representation when we use `Markers.appendFields(object)` with logstash encoder? I couldn't find a way from documentations.

The default behavior is creating a JSON object with all date properties, something like:
```"year":2012,"dayOfMonth":24,"dayOfWeek":1,"era":1,"dayOfYear":359,"centuryOfEra":20,"yearOfEra":2012,"yearOfCentury":12,"weekyear":2012,"monthOfYear":12 ```

**Comment by philsttr** [comment]
Hi @jama707 ,

Yes, you should be able to do this by defining a custom `JsonFactoryDecorator` as described [here](https://github.com/logstash/logstash-logback-encoder#custom_factory).

For example:

```java
import net.logstash.logback.decorate.JsonFactoryDecorator;

public class JodaJsonFactoryDecorator implements JsonFactoryDecorator {
    @Override
    public MappingJsonFactory decorate(MappingJsonFactory factory) {
        factory.getCodec().registerModule(new JodaModule());
        return factory;
    }
}
```

and then configure the decorator in your configuration like this

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
  <jsonFactoryDecorator class="your.package.JodaJsonFactoryDecorator "/>
</encoder>
```

I haven't tested this, but it should work.  Let me know if it doesn't.

**Comment by jama707** [comment]
Thank you, @philsttr ! I didn't know it would be easier with `JsonFactoryDecorator`, I used `JsonGeneratorDecorator` which is wrong even though it works.

```
public class LogstashDateTimeJsonProvider implements JsonGeneratorDecorator {

    public static final JodaModule MODULE = new JodaModule();

    /**
     * Joda DateTime objects are converted into their string representation instead of JSON Object.
     *
     * @param generator - Logstash JsonGenerator with default configurations.
     * @return JsonGenerator enriched with an ability to convert Joda DateTime to String.
     */
    @Override
    public JsonGenerator decorate(JsonGenerator generator) {
        ObjectMapper objectMapper = (ObjectMapper)  factory.getCodec();
        objectMapper.registerModule(MODULE);
        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        generator.setCodec(objectMapper);
        return generator;
    }
}
```

**Comment by philsttr** [comment]
Yeah, it'll work with a `JsonGeneratorDecorator`.  However, the main reason to use `JsonFactoryDecorator` for this rather than `JsonGeneratorDecorator` is that the `JsonFactoryDecorator` will only be called once (during startup), but the `JsonGeneratorDecorator` is called for every event.  So doing configuration in a `JsonFactoryDecorator` will be more efficient.
