### ISSUE TITLE
NestedField not working

### ISSUE THREAD

**Issue by anthonylau** [logstash/logstash-logback-encoder#146]
Version 4.5.1

```
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <nestedField>
                    <fieldName>nested</fieldName>
                    <providers>
                        <rawMessage>
                            <fieldName>customRawMessage</fieldName>
                        </rawMessage>
                    </providers>
                </nestedField>
           </providers>
</encoder>
```

> 11:11:56,084 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@26:30 - no applicable action for [nestedField], current ElementPath  is [[configuration][appender][encoder][providers][nestedField]]

**Comment by philsttr** [comment]
Hey @anthonylau 

The nestedField was added after 4.5.1, and hasn't been released yet.  I'll release it soon

**Comment by philsttr** [comment]
4.6 has been released and is on its way to maven central
