### ISSUE TITLE
How Can i log to both file and sent to logstash 

### ISSUE THREAD

**Issue by ashishsoni** [logstash/logstash-logback-encoder#148]
Just wanted to know if logstash is not available we can still fall back to log in the local file , please let me know how it can be done

**Comment by osigida** [comment]
we do it like that, works fine: 

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>/log/file_name.log</file>
    <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
        <Pattern>%d{yyyy-MM-dd_HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</Pattern>
    </encoder>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
        <fileNamePattern>/log/file_name.%d{yyyy-MM-dd}.log.gz</fileNamePattern>
        <maxHistory>7</maxHistory>
        <cleanHistoryOnStart>true</cleanHistoryOnStart>
    </rollingPolicy>
</appender>

<appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
    <remoteHost>LOGSTASH_HOST</remoteHost>
    <port>LOGSTASH_PORT</port>
    <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
</appender>
<root level="INFO">
    <appender-ref ref="file" />
    <appender-ref ref="stash" />
</root>
</configuration>
```

**Comment by ashishsoni** [comment]
Thanks , Is is possible to share the logstash configuration also to receive this on TCP socket a example conf will be helpful

**Comment by osigida** [comment]
you'd better to follow logstash documentation
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-tcp.html

**Comment by philsttr** [comment]
@ashishsoni, A very simple example on how to configure logstash with a tcp input is provided in the [TCP Appenders](https://github.com/logstash/logstash-logback-encoder/blob/master/README.md#tcp-appenders) section.

But, as @osigida , logstash's documentation is the primary source for how to configure it.
