### ISSUE TITLE
LogstashTcpSocketAppender how to log dropped events

### ISSUE THREAD

**Issue by rogerwelin** [logstash/logstash-logback-encoder#151]
This probably isn't an issue, I'm just not quite sure how to implement it. What I want is that when the buffer gets full and drop events this will get logged (local logging is fine).

I use an LogstashTcpSocketAppender appender and have set the following config:

`<ringBufferSize>512</ringBufferSize>`
`<droppedWarnFrequency>1</droppedWarnFrequency> `

I also set up a RollingFileAppender where I expected the warnings to end up.

Even though logstash isn't available I see no warning regarding dropped events. Any ideas what I'm missing?

**Comment by philsttr** [comment]
Hey @rogerwelin 

The warnings are currently sent to logback's [status listener](http://logback.qos.ch/manual/configuration.html#statusListener).

So, to "hear" them, you can register a status listener with logback.  Your listener can do whatever it wants with those status events (log them to another logger, print them on the console, etc)

**Comment by rogerwelin** [comment]
thanks for the hint @philsttr, that did the trick. Great project btw!
