### ISSUE TITLE
I can not use PatternLayoutEncoder and LogstashEncoder together

### ISSUE THREAD

**Issue by Yancey1989** [logstash/logstash-logback-encoder#152]
Here is my logback.xml,
'''
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>127.0.0.1:4561</destination>

        <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
    </appender>
    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
        <file>app.log</file>

        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <Pattern>
                %d{yyyy-MM-dd HH:mm:ss} [%thread] %level %logger{35} - %msg%n
            </Pattern>
        </encoder>
    </appender>
    <root level="DEBUG">
        <appender-ref ref="stash" />
        <appender-ref ref="FILE" />
    </root>

</configuration>
'''
there are two appender, LogstashTcpSocketAppender and FileAppender. 
With this config file, my logstash can not received the message,  when I fix FileAppender->encoder to LogstashEncoder, it will be ok, it seems like there only can be one encoder in one config file.

**Comment by osigida** [comment]
this one looks ok for me 

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>/log.log</file>
    <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
        <Pattern>%d{yyyy-MM-dd_HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</Pattern>
    </encoder>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
        <fileNamePattern>/log.%d{yyyy-MM-dd}.log.gz</fileNamePattern>
        <maxHistory>7</maxHistory>
        <cleanHistoryOnStart>true</cleanHistoryOnStart>
    </rollingPolicy>
</appender>

<appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
    <destination>HOST:PORT</destination>
    <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
</appender>

<root level="INFO">
    <appender-ref ref="file" />
    <appender-ref ref="stash" />
</root>
</configuration>
```

**Comment by Yancey1989** [comment]
Thanks @osigida, but this config file can not work for me, what's your logback version?

**Comment by osigida** [comment]
we use something recent:
```
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>1.1.3</version>
            </dependency>
            <dependency>
                <groupId>net.logstash.logback</groupId>
                <artifactId>logstash-logback-encoder</artifactId>
                <version>4.5.1</version>
            </dependency>
```

**Comment by philsttr** [comment]
@Yancey1989, where you able to get this working?

**Comment by Yancey1989** [comment]
@philsttr We fix this problem, but not cased by the config file,maybe the other reason does it.
We add "sleep 10 seconds" before exit main function, it works ok. Maybe there is some thing like cache, these message will be droped when main function exit.

**Comment by philsttr** [comment]
Hi @Yancey1989 ,

The TCP appender is asynchronous.  It uses a daemon thread to actually send messages.  So, your application is probably shutting down before that thread gets a chance to finish sending the messages.

See this note (from [the Async Appenders section in the README.md](https://github.com/logstash/logstash-logback-encoder#async-appenders))

>In order to guarantee that logged messages have had a chance to be processed by asynchronous appenders (including the TCP appender), you'll need to [cleanly shut down logback](http://logback.qos.ch/manual/configuration.html#stopContext) when your application exits.
