### ISSUE TITLE
LogstashTcpSocketAppender: Handling of UnknownHostExceptions

### ISSUE THREAD

**Issue by markbigler** [logstash/logstash-logback-encoder#159]
Our application is doing an automatic re-configuration (at runtime) of the logging mechanism (e.g. replace console/file appenders with logstash-appender) as soon as it detects the "logstash credentials".

In case of an accidential missconfiguration for the logstash host property, the `start()` process of the logstash appender keeps trying to connect to the unknown host. Of course a log message is
written after some attemps but since we need to know when (and if at all) the logstash appender is connected and starts to send log messages it would be nice to have an interface/listener to retrieve
status messages (connecting, connected, disconnected, ...).

Any thoughts on this?

**Comment by philsttr** [comment]
Definitely a good idea.

I've wanted to add support for a custom listener that can hear the following events, but just haven't implemented it yet:
* connection established
* connection failed / lost
* buffer full / dropping messages
* resuming messages
* maybe others.  Basically, a lot of what is currently logged to logback's status listener.

In the meantime, you could use logback's [StatusListener](http://logback.qos.ch/manual/configuration.html#statusListener), and watch for events that contain specific strings (e.g. [`connection established`](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L541)).  Yes, I know this is not ideal, but I wanted to suggest it as an intermediate solution before a true listener is implemented.

**Comment by kongslund** [comment]
Such a listener would definitely be valuable to have, e.g. a Spring Boot application could transform the events into metrics allowing an administrator to detect connection issues, misconfigurations etc.

**Comment by philsttr** [comment]
Appender listeners added in 5.0
