### ISSUE TITLE
get NPE when adding and then accessing customfields programmatically

### ISSUE THREAD

**Issue by ssatguru** [logstash/logstash-logback-encoder#161]
the following code does not add custom fields and throws a NPE on getCustomfields()

``
        LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
	
	// encoder
	LogstashEncoder le = new LogstashEncoder();
	le.setContext(context);
	
	String customfield = "{\"foo\":\"bar\"}";
	le.setCustomFields(customfield);
        //NPE thrown by next line
	System.out.println("customefields " + le.getCustomFields());
	
	// appender
	LogstashTcpSocketAppender appender = new LogstashTcpSocketAppender();
	appender.setContext(context);
	appender.setEncoder(le);
	appender.addDestination("localhost:4560");
	appender.start();

	// log
	ch.qos.logback.classic.Logger log = (ch.qos.logback.classic.Logger) LoggerFactory.getLogger("com.foo.bar.logger");
	log.addAppender(appender);
	log.setLevel(Level.INFO);

	log.info("test");
``

**Comment by philsttr** [comment]
@ssatguru 

Thanks for the report.  Will get this fixed.

**Comment by philsttr** [comment]
Fixed in fe31841952d4ca665cc17f89fb4d3a6a6539eb74 for the next release.

**Comment by ssatguru** [comment]
tested again.
works as expected.
thanks for the quick fix
