### ISSUE TITLE
Global Custom Fields: How to?

### ISSUE THREAD

**Issue by marcellodesales** [logstash/logstash-logback-encoder#162]
According to https://github.com/logstash/logstash-logback-encoder#loggingevent_custom_global, we can produce the output:

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
  <customFields>{"appname":"myWebservice","roles":["customerorder","auth"],"buildinfo":{"version":"Version 0.1.0-SNAPSHOT","lastcommit":"75473700d5befa953c45f630c6d9105413c16fe1"}}</customFields>
</encoder>
```

* How can I get this automatically generated?
* How can I extract the appname and version of the app from build.gradle?
* How can I get the value of the lastcommit?

thanks!

**Comment by osigida** [comment]
you'd better ask such a question on maven forum

**Comment by philsttr** [comment]
Yeah, I'm not an expert on gradle, but you could generate your logback xml config file using a template, and substitute params provided by gradle like [this](http://mrhaki.blogspot.com/2010/10/gradle-goodness-parse-files-with.html).

Alternatively, if your build puts the name/version/commit in a `META-INF/MANIFEST.MF` (or any other) file in your jar, you could write a custom [provider](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/composite/JsonProvider.java) that pulled that metadata out of the file, and add it to the json output.
