### ISSUE TITLE
Normalize access log Response/Request headers

### ISSUE THREAD

**Issue by gjdev** [logstash/logstash-logback-encoder#163]
The ResponseHeadersJsonProvider and RequestHeadersJsonProvider providers create fields for every capitalisation of headers used. So you may end up with fields for 'Location', 'location', and 'LOCATION' if clients use these different capitalizations. It would be nice if there was an option to lowercase these fieldnames. That makes searches, filters, and visualisations for a specific field a lot easier.
Note that according to the HTTP protocol specs the fieldnames are case insensitive.

**Comment by philsttr** [comment]
Implemented, and will be available in the next release.
