### ISSUE TITLE
ShortenedThrowableConverter wrong documentation

### ISSUE THREAD

**Issue by vshalts** [logstash/logstash-logback-encoder#165]
According to documentation:
Options can be specified in the pattern in the following order:
- maxDepthPerThrowable = "full" or "short" or an integer value
- maxLength = "full" or "short" or an integer value
- shortenedClassNameLength = "full" or "short" or an integer value

and in
> <pattern>[%thread] - %msg%n%stack{5,1024,10,rootFirst,regex1,regex2,evaluatorName}</pattern>

but in code
```
private static final int OPTION_INDEX_MAX_DEPTH = 0;
private static final int OPTION_INDEX_SHORTENED_CLASS_NAME = 1;
private static final int OPTION_INDEX_MAX_LENGTH = 2;
```

So,  in reality shortenedClassNameLength is prior to maxLength.

**Comment by philsttr** [comment]
Fixed.  Thanks for the report!
