### ISSUE TITLE
Configurable value for destination element

### ISSUE THREAD

**Issue by rbkumar88** [logstash/logstash-logback-encoder#166]
Hi,

Is there any way we can specify the destination element to pull from ENV and fallback to a default value if not set (say LOGSTASH.URI is not set)

<destination>${LOGSTASH.URI:"XXXX:YYYY"}</destination>

where XXXX:YYYY are default host:port

Thanks
Bharath

**Comment by philsttr** [comment]
Sure.  See logback's documentation [here](http://logback.qos.ch/manual/configuration.html#defaultValuesForVariables)
