### ISSUE TITLE
OSGI maven hell

### ISSUE THREAD

**Issue by piyushGoyal2** [logstash/logstash-logback-encoder#167]
Hi Team,

I am trying to use logstash-logback-encoder as an OSGI bundle in felix. The problem is the dependencies it depends upon is creating a maven hell chain. logstash-logback-encoder->logback-access->tomcat-catlina-> .....
And I haven't talked about the logback-classic jar.

Is there a way that these dependencies can be bundled out together in the logstash-logback-encoder bundle or atleast the uncommon jars are packed together with the main bundle/jar.

**Comment by osigida** [comment]
https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by piyushGoyal2** [comment]
Thanks @osigida for the link but this would work when you are compiling your source code and maven needs the jar from repository which might not be there. I am talking about what happens when you deploy your application in OSGI container such as felix. There since logstash-logback-encoder is deployed as a bundle, it would need all the dependencies as bundles in the OSGI. I am only using code related to logback-classic and nowhere using logback-access code. However in order to make logback-access resolved in OSGI, I need 12 more jars weighing upto 12 MB. dugh!!!

**Comment by philsttr** [comment]
Hi @piyushGoyal2 ,

For the next major release, I'll consider breaking up logstash-logback-encoder into multiple modules to solve the runtime OSGI dependency problem.

In the meantime, in the `MANIFEST.MF` the import of logback-access is currently marked as optional....

```
Import-Package: ch.qos.logback.access;version="[1.1,2)";resolution:=op
 tional,ch.qos.logback.access.spi;version="[1.1,2)";resolution:=option
 al,...
```

Can you configure your OSGI container to ignore these optional imports?

**Comment by piyushGoyal2** [comment]
Thanks @philsttr for taking it as an enhancement. For the time being, I added the unwanted packages of logback-access to import packages. I know its a risky thing to do. But for logstash-logback-encoder, I knew for sure that I would not break anything. Looking to see the enhancement soon.
Thanks
Piyush

**Comment by philsttr** [comment]
Not planning on splitting up logstash-logback-encoder.
