### ISSUE TITLE
Using LogstashTcpSocketAppender + includeCallerInfo doesn't work

### ISSUE THREAD

**Issue by Aiden-Wang** [logstash/logstash-logback-encoder#170]
In Logback.xml:
`	<appender name="logstash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
	    <destination>10.5.0.182:4567</destination>
	    <encoder class="net.logstash.logback.encoder.LogstashEncoder" >
	    	<includeCallerData>true</includeCallerData>
	    	<customFields>{"server_name":"registSrv"}</customFields>
	    </encoder>
	    <keepAliveDuration>1 minutes</keepAliveDuration>
	</appender>
`
why don't output the fields : caller_class_name, caller_method_name ?

**Comment by philsttr** [comment]
Hi @Aiden-Wang 

See this note in the documentation:

> If the encoder is included inside an asynchronous appender, such as AsyncAppender, LoggingEventAsyncDisruptorAppender, or LogstashTcpSocketAppender, then includeCallerData must be set to true on the appender as well.

So, you'll need to do this:

```
	<appender name="logstash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
	    <destination>10.5.0.182:4567</destination>
	    <encoder class="net.logstash.logback.encoder.LogstashEncoder" >
	    	<includeCallerData>true</includeCallerData>
	    	<customFields>{"server_name":"registSrv"}</customFields>
	    </encoder>
	    <includeCallerData>true</includeCallerData>
	    <keepAliveDuration>1 minutes</keepAliveDuration>
	</appender>
```
