### ISSUE TITLE
@Version is generated as an integer.

### ISSUE THREAD

**Issue by ls-yann-david** [logstash/logstash-logback-encoder#171]
@version is an integer where every other lib/slurp agent send it as a string. It's not a big issue except when it comes to Elasticsearch V2 which doesn't accept field with the same name having multiple type in a given index.

Example:

event1.@version = 1
event2.@version = "1"

This would prevent elasticsearch from restarting/starting.

**Comment by philsttr** [comment]
Hi @ls-yann-david 

For backwards compatibility, I need to leave the default behavior as-is until the next major release (5.0).  I'll consider changing the default in 5.0.

Until then, I have added the ability to optionally write the version value as a string.  See the [updated documentation](https://github.com/logstash/logstash-logback-encoder#custom_version).
This will be available in the next minor release (4.8)
