### ISSUE TITLE
Logging request attributes - outdated disclaimer on Logback issue

### ISSUE THREAD

**Issue by adammichalik** [logstash/logstash-logback-encoder#175]
The [README](https://github.com/logstash/logstash-logback-encoder/blob/master/README.md) says that

> Note that the latest Logback (1.1.2 at the moment of writing), does not support deferred processing of request attributes. And because LogstashAccessTcpSocketAppender defers processing of the event to a background thread, you won't be able to use "%requestAttribute{name}" with TCP appender until this issue is fixed (or you build yourself a custom logback). http://jira.qos.ch/browse/LOGBACK-1033

The linked Logback issue has been resolved in version 1.1.3, on 28/Jan/15. I assume that logging of request attributes now works, making the disclaimer obsolete, so it can be removed from the README.

**Comment by philsttr** [comment]
Fixed.  Thanks for the report!
