### ISSUE TITLE
LogstashLayout not able to generate nested fields

### ISSUE THREAD

**Issue by adeelmahmood** [logstash/logstash-logback-encoder#179]
I am trying to customize the JSON logging output generated by logstash to include a nested field. This is how I have configured my layout (using a kafka appender)

`<layout class="net.logstash.logback.layout.LogstashLayout">
<providers>
					<nestedField>
						<fieldName>customField</fieldName>
						<providers>
							<logLevel/>
						</providers>
					</nestedField>
				</providers>`

For some reason, this has no effect. There is no customField in the output.

**Comment by philsttr** [comment]
Hey @adeelmahmood ,

`LogstashLayout` requires a predefined set of providers, so you can't really override all the providers at the same time using the `providers` tag.

You have a couple options:

1) If you want to use a custom set of providers, you can use: `LoggingEventCompositeJsonLayout` like this:

```
<layout class="net.logstash.logback.layout.LoggingEventCompositeJsonLayout">
	<providers>
		<nestedField>
			<fieldName>customField</fieldName>
			<providers>
				<logLevel/>
			</providers>
		</nestedField>
	</providers>
```

or

2) If you just want to add to the providers already used by `LogstashLayout`, you can add an individual provider to its set of providers like this:

```
<layout class="net.logstash.logback.layout.LogstashLayout">
	<provider class="net.logstash.logback.composite.loggingevent.LoggingEventNestedJsonProvider">
		<fieldName>customField</fieldName>
		<providers>
			<logLevel/>
		</providers>
	</provider>
```

**Comment by adeelmahmood** [comment]
Thanks - that was very helpful.

**Comment by adeelmahmood** [comment]
One question though - In the second method (LoggingEventNestedJsonProvider), if the customField was already a provider for the LogstashLayout it shows up twice. In my example, I want to nest the logstashMarkers in a custom field.

`<layout class="net.logstash.logback.layout.LogstashLayout">
				<provider class="net.logstash.logback.composite.loggingevent.LoggingEventNestedJsonProvider">
			        <fieldName>markers</fieldName>
			        <providers>
			            <logstashMarkers/>
			        </providers>
			    </provider>
			</layout>`

The JSON output includes the markers both at the root level and inside the custom makers field. Is there a way to exclude them from the root level ?

**Comment by philsttr** [comment]
You'll need to use `LoggingEventCompositeJsonLayout` instead of `LogstashLayout` if you want that level of customization.
