### ISSUE TITLE
how to add NULL after each log entry using encoder?

### ISSUE THREAD

**Issue by sridhar1982** [logstash/logstash-logback-encoder#181]
I am using TCPappender to send my log entries to logstash server. Our logtash server requires to add [NULL character](https://en.wikipedia.org/wiki/Null_character) or [SOH character](https://en.wikipedia.org/wiki/C0_and_C1_control_codes#SOH) after each json log entry for the logstash server to differentiate between entries?

My message looks like the following (three messages). just like how there is new line after each message, I would like to add NULL. how is that possible? The other option for me is to close the connection after I sent each message. but I guess that is not an idea I can use in production.

Thanks

```
{"@timestamp":"2016-08-11T12:35:00.512-07:00","data_version":1,"description":"log message1","logger_name":"in.sdqali.spring.GreetingController","thread_name":"http-nio-2020-exec-1","level":"ERROR","level_value":40000,"HOSTNAME":"13MBP-13447.local","Greeting":{"id":1,"content":"Hello, World!"},"application":"helloWorld","type":"log","correlation-id":"dummy-value","caller_class_name":"in.sdqali.spring.GreetingController","caller_method_name":"greeting","caller_file_name":"GreetingController.java","caller_line_number":31}
{"@timestamp":"2016-08-11T12:36:52.881-07:00","data_version":1,"description":"log message1","logger_name":"in.sdqali.spring.GreetingController","thread_name":"http-nio-2020-exec-2","level":"ERROR","level_value":40000,"HOSTNAME":"13MBP-13447.local","Greeting":{"id":2,"content":"Hello, World!"},"application":"helloWorld","type":"log","correlation-id":"dummy-value","caller_class_name":"in.sdqali.spring.GreetingController","caller_method_name":"greeting","caller_file_name":"GreetingController.java","caller_line_number":31}
{"@timestamp":"2016-08-11T12:37:05.320-07:00","data_version":1,"description":"log message1","logger_name":"in.sdqali.spring.GreetingController","thread_name":"http-nio-2020-exec-3","level":"ERROR","level_value":40000,"HOSTNAME":"13MBP-13447.local","Greeting":{"id":3,"content":"Hello, World!"},"application":"helloWorld","type":"log","correlation-id":"dummy-value","caller_class_name":"in.sdqali.spring.GreetingController","caller_method_name":"greeting","caller_file_name":"GreetingController.java","caller_line_number":31}
```

**Comment by philsttr** [comment]
The `CompositeJsonEncoder` (which is a superclass of `LogstashEncoder`) supports configuring the line separator.  By default it uses the os' default line separator.

So, ideally you would be able to configure the lineSeparator like this, in xml 1.1:

```xml
<?xml version="1.1" encoding="UTF-8"?>
<configuration debug="true">
    <appender ...>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <lineSeparator>&#0001;</lineSeparator>
        </encoder>
```

(Note that NULL cannot be encoded in xml 1.0 or 1.1.  SOH cannot be encoded in xml 1.0, but can be encoded in xml 1.1)

Unfortunately, even though this is valid xml 1.1, logback's xml configuration reader (joran) will not set a property to a value that is only whitespace.  You can see this behavior [here](https://github.com/qos-ch/logback/blob/151857344eaefda8f641d93ac23e9e2c1be2b723/logback-core/src/main/java/ch/qos/logback/core/joran/event/SaxEventRecorder.java#L116-L119)

Therefore, you cannot configure using NULL or SOH through logback's XML configuration.

You can, however programmatically configure the encoder to use a NULL or SOH character.  See [this stackoverflow answer](http://stackoverflow.com/questions/16910955/programmatically-configure-logback-appender) for how to configure logback programmatically.

You would just need to call `encoder.setLineSeparator(new String(new char[] {0}))`

**Comment by philsttr** [comment]
Of course, you could always change your destination side to allow line endings as separators as well.

**Comment by sridhar1982** [comment]
Thanks again, changing destination side is out of possibility for us. I will see how to configure programmatically for my spring application since I want both TCP and file appenders
