### ISSUE TITLE
Failed to work on Spring boot 1.4

### ISSUE THREAD

**Issue by choelea** [logstash/logstash-logback-encoder#184]
After I upgrade the Spring boot from 1.3.3 to 1.4.0, I encountered below error:

java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:152)

**Comment by philsttr** [comment]
This is caused by a bug in logback.  Please see #160.

**Comment by choelea** [comment]
Thanks,   get it
