### ISSUE TITLE
Easier AccessLogs configuration (ex for HTTP Headers)

### ISSUE THREAD

**Issue by tomaszglinski** [logstash/logstash-logback-encoder#194]
My starting point is that I would like to add to access logs single HTTP header (all of them would be too heavy), but currenty there is no "nice" configuration for that.

The current workaround would be to redefine whole Json pattern via AccessEventJsonPatternLayoutEncoder and add my header to it.

My proposals:
 - provide direct configuration possibility to choose which headers are to be logged
AND/OR
 - for AccessEventJsonPatternLayoutEncoder (and other encoders too where it applies) enable "merging", so the pattern I provide is merged into standard one

**Comment by ChrisMacpherson-awin** [comment]
This would be useful for us also as want to easily exclude certain headers (like Authorization).

**Comment by philsttr** [comment]
Ability to include/exclude request/response headers added in 5.0
