### ISSUE TITLE
Question: Preprocess request/response headers

### ISSUE THREAD

**Issue by moleksyuk** [logstash/logstash-logback-encoder#196]
Hi,
I need to replace in all request/response headers '.' symbol (if it exists) before write to JSON.

Could someone point me which way I should look, please?

**Comment by philsttr** [comment]
You could do something similar to what I mentioned [here](https://github.com/logstash/logstash-logback-encoder/issues/138#issuecomment-163009097)

**Comment by moleksyuk** [comment]
@philsttr thanks a lot 👍
