### ISSUE TITLE
QUESTION:Chinese Logged As Unicode char

### ISSUE THREAD

**Issue by looqy** [logstash/logstash-logback-encoder#197]
when I use **net.logstash.logback.encoder.LogstashEncoder** output chinese chars to log file, they always change to unicode char, like _\u5FAE\u670D\u52A1\u51FA\u9519\uFF0C\u8BF7_,
I've tried config **charset=utf-8** whin LogstashEncoder, but it's not working,
Could someone tell me what can i do? thank you!
my logback.xml:

```
<appender name="stash" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
      <level>info</level>
    </filter>
    <file>${catalina.home}/logs/sublogs/development.log</file>
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <fileNamePattern>${catalina.home}/logs/sublogs/development.log.%d{yyyy-MM-dd}</fileNamePattern>
      <maxHistory>30</maxHistory>
    </rollingPolicy>
    <encoder class="net.logstash.logback.encoder.LogstashEncoder">
          <charset>UTF-8</charset>    
    </encoder>
</appender>
```

**Comment by philsttr** [comment]
[UTF-8 is used by default](https://github.com/logstash/logstash-logback-encoder/blob/7d21a2f1973bd504e515a37b5f7a1363095bf871/src/main/java/net/logstash/logback/composite/CompositeJsonFormatter.java#L108).  However, the jackson option for escaping non-ascii characters is also [enabled by default](https://github.com/logstash/logstash-logback-encoder/blob/7d21a2f1973bd504e515a37b5f7a1363095bf871/src/main/java/net/logstash/logback/composite/CompositeJsonFormatter.java#L76).

You can override this behavior by creating class that a implements `JsonFactoryDecorator` and disables that option like this:

```java
import net.logstash.logback.decorate.JsonFactoryDecorator;

public class NoEscapingJsonFactoryDecorator implements JsonFactoryDecorator {
    @Override
    public MappingJsonFactory decorate(MappingJsonFactory factory) {
        return (MappingJsonFactory) factory.disable(JsonGenerator.Feature.ESCAPE_NON_ASCII);
    }
}
```

Then configure the LogstashEncoder to use `NoEscapingJsonFactoryDecorator` like this

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
  <jsonFactoryDecorator class="your.package.NoEscapingJsonFactoryDecorator"/>
</encoder>
```

**Comment by lalmeme** [comment]
thanks

**Comment by philsttr** [comment]
#261 will disable ESCAPE_NON_ASCII by default
