### ISSUE TITLE
stackTrace as pattern layout keyword

### ISSUE THREAD

**Issue by evmin** [logstash/logstash-logback-encoder#200]
As a system administrator posting to GCP Logging, I would like to be able to make stack_trace as part of the message as opposed to a separate field.

I.e.

```
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
  <providers>
    <pattern>
      <!-- the pattern that defines what to include -->
      <pattern>
        { "level": "%level" , "message" : "%logger | %message %stackTrace" }}
      </pattern>
    </pattern>
  </providers>
</encoder>
```

**Comment by philsttr** [comment]
This is already possible.  You can either use logback's default stacktrace printer ([which uses the `%exception` conversion word](https://logback.qos.ch/manual/layouts.html#conversionWord)) like this:

```xml
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
  <providers>
    <pattern>
      <!-- the pattern that defines what to include -->
      <pattern>
        { "level": "%level" , "message" : "%logger | %message %exception" }}
      </pattern>
    </pattern>
  </providers>
</encoder>
```

OR, you can use the logback logstash encoder's [enhanced stacktrace converter](https://github.com/logstash/logstash-logback-encoder#customizing-stack-traces), by adding a conversion rule to your logback.xml like this:

```xml
<conversionRule
    conversionWord="stacktrace"
    converterClass="net.logstash.logback.stacktrace.ShortenedThrowableConverter" />
```
and then configuring the encoder like this

```xml
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
  <providers>
    <pattern>
      <!-- the pattern that defines what to include -->
      <pattern>
        { "level": "%level" , "message" : "%logger | %message %stacktrace{5,20,1024,rootFirst}" }}
      </pattern>
    </pattern>
  </providers>
</encoder>
```

See [ShortenedThrowableConverter](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java) for details on the options that can be configured for the stacktrace output.
