### ISSUE TITLE
Slf4j Marker with key value

### ISSUE THREAD

**Issue by tetv** [logstash/logstash-logback-encoder#207]
I am using logging implementation agnostic in my code.
Therefore the only reference that I have is to `slf4j-api` library.
That means nothing related to `logback` or `logstash-logback-encoders` is accessible.
This allows changing for a more modern logging implementation in the future without changing a line of code.

My thoughts is to do something like this:

```javascript
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.Marker;
import org.slf4j.MarkerFactory;
...
private final static Logger LOG = LoggerFactory.getLogger(MyClass.class);
...
Marker marker = MarkerFactory("keyValuePairs"); // Special marker name for key value pairs
Marker key1 = MarkerFactory("messageRaw");
Marker value1 = MarkerFactory("{\"key1\":\"value1\"}");
Marker type1 = MarkerFactory("Json"); // Special marker name for accept value as json
key1.add(value1);
value1.add(type1);
Marker key2 = MarkerFactory("myNumber");
Marker value2 = MarkerFactory("123");
Marker type2 = MarkerFactory("int"); // Special marker name for accept value as integer
key2.add(value2);
value2.add(type2);
marker.add(key1);
marker.add(key2);
...
LOG.info(marker, "Some message");
```

Configuring logging to use `backlog` implementation with `logstash-logback-encoders`, is it possible to have in json these two additional fields: `messageRaw` and `myNumber`?

PS: The code is just to be simple to understand, later I can create a helper library to deal with this complexity of creating Makers :)

**Comment by osigida** [comment]
why MDC doesn't work for you?

**Comment by tetv** [comment]
The main idea is to emulate the `structured arguments` that `logstash-logback-encoders` has out of the box, but using the standard `Slf4j`. The concept of structured arguments is a bit different than the Mapped Diagnostic Context (`MDC`).

In some scenarios `MDC` can be used, but in others it's a bit messy. The main reasons are:
1) MDC doesn't know how to convert to Json.
2) MDC is thread local based, and is not really designed to applications that are event base driven (use and abuse of multithreading) like [vertx applications](https://en.wikipedia.org/wiki/Vert.x).

**Comment by tetv** [comment]
I will close this issue, because Markers should be used for this purpose.
I think slf4j 2.0 will support `Structured Arguments`, which will be easy to implement.

As a workaround, I am just constructing a json message using pure slf4j and then I am using the extension #asJson (#208) that I have build which is working really well. I also implemented another additional extension #unlessJson for standard string message (when #asJson fails).

Therefore my json loggings will have this two properties:
`{ ..., "jsonMessage":"#asJson(%m)", "textMessage":"#unlessJson(%m)", ... }`

**Comment by gavenkoa** [comment]
* http://www.slf4j.org/api/org/slf4j/event/KeyValuePair.html
* http://www.slf4j.org/api/org/slf4j/event/LoggingEvent.html
