### ISSUE TITLE
ObjectAppendingMarker: Error in print the field with type Optional 

### ISSUE THREAD

**Issue by Miuler** [logstash/logstash-logback-encoder#209]
I'm using java 8 and the type Optional (Optional<String>, optional<Long>, etc), but the data printed from logstash encoder, show the Address.id.present: true instead of Address.id: 100

Please add suport for java 8:
ObjectMapper mapper = new ObjectMapper().registerModule(new Jdk8Module());

https://github.com/FasterXML/jackson-modules-java8

**Comment by philsttr** [comment]
Hi,

I'll have to see if the `Jdk8Module` can be safely added by default, and retain java 6 and 7 runtime compatibility.

In the meantime, you can customize the ObjectMapper however you like (including registering additional modules) by using a `JsonFactoryDecorator`.

See [here](https://github.com/logstash/logstash-logback-encoder#custom_factory)

**Comment by philsttr** [comment]
Closing this for now.  Cannot safely add the Jdk8 Module while logstash-logback-encoder still supports java 7.   As mentioned in my previous comment, the jdk 8 modules can be added via a `JsonFactoryDecorator`
