### ISSUE TITLE
The new line problem

### ISSUE THREAD

**Issue by zong400** [logstash/logstash-logback-encoder#212]
Hi all, I want to use logstash-logback-encoder to send java log to filebeat over udp.
And the problem is filebeat recived data is like that:
{"@timestamp": log1}{"@timestamp": log2}{"@timestamp": log3}{"@timestamp": log4}
all log in one line. filebeat can not analyze it.

I do some debug. I write this data in two text
text1:
{"@timestamp": log1}{"@timestamp": log2}{"@timestamp": log3}{"@timestamp": log4}
text2:
{"@timestamp": log1}
{"@timestamp": log2}
{"@timestamp": log3}
{"@timestamp": log4}

and execute 
cat text1 |  sudo filebeat.sh -c /etc/filebeat/filebeat-wxq.yml
cat text2 |  sudo filebeat.sh -c /etc/filebeat/filebeat-wxq.yml

text2 work fine!
please help, how to fix it .

**Comment by zong400** [comment]
logback.xml: 
<appender name="stash" class="net.logstash.logback.appender.LogstashSocketAppender">
            <host>logstash-wxq</host>
            <port>5111</port>
        </appender>

filebeat-wxq.yml:
filebeat.prospectors:
- input_type: stdin 
  json.message_key:
  json.keys_under_root: true
  json.overwrite_keys: true

output.kafka:
  enabled: true 
  hosts: ["10.254.58.3:9092"]
  topic: weixiao-dev-wxq
  #use_type: false
  worker: 2
  keep_alive: 20s

we use socat to listen udp port
sudo socat  udp-listen:5111,reuseaddr,fork - | sudo filebeat.sh -c /etc/filebeat/filebeat-wxq.yml

**Comment by philsttr** [comment]
See [here](https://github.com/logstash/logstash-logback-encoder#prefix_suffix) for how to add a suffix.

More specifically,  try adding the following to you appender config:

```xml
    <suffix class="ch.qos.logback.classic.PatternLayout">
      <pattern>%n</pattern>
    </suffix>
```

**Comment by zong400** [comment]
@philsttr  It work,thank you!  
BTW  why '%n' not '/n'

**Comment by philsttr** [comment]
`%n` is the system newline separator. See logback's PatternLayout docs for more info.
