### ISSUE TITLE
Add MDC fields to access events

### ISSUE THREAD

**Issue by regevbr** [logstash/logstash-logback-encoder#213]
It would be awsome if MDC fields can be added to access events (if even possible)
see https://jira.qos.ch/browse/LOGBACK-1016

@ezraroi

**Comment by philsttr** [comment]
Will consider this if/when logback ever supports it.  Can't really do anything until then

**Comment by philsttr** [comment]
Closing.  Feel free to open a new issue if/when logback ever supports MDC in access events.
