### ISSUE TITLE
HOSTNAME as lowercase in the logging event

### ISSUE THREAD

**Issue by browndogg33** [logstash/logstash-logback-encoder#220]
I know this is part of the logback context, but is there a way to make the "HOSTNAME" key appear as "hostname" in the event?

**Comment by philsttr** [comment]
You can disable logging of [context fields](https://github.com/logstash/logstash-logback-encoder#context-fields), and then [add your own hostname field](https://github.com/logstash/logstash-logback-encoder#global-custom-fields)

```
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
    <includeContext>false</includeContext>
    <customFields>{"hostname":"${HOSTNAME}"}</customFields>
</encoder>
```

**Comment by browndogg33** [comment]
Worked great.  Thank you!

**Comment by mwisnicki** [comment]
Any way to do that without excluding all other context properties?
