### ISSUE TITLE
Chinese word change to unicode char in log file

### ISSUE THREAD

**Issue by looqy** [logstash/logstash-logback-encoder#222]
Hi~    
    I'm a chinese user,  chinese words change into unicode chars in log file.    
    Such as "请求方法" changes to be "\u8BF7\u6C42\u65B9\u6CD5".    
    I set charset=UTF-8 for logstashEncoder in logback.xml, but it is not working.    
    how can I solve this problem?    
    thx!

**Comment by philsttr** [comment]
Hi,

See [this answer](https://github.com/logstash/logstash-logback-encoder/issues/197#issuecomment-273382200)
