### ISSUE TITLE
logback appender thread failed to stop

### ISSUE THREAD

**Issue by looqy** [logstash/logstash-logback-encoder#225]
Hi~    
  When I redeploy my web-application with tomcat, it happens warning "The web application [ROOT] appears to have started a thread named [logback-appender-stash-192.168.201.14:5043-2] but has failed to stop it. This is very likely to create a memory leak".
  How can I accomplish this?    
  thx!

**Comment by philsttr** [comment]
You'll need to [stop the logback context](https://logback.qos.ch/manual/configuration.html#stopContext) when your web application stops.

**Comment by looqy** [comment]
thx!    
  I knew this solution, I have solved my problem with logback official suggestion.    
  And I want to know if we have some customized plans for this situation whin our project?

**Comment by philsttr** [comment]
The proper way of shutting down appenders is by shutting down logback as I mentioned.

logback-logstash-encoder is not going to implement any other way of shutting down.
