### ISSUE TITLE
Compute hash value from exception stacks as a JSON field

### ISSUE THREAD

**Issue by pismy** [logstash/logstash-logback-encoder#226]
Hi,

First of all, I'd like to thank you for this splendid project, I'm a big fan !

I'm using it a lot at Orange, and have developped some additional features that - I believe - are of pretty good interest.
See: https://github.com/Orange-OpenSource/orange-mathoms-logging

The most valuable one is probably the idea of generating a single hash from exception stacks.
Those hashes help matching several occurrences of the same error, as it is highly probable that two errors with the same hash will be - indeed - occurrences of the same error.

Once indexed by Elasticsearch, you can track your errors history, frequency, and build awesome dashboards...

I've just proposed contributing to Logback (see https://jira.qos.ch/browse/LOGBACK-1296) and don't know what will be the outcome, but it could also simply be a feature of logstash-logback-encoder as the full power of it is really related to Elasticsearch.

Let me know...

**Comment by philsttr** [comment]
Sure, should be relatively easy to extend [ShortenedThrowableConverter](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java) to do this

**Comment by pismy** [comment]
Actually I implemented both:

* [CustomThrowableConverterWithHash](https://github.com/Orange-OpenSource/orange-mathoms-logging/blob/master/src/main/java/com/orange/common/logging/logback/CustomThrowableConverterWithHash.java) renders the stack trace with inlines hashes
* [StackHashJsonProvider](https://github.com/Orange-OpenSource/orange-mathoms-logging/blob/master/src/main/java/com/orange/common/logging/logback/StackHashJsonProvider.java) generates a single JSON property

We use both in my projects, but the JSON property is the one that allows building stats, graphs and dashboards...

As I told you, I proposed this contribution to Logback, but I don't know how long it will take to have it accepted.

Do you want me to submit a PR to `logstash-logback-encoder` with those enhancements ?

**Comment by osigida** [comment]
@pismy I guess this functionality might be useful not only in terms of logback encoder,
but with the regular logging to a file as well.

**Comment by pismy** [comment]
Yes sure, that's why I proposed it to Logback (can be used with any appender)

**Comment by philsttr** [comment]
@pismy , sure!  that'd be great.
