### ISSUE TITLE
Update Jackson version to 2.8.9

### ISSUE THREAD

**Issue by msymons** [logstash/logstash-logback-encoder#230]
logstash-logback-encoder currently (v4.10) uses jackson-databind v2.8.8.  Update this by incrementing jackson.version to 2.8.9.

Addresses Jackson Deserializer security vulnerability:

FasterXML/jackson-databind#1599
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8.9

**Comment by philsttr** [comment]
PR #231 merged
