### ISSUE TITLE
How do specify the index to which the logs are to be written?

### ISSUE THREAD

**Issue by venkatasreekanth** [logstash/logstash-logback-encoder#233]
Logs by default appear in logstash index. I would like the logs for each service be in their own index.

**Comment by philsttr** [comment]
You would need to configure that in your [logstash configuration](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index), not in the logstash-logback-encoder config.

See [here](https://stackoverflow.com/questions/27146032/make-logstash-add-different-inputs-to-different-indices) for an example based on type.  You can also base it on other fields in the events.
