### ISSUE TITLE
[bug] useless method calls

### ISSUE THREAD

**Issue by waooog** [logstash/logstash-logback-encoder#237]
We find the following bug inside `logstash-logback-encoder`, the reason is the combined method calls to `Math.min` and `Math.max` always return a constant value. 

**Path**: `src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java`

**Bug location**: line 274

**Code**:
` public String convert(ILoggingEvent event) {
...
 StringBuilder builder = new StringBuilder(Math.min(BUFFER_INITIAL_CAPACITY, Math.max(Integer.MAX_VALUE, this.maxLength + 100)));
...
`

In the above code snippet, the return value of `Math.max` is always bigger than or equal to `Integer.MAX_VALUE`, so the return value of `Math.min` is always `BUFFER_INITIAL_CAPACITY`.

**Comment by philsttr** [comment]
Fixed for next release.  Thanks for the report!
