### ISSUE TITLE
Support for Conversion Rules

### ISSUE THREAD

**Issue by ppiastucki** [logstash/logstash-logback-encoder#238]
Hi,

Is logstash encoder supposed to handle logback conversion rules?
E.g.
```
<conversionRule conversionWord="message" converterClass="SomeMessageConverter" />
```
Such a rule works fine for both console and file appenders, however, I cannot make it work with logstash.
How can I achieve similar functionality with logstash encoder? I would like to modify the message and remove some sensitive data before it gets logged. I would be grateful for some help.

**Comment by philsttr** [comment]
I believe you can use conversion rules with the [Pattern JSON Provider](https://github.com/logstash/logstash-logback-encoder#pattern-json-provider)

**Comment by ppiastucki** [comment]
Yep. It works like a charm with the pattern provider. Thanks!
