### ISSUE TITLE
Cannot customize standard field names with LogstashTcpSockerAppender and LogstashEncoder

### ISSUE THREAD

**Issue by xiaoming1999** [logstash/logstash-logback-encoder#242]
I have the following configuration in my logback.xml:

    <appender name="LOGSTASH" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <includeContext>false</includeContext>
            <fieldNames>
                <timestamp>timestamp</timestamp>
                <version>[ignore]</version>
                <levelValue>[ignore]</levelValue>
            </fieldNames>
        </encoder>
    </appender>

Output:
{
    "level": "INFO",
    "message": "This is a raw json object logging example.",
    "version": "2.1",
    "@timestamp": "2017-07-31T23:22:12.368Z",
    "thread_name": "main",
    "@version": "1",
    "logger_name": "com.forescout.util.FSLogger",
    "timestamp": "2017-07-31T16:21:40.902-07:00",
  },

The old version filed name @version is not ignored and the old timestamp field name @timestamp still exists.

If I replace the LogstashTcpSocketAppender with ch.qos.logback.core.rolling.RollingFileAppender and output the log to a file, the output is expected and is shown as following:
{
    "level": "INFO",
    "message": "This is a raw json object logging example.",
    "version": "2.1",
    "thread_name": "main",
    "logger_name": "com.forescout.util.FSLogger",
    "timestamp": "2017-07-31T16:21:40.902-07:00",
  },

Why are the behaviors of the encoder different for different appenders?

**Comment by philsttr** [comment]
When I try your examples using either appender, I see the same output (with the renamed timestamp, and removed version and levelValue).

How are you retrieving the tcp output?  Is it with logstash?  Perhaps logstash is adding those fields. Can you try using a simple tcp server (e.g. `nc -l 1234`) so you can see the raw data that is received over tcp?

**Comment by xiaoming1999** [comment]
The log is sent to a logstash server. It turns out that logstash server will add @timestamp and @version if they does not exist in the log received over the tcp socket.
