### ISSUE TITLE
TCP - tag log for Logstash

### ISSUE THREAD

**Issue by visioncoder** [logstash/logstash-logback-encoder#245]
Hello,  

I am using logstash-logback-encoder **4.11** for Spring Boot **1.5.6.RELEASE**.  The logstash currently picks up "tagged" log files, which is handled by FileBeat. We are moving to TCP protocol, provided by logstash-logback-encoder. 

The relevant **logstash configuration** file looks like this: 
```
tcp {
        port => 9203
        type => "lower"
        tags => [ "someTag" ]
    }
```

Now below is my **appender defined in logback.xml**: 
```xml
    <appender name="stash"
        class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>LOGSTASH_SERVER_NAME:9203
        </destination>
        <encoder
            class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <timestamp />
                <version />
                <pattern>
                    {
                    "tags": ["mbc"],
                    "type:" "mbc-lower",
                    "logger":"%logger",
                    "level": "%level",
                    "thread":
                    "%thread",
                    "message": "%message"
                    }
                </pattern>
            </providers>
        </encoder>
        <writeBufferSize>2000</writeBufferSize>
    </appender>
```

When I run the application with log configuration in debug mode, it indicates that the TCP connection has been established with the server and prints out the log on the console. But there is no sight of the log anywhere in the Logstash server.  

```
09:25:32,380 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[stash] - Log destination LOGSTASH_SERVER_NAME:9203: connection established.
```

Additionally, spring.log file is generated in temp directory *without explicitly specifying in the logback) partial stack of which is below: 

```
2017-08-11 09:28:48.868 ERROR 1776 --- [DiscoveryClient-HeartbeatExecutor-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error
com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)

```

Can you please advise if this is an issue? 

Thanks!

**Comment by philsttr** [comment]
Have you hooked up your appender to any loggers in your logback.xml?

e.g.
```xml
  <root level="debug">
    <appender-ref ref="stash" />
  </root>
```

or 

```xml
  <logger name="com.foo.bar" level="debug">
    <appender-ref ref="stash" />
  </logger>
```


For debugging, you can also try replacing logstash with a simple netcat listener, so you can see the raw data that is received.  For example, to start up a tcp listener that outputs everything it receives to the console, just run `nc -lp 9203`
