### ISSUE TITLE
Java Configuration - add new fields not in LogstashFieldNames

### ISSUE THREAD

**Issue by visioncoder** [logstash/logstash-logback-encoder#247]
Hello, 

I am using logstash-logback-encoder version _4.11_ in Spring Boot _1.5.2.RELEASE_ application. 

Logback configuration is done programatically,  relevant snippet for encoder and tcpAppender is below for reference: 

```
protected LogstashTcpSocketAppender configureTcpSocketAppender(LoggerContext loggerContext, Logger rootLogger) {
        LogstashTcpSocketAppender logstashTcpSocketAppender = new LogstashTcpSocketAppender();
        logstashTcpSocketAppender.setName(TCP_APPENDER_NAME);
        logstashTcpSocketAppender.setContext(loggerContext);
        logstashTcpSocketAppender.addDestination(TCP_DESTINATION);
        logstashTcpSocketAppender.setEncoder(logstashEncoder(loggerContext, rootLogger));
        logstashTcpSocketAppender.start();
        return logstashTcpSocketAppender;
    }
```

   ```
 protected LogstashEncoder logstashEncoder(LoggerContext loggerContext, Logger rootLogger) {

        LogstashEncoder encoder = new LogstashEncoder();
        encoder.setContext(loggerContext);
        encoder.setIncludeContext(true);
        encoder.setCustomFields("host, mbosDev, datacenter"); //ADD FIELDS - DID NOT WORK!
        encoder.start();
        return encoder;
    }

```

As an alternative, I tried to extend _LogstashFieldNames_ and then add properties there before injecting it into the Encoder. However, this did not work either. 

```
 class CloudFieldNames extends LogstashFieldNames {

        private String host = "SomeHost";
        private String env = "SomeEnv";
        private String datacenter = "SomeDatacenter";

        public CloudFieldNames() {
            super();
        }
//Getters, setters and so on
}
```

I am trying to add fields at the logger level (not within message itself). Idea is to inject additional fields at "top level" so that they show up at the same level as where we see "**host**" in the screenshot below: grabbed after exporting the log to Kibana: 

![image](https://user-images.githubusercontent.com/20347500/29637564-7ed496e6-8822-11e7-808b-17162d056035.png)

Is there a way for me to do this? I have taken a look at one of the open issues [#168 ](https://github.com/logstash/logstash-logback-encoder/issues/168) - that does indicate utilizing _customFields_ which I've tried to do above. 

Other than this, rest of the configuration is working quite well. Can someone please take a look and suggest? 

Thanks!

**Comment by philsttr** [comment]
The `customFields` string needs to be a valid JSON object string.

For example:

```java
encoder.setCustomFields("{\"host\":\"myhostname\"}");
```

Those custom fields will be "merged" into the root level json object.

**Comment by visioncoder** [comment]
Hi @philsttr, thank you for your prompt response and direction.

Yes, the suggested approach did work, and I am now able to see the additional fields in the root-level JSON object ("message" field): 
![image](https://user-images.githubusercontent.com/20347500/29664242-d266645e-889c-11e7-9f87-0496248edb3b.png)

However, I wanted to know if I can add the field at the level where "host" attribute exists: 
![image](https://user-images.githubusercontent.com/20347500/29664205-ade9434e-889c-11e7-9a30-046a90c512d6.png)

In the screenshot above, host value is coming from the TCP-ed log via logstash-encoder, and the others, (like datacenter environment etc.) are populated in Logstash config file. 
Intent is to move these outside of Logstash configuration and into the application logback config (if there is a way to accomplish this).

**Comment by philsttr** [comment]
Ah, so what is happening is that logstash (on the receiving end) is not interpreting the output from the logtash-logback-encoder as JSON.  logstash is just treating it as a simple string.  This is evident for two reasons:

1. logstash includes the entire JSON string as a `message` field, as opposed to just the `message` field from the JSON event
2. logstash isn't interpreting the timestamp of the JSON event (`2017-08-24T11:10:30.256+00:00`).  Instead, logstash is creating its own timestamp a few milliseconds later  (`07:10:30:*309*`

The solution to this problem is to configure logstash's input to use the `json_lines` codec like this:

```
input {
    tcp {
        port => 4560
        codec => json_lines
    }
}
```

**Comment by visioncoder** [comment]
Perfect! Thanks a million, @philsttr!

**Comment by mpanchap** [comment]
@philsttr   I couldn't find the custom fields in my kibana Discover logs.

Below is my logstash conf and  logback.xml configuration

`input {
	tcp {
		type => "logs"
		codec => "json_lines"
		port => 4560
	}
}`

`<appender name="LOGSTASH_HOST"
				class="net.logstash.logback.appender.LogstashTcpSocketAppender">
				<destination>${LOGSTASH_HOST}</destination>
				<port>4560</port>
				<encoder class="net.logstash.logback.encoder.LogstashEncoder">
					<provider
						class="net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider" />
					<includeCallerData>true</includeCallerData>
					<customFields>{"appname":"myWebservice","roles":["customerorder","auth"],"buildinfo":{"version":"Version
						0.1.0-SNAPSHOT","lastcommit":"75473700d5befa953c45f630c6d9105413c16fe1"}}
					</customFields>
				</encoder>
			</appender>`
