### ISSUE TITLE
JSON encoder FORMAT ( Single line per log )

### ISSUE THREAD

**Issue by giovannyreyeso** [logstash/logstash-logback-encoder#249]
Hi, it's possible make log per line? the actual format is:

{ 
 "prop": "value",
"prop": "value"
}
I would like to change it to :

{"prop:"value","prop":"value"}
{"prop:"value","prop":"value"}

**Comment by philsttr** [comment]
By default, logstash-logback-encoder will write on log per line. Something must be "pretty printing" the json event after it it output by logstash-logback-encoder.

**Comment by giovannyreyeso** [comment]
Nice, i will check this now, Thanks!
