### ISSUE TITLE
how can asJson not return null if message is not json

### ISSUE THREAD

**Issue by dragontree101** [logstash/logstash-logback-encoder#251]
i have log message, if message is json i want to use asJson to json str and if message not json, i want to display normal message instead of null

**Comment by philsttr** [comment]
I don't think that is possible at the moment.

Pull Requests are welcome

**Comment by java-my-life** [comment]
I also need the same function !
:+1:

**Comment by philsttr** [comment]
Added `#tryJson` converter in 5.0
