### ISSUE TITLE
API report

### ISSUE THREAD

**Issue by lvc** [logstash/logstash-logback-encoder#255]
Hi,

I'd like to share report on API changes and backward compatibility for the Logstash Logback Encoder library: https://abi-laboratory.pro/java/tracker/timeline/logstash-logback-encoder/

BC — binary compatibility
SC — source compatibility

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/japi-tracker tool.

Hope it will be helpful for users and maintainers of the library.

Thank you.

![logstash-logback-encoder-1](https://user-images.githubusercontent.com/1517837/32407301-1ad80970-c198-11e7-91a4-e81b422780f7.png)

![logstash-logback-encoder-2](https://user-images.githubusercontent.com/1517837/32407300-1ab4791a-c198-11e7-9910-922556e3f940.png)

**Comment by philsttr** [comment]
Cool. Thanks
