### ISSUE TITLE
Date format customization not working

### ISSUE THREAD

**Issue by kringol** [logstash/logstash-logback-encoder#258]
I've been trying to change the date format of the timestamp field on json output following the example of the custom JsonGenerator
https://github.com/logstash/logstash-logback-encoder#customizing-json-factory-and-generator

I see the generator being instantiated properly and set, but it's being ignored, and I see the timestamp being serialized by "net.logstash.logback.composite.FormattedTimestampJsonProvider" which has a predefined pattern but no way to set it from the config.

Am i missing something on how to customize the timestamp format?
Is there any easy workaround?

**Comment by kringol** [comment]
I believe I can customize it alternatively by using a LoggingEventCompositeJsonEncoder and doing it on the provider directly or adding my own provider.
Am i correct?
Will try that next week

**Comment by philsttr** [comment]
Hey @kringol ,

Currently, as you mentioned, you'll need to use `LoggingEventCompositeJsonEncoder` with a `LoggingEventFormattedTimestampJsonProvider` if you want to customize the timestamp pattern.

For the next release, I've added a new `timestampPattern` property of `LogstashEncoder` that can be used to set the pattern without having to use `LoggingEventCompositeJsonEncoder` directly.
