### ISSUE TITLE
globalCustomFields provider is not documented for composite encoder

### ISSUE THREAD

**Issue by cykl** [logstash/logstash-logback-encoder#262]
README  extensively documents every provider supported by `LoggingEventCompositeJsonEncoder`. However, there is no mention of `globalCustomFields`. Is it intentional or an omission ? 

If anybody faces the same issue until README gets updated, following conf worked for me:

```xml
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <timestamp/>
                <globalCustomFields>
                    <customFields>{"appname":"myWebservice"}</customFields>
                </globalCustomFields>
            </providers>
        </encoder>
```

**Comment by philsttr** [comment]
It was intentional.

It was intended that the `pattern` provider would be used to add global fields when using the composite encoder.

e.g.

```xml
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <timestamp/>
                <pattern>
                    <pattern>{"appname":"myWebservice"}</pattern>
                </pattern>
            </providers>
        </encoder>
```

Probably worth mentioning that somewhere in the doc though.

**Comment by cykl** [comment]
Damn, it is even documented by the _"myCustomField": "fieldValue"_ example! It seems obvious when you know it but dunno why I haven't figured it out from the doc which contains all the necessary information.

Thanks !

**Comment by philsttr** [comment]
Ignore that commit, mentioned wrong issue number.  Should have been 261
