### ISSUE TITLE
Logstash encoder has \n \t issues

### ISSUE THREAD

**Issue by SawyerFord** [logstash/logstash-logback-encoder#263]
I have configured the required logstash encoder inside pom.xml and logback.xml. The logs are in JSON format but I get the logs with newline and space charecters \n\t inside the stacktrace. The message attribute also has  full of  backslash charecters. Could you please let me know how to handle these special charecters.

**Comment by philsttr** [comment]
Hi @SawyerFord 

The JSON format does not allow line breaks within string values.  Since the stacktrace and message field values are string values, newlines will be escaped within them.
