### ISSUE TITLE
MDC fields lost to log when logging exception

### ISSUE THREAD

**Issue by bailaohe** [logstash/logstash-logback-encoder#267]
Hello, I want to logging a request id in MDC when a un-expectable exception occurs in my spring boot application. My logback config is as follows:

```
<appender name="ERROR" 
 class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>ERROR</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>
        <destination>${LOGHUB_AGENT}:55${APP_ID}4</destination>
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <mdc/>
                <context/>
                <version/>
                <logLevel/>
                <loggerName/>
                <pattern>
                    <pattern>
                        {
                        "appName": "${APP_NAME}",
                        "appVersion": "${APP_VERSION}"
                        }
                    </pattern>
                </pattern>
                <threadName/>
                <message/>
                <logstashMarkers/>
                <arguments/>
                <stackTrace/>
            </providers>
        </encoder>
    </appender>
```

I put requestId in MDC in my request filter before processing any incoming HttpServletRequest:

`MDC.put("requestId", String.valueOf(requestId));`

But in final logstash output I cannot find requestId logged.

**Comment by philsttr** [comment]
Hi @bailaohe, your configuration looks correct to me.

Can you perhaps provide a sample application and/or unit test that exposes the problem?

If not, here are some steps to debug the problem....

First, put a breakpoint [here](https://github.com/qos-ch/logback/blob/dcfd52325f9bf0f17bea98a35b5b76b40bbfcc2f/logback-classic/src/main/java/ch/qos/logback/classic/spi/LoggingEvent.java#L209) and step into `getMDCPropertyMap()` to ensure that the MDC contains the value you put into it.  If it does not, then something is either clearing the value out of the MDC prior to your log event, or your log event is occurring on a different thread than the one that put the value into the MDC.

Then put a breakpoint [here](https://github.com/logstash/logstash-logback-encoder/blob/01a49aa0a087ae08e4550f4542810d51a6974c5f/src/main/java/net/logstash/logback/composite/loggingevent/MdcJsonProvider.java#L81), and make sure the value is still there.
