### ISSUE TITLE
Unable to change Timezone with ConsoleAppender

### ISSUE THREAD

**Issue by aw1212** [logstash/logstash-logback-encoder#270]
My dependencies:

```
         <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-access</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>4.7</version>
        </dependency>
```

My logback.xml:
```
   <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <timeZone>UTC</timeZone>
        </encoder>
         ....
```

Error:

> Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Could not create component [encoder] of type [net.logstash.logback.encoder.LogstashEncoder] java.lang.ClassNotFoundException: net.logstash.logback.encoder.LogstashEncoder
ERROR in ch.qos.logback.core.joran.spi.Interpreter@8:23 - no applicable action for [timeZone], current ElementPath  is [[configuration][appender][encoder][timeZone]]

Any help is greatly appreciated

**Comment by philsttr** [comment]
What happens when you remove the `timeZone` element?

The reason I ask, is because I don't think this error has anything to do with the `timeZone` element.  The `ClassNotFoundException: net.logstash.logback.encoder.LogstashEncoder` error indicates that your application cannot find the `LogstashEncoder` class.

You would need to ensure that the classpath that is loading your logback configuration includes the logstash-logback-encoder jar.

**Comment by aw1212** [comment]
I believe it may have been a dependency clash on the classpath. I removed the logback-classic dependency and it seems to start up without error however the timezone does not seem to be working. I have been able to make it work by adding the timezone to my date pattern: %d{yyyy-MM-dd'T'HH:mm:ss.SSS,UTC}
