### ISSUE TITLE
includeCallerData Field 

### ISSUE THREAD

**Issue by cashok08** [logstash/logstash-logback-encoder#272]
Given a scenerio , where I have two spring boot micro services . Service A calls Service B , both services are equipped with logstash-logback . Now if includeCallerData is enabled in logback-spring.xml 
how it behaves while logging incomplete request from Service A in Service B

**Comment by philsttr** [comment]
The `includeCallerData` option only refers to the class that calls the logger method.  It does not have any concept of multiple applications.

For example, if you have:

```java
public class MyClass {
    private static final Logger logger = LoggerFactory.getLogger(MyClass .class);

    public static void main(String[] args) {
        logger.info("foo");
    }
}
```

Then the caller data would be `caller_class_name=MyClass`, `caller_method_name=main`, etc.
