### ISSUE TITLE
GlobalCustomFieldsJsonProvider.start() is called once and to late (after `setJsonFactory`) when used _nested_

### ISSUE THREAD

**Issue by ratemyduck** [logstash/logstash-logback-encoder#276]
EDIT: I thought this had to do with the logback version. It doesn't; it got to do with nesting json (using `LoggingEventCompositeJsonEncoder`)

If `GlobalCustomFieldsJsonProvider` is used inside a `nestedField` the JsonFactory is not set when the start method is run the first time causing this code to skip
```
    private void initializeCustomFields() {
        if (this.customFields != null && jsonFactory != null) {
            try {
                this.customFieldsNode = this.jsonFactory
                    .createParser(customFields).readValueAsTree();
            } catch (IOException e) {
                addError("Failed to parse custom fields [" + customFields + "]", e);
            }
        }
    }
```
When using it non-nested the start method runs twice, one before `setJsonFactory` has been run, one after it been run.

**Comment by philsttr** [comment]
Thanks for the report.

If you need a workaround before this is fixed, you can try using the [`pattern` json provider](https://github.com/logstash/logstash-logback-encoder#pattern-json-provider) to get the same functionality.

**Comment by philsttr** [comment]
Fixed for 5.1

**Comment by jeacott1** [comment]
I'm using 6.2 and this is still a problem!

**Comment by philsttr** [comment]
Hi @jeacott1 , I believe you are actually running into #168 , which is caused by [LOGBACK-1101](http://jira.qos.ch/browse/LOGBACK-1101)
