### ISSUE TITLE
How to escape or replace special characters in the log message 

### ISSUE THREAD

**Issue by kovisrividya** [logstash/logstash-logback-encoder#281]
When logs are viewed in Kibana \n, \r are executed and message has come in new line instead if we want it to be displayed as literal \n how can we do that?

is there any property for encoder so that these special characters like \n,\r,\t e.t.c. viewed as \n instead of text in new line?

and do we need to take care of any extra caution to deal with log forging(script attack XSS, html code any thing) when using logstash-logback-encoder? 

Thank you!
Regards,
srividya

**Comment by philsttr** [comment]
Hi @kovisrividya ,

I'm not an expert in Kibana, so I can't comment on if Kibana can be configured to not interpret the escaped newline characters (`\n`) that appear in the JSON events output by logstash-logback-encoder.

You could potentially use the solution mentioned in #83 to change the characters that jackson uses to escape newline characters within json strings.  Or you can wait for the solution to #279 

Jackson will properly handle escaping strings within the JSON event being output, to ensure that it is valid JSON.  However, logstash-logback-encoder does offer your code the ability to append raw strings to the JSON event via [`StructuredArguments.raw`](https://github.com/logstash/logstash-logback-encoder/blob/bd5c74331aee7816bf0f3e667d7937e2a0ea22d5/src/main/java/net/logstash/logback/argument/StructuredArguments.java#L168-L184) and [`Markers.appendRaw`](https://github.com/logstash/logstash-logback-encoder/blob/bd5c74331aee7816bf0f3e667d7937e2a0ea22d5/src/main/java/net/logstash/logback/marker/Markers.java#L69-L74).  These raw strings are not escaped by jackson, so it would be your responsibility to ensure that the raw strings are in proper json format before appending them.

I cannot comment on anything downstream that is reading your logs.  For example, if something downstream interprets part of your logs as html, logstash-logback-encoder has no control over that.
