### ISSUE TITLE
requested_url format

### ISSUE THREAD

**Issue by jeacott1** [logstash/logstash-logback-encoder#292]
hi All,
 I'm wondering what format I should expect from the requested_url field?
is it intended to be the equivalent of nginx 'request' field? - [GET /some/path HTTP/1.1] 
or java requestUrl?
"[http://127.0.0.1: 8888/some/path]"

I'm guessing the first but cant find anything definitive.

**Comment by philsttr** [comment]
The request url value comes from logback access' `IAccessEvent` implementation, which you can see [here](https://github.com/qos-ch/logback/blob/4dd08e68321548cd85251ec389f5a832505e1268/logback-access/src/main/java/ch/qos/logback/access/spi/AccessEvent.java#L197-L204).

Logback documents the requestUrl as the first line of the HTTP request, which would look like `GET /some/path HTTP/1.1`
