### ISSUE TITLE
net.logstash.logback.encoder.LogstashAccessEncoder content length -1 when header missing

### ISSUE THREAD

**Issue by MrGarry2016** [logstash/logstash-logback-encoder#296]
I am using net.logstash.logback.encoder.LogstashAccessEncoder
content length is set to -1 for response w/o Content-Length header
traditional tomcat access log does not have this issue, the following will produce correct content length using %b even if Content-Length header is missing
```<Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs" pattern="%h %l %u %t "%r" %s %b" prefix="localhost_access_log." suffix=".txt">```

**Comment by philsttr** [comment]
logstash-logback-encoder's [`ContentLengthJsonProvider`](https://github.com/logstash/logstash-logback-encoder/blob/2bf96d3d17aaa30fa8b266fb6d8b0e136bde5606/src/main/java/net/logstash/logback/composite/accessevent/ContentLengthJsonProvider.java#L36) just pulls the contentLength from logstash's [`AccessEvent.getContentLength()`](https://github.com/qos-ch/logback/blob/4dd08e68321548cd85251ec389f5a832505e1268/logback-access/src/main/java/ch/qos/logback/access/spi/AccessEvent.java#L456-L464) method.  

logstash-logback-encoder doesn't have direct access to tomcat, or examining headers, or body content, so there is no way to fix this in logstash-logback-encoder.  I'd recommend filing this upstream with logback.
