### ISSUE TITLE
logback json encoder split large messages

### ISSUE THREAD

**Issue by abedwardsw** [logstash/logstash-logback-encoder#297]
I am using a setup similar to https://developers.redhat.com/blog/2018/01/22/openshift-structured-application-logs/ to send my log messages to fleuntd/elasticsearch within openshift.   However a problem has arose that if the log message is larger than 16k docker splits the log message into 2.    This is all fine and dandy, however we end up losing the MDC context data on subsequent messages, this results in the inability for me to search for my log messages based on these fields.

Unfortunately it seems that we are at a standstill where neither the fluentd side or docker side are willing to budget on a solution.   I even have support for Kubernetes with RedHat but they have proved to be unwilling to put in the proper fix (merge the records back together in fluentd/elasticsearch).

Here is a link to the "bug" on the openshift side.  https://github.com/kubernetes/kubernetes/issues/52444

I looked through the logstash code and did not see any way to confirm the maximum buffer size similar to the TCP apender.     I think it would be good to have a configurable maximum message size for the encoders at which point the encoder would spit out multiple lines, all ensuring to comply with the format (having the mdc tags).   If you agree with this change, could you provide some high level details on where it should be implemented.  I'll see if I can find some time to do the fix myself.   If you don't agree or have a better idea, please let me know.  thanks

**Comment by philsttr** [comment]
How do you propose to split a JSON object based on encoded size?

For example, how would the following JSON object be split?

```
{
  "@timestamp" : "2018-06-28T13:30:52.164-07:00",
  "@version" : "1",
  "logger_name" : "com.foobar.Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "message" : "A 16k log message",
  "mdckey" : "a 16k mdc value",
  "object" : {
     ... a huge object graph that serializes out to 16k ...
  }
}
```

**Comment by abedwardsw** [comment]
I guess I am not familiar enough with the encoder, I was only considering the "message" field and was assuming something like the following:

current:
```
{
  "@timestamp" : "2018-06-28T13:30:52.164-07:00",
  "@version" : "1",
  "logger_name" : "com.foobar.Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "message" : "A 16k log message",
}
```

proposed:
```
{
  "@timestamp" : "2018-06-28T13:30:52.164-07:00",
  "@version" : "1",
  "logger_name" : "com.foobar.Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "message" : "up to first 10k of message (configurable) - thus allowing extra 6k for other mdc fields/keys/objects",
}
{
  "@timestamp" : "2018-06-28T13:30:52.164-07:00",
  "@version" : "1",
  "logger_name" : "com.foobar.Main",
  "thread_name" : "main",
  "level" : "DEBUG",
  "level_value" : 10000,
  "message" : "additional messages repeated for every 10k",
}
```

in my use case I am not using large objects or mdc values so I think the solution would work for me.  But agree with your comment, I am not sure if I have a good proposal for messages that have large mdc values or objects.

Do you have any suggestions of something that might work?   or potentially would just having the message key split be good enough solution for this particular use case?

**Comment by abedwardsw** [comment]
thanks a lot for providing a detailed response!  I will close this issue and attempt your solution.  I'll look to contribute back to logback once complete.

**Comment by dsbecker** [comment]
I realize this is a closed issue and I'm about to make this a zombie thread. I was attempting to implement this myself and an hung up on how to effectively clone the LoggingEvent. Many of the fields for are private and have no getters or setters. Any thoughts on how to go about that?

**Comment by dsbecker** [comment]
Nevermind, I solved it. I went with a new delegating event wrapper. Worked great.

**Comment by 84drizzt** [comment]
Hi @dsbecker, would you please share how the "delegating event wrapper" is written? we got the same needs. Thank you

**Comment by dsbecker** [comment]
Here you go:  https://gist.github.com/dsbecker/77700dd5167265ff793de2b0d1365c5a

This appender uses nested appenders, so simply your existing appender definition with this one, like so:
`    <appender name="STDOUT" class="com.employers.inc.das.util.LogChunkAppender">
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
        </appender>
    </appender>`

**Comment by anshuld95** [comment]
We also had similar needs where we wanted to split long logs so they don't get truncated by third party logging solutions. 

To address this, we created the following project: https://github.com/Latch/logback-length-splitting-appender

With this you can set up Logback to split on a custom length and add a sequence number to the logs with the following:

    <appender name="SPLITTER" class="com.latch.LengthSplittingAppender">
        <appender-ref ref="STDOUT"/> 
        <maxLength>5</maxLength>
        <sequenceKey>seq</sequenceKey>
    </appender>

@dsbecker similar to the cloning issue you encountered, we ended up creating a helper method to clone the original logging event to get all the attributes.

Feel free to check it out and contribute!

**Comment by chrisN777** [comment]
I ran into this dead thread and played around with the solutions provided above without success. For me the problem was the size of stacktraces and _not_ a long log message. I found that truncating the stacktraces was the better solution and configured easily:
https://github.com/logstash/logstash-logback-encoder#customizing-stack-traces
