### ISSUE TITLE
Log message limit max length

### ISSUE THREAD

**Issue by anjia0532** [logstash/logstash-logback-encoder#298]
Hi, I Known the [`ShortenedThrowableConverter`](https://github.com/logstash/logstash-logback-encoder#customizing-stack-traces) support `maxLength` and `maxDepthPerThrowable` but `message` was not.

In my work,sometimes see huge log messages and i want to truncated (spec sufix e.g. `...`), how easily to do this?

1. custom pattern ? ref https://stackoverflow.com/questions/35710008/limit-message-size-in-logback#answer-35733805
2. custom convert ? ref https://stackoverflow.com/questions/32704470/can-a-logback-message-field-be-truncated-trimmed-to-n-characters#answer-37744555

**Comment by philsttr** [comment]
You can truncate the message field by using [pattern](https://github.com/logstash/logstash-logback-encoder#pattern-json-provider) provider, and specifying a limit via logback's [format modifiers](https://logback.qos.ch/manual/layouts.html#formatModifiers)

For example, if you're using `LogstashEncoder`:

```
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
    <!-- Turn off the default message provider. -->
    <fieldNames>
        <message>[ignore]</message>
    </fieldNames>
    <!-- Outputs the message field, while truncating long messages. -->
    <provider class="net.logstash.logback.composite.loggingevent.LoggingEventPatternJsonProvider">
        <pattern>{"message":"%.-1000message"}</pattern>
    </provider>
</encoder>
```

**Comment by anjia0532** [comment]
ping @philsttr , ok ,  thanks for your reply 👍

**Comment by mmuruev** [comment]
I'm also have this issue. First its  a bit frustrating why so trivial and I believe very common thing require so many unobvious xml magic.  and second which place it correct for this encoder? Because for me its never work.

**Comment by anton-tkachenko** [comment]
My solution was this:

```
import ch.qos.logback.classic.pattern.ExtendedThrowableProxyConverter;
import ch.qos.logback.classic.spi.IThrowableProxy;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Delegate;

@RequiredArgsConstructor
public class LimitedMessageThrowableProxyConverter extends ExtendedThrowableProxyConverter {

    private final int limit;

    @Override
    protected String throwableProxyToString(IThrowableProxy proxy) {
        return super.throwableProxyToString(
                new DelegatingLimitedIThrowableProxy(proxy, limit)
        );
    }

    @RequiredArgsConstructor
    private static class DelegatingLimitedIThrowableProxy implements IThrowableProxy {

        @Delegate
        private final IThrowableProxy delegate;
        private final int limit;

        @Override
        public String getMessage() {
            return delegate.getMessage().length() > limit
                    ? delegate.getMessage().substring(0, limit) + "[ truncated ]..."
                    : delegate.getMessage();
        }

    }
}
```
