### ISSUE TITLE
SleepingWaitStrategy can take up to 90% of a core

### ISSUE THREAD

**Issue by wsargent** [logstash/logstash-logback-encoder#299]
In the async section, https://github.com/logstash/logstash-logback-encoder#async-appenders there is this advice:

> By default, the BlockingWaitStrategy is used by the worker thread spawned by this appender. The BlockingWaitStrategy minimizes CPU utilization, but results in slower latency and throughput. If you need faster latency and throughput (at the expense of higher CPU utilization), consider a different wait strategy offered by the disruptor, such as SleepingWaitStrategy.

This doesn't really describe the "higher CPU utilization" though.  In some kubernetes containers, CPU utilization was described as "90% at rest."  Something indicating "potentially MUCH higher" CPU utilization may work better here.

**Comment by raffaeleragni** [comment]
Anything that can solve this issue so far? I got containers spiking to 100% cpu while doing nothing. Took even a while to figure out that in fact the thread doing it was the logstash appender.

It should have to do with how the disruptor library handles a parkNanos(1) in the sleep strategy. Which in my opinion is crazy low amount of wait, especially for Java. I would normally think in such time spans only when I deal with native code in micro controllers or electronics imho.

I would even override the disruptor version myself on my pom for using the new one -apparently they changed that value now-, but this project is shading all of it, so not possible.
