### ISSUE TITLE
LogstashTcpSocketAppender sends duplicate logs

### ISSUE THREAD

**Issue by prathamesh13** [logstash/logstash-logback-encoder#301]
I am using `LogstashTcpSocketAppender` in my application to send logs to a logstash host. It appears that the appender/logger is producing duplicate logs for each logging event. Each log message seemed to be sent twice to logstash 

Following is my configuration:

_Logback.xml_

```
<configuration>
    <appender name="stash"
        class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>localhost:5044</destination>
    <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
    </appender>
    <root level="INFO">
        <appender-ref ref="stash" />
    </root>
	
    <shutdownHook class="ch.qos.logback.core.hook.DelayingShutdownHook" />
</configuration>

```
Does this have anything to do with additivity flag that can be set within logback configuration? How can we avoid duplicate logs while using `LogstashTcpSocketAppender`

**Comment by philsttr** [comment]
Hi @prathamesh13 

When I run an application with your exact `logback.xml`, duplicate logs are not received on `localhost:5044`.

Are you using the exact `logback.xml` that you provided?  Or do you have additional loggers/appenders/etc configured in your `logback.xml`.

Are you using the [additivity](https://logback.qos.ch/manual/configuration.html#overrridingCumulativity) flag anywhere in your configuration?

Are you running logstash on `localhost:5044`?  Can you try just running netcat locally (`nc -lk 5044`) to look at the raw data received to see if duplicate log events are received?

**Comment by prathamesh13** [comment]
Hi @philsttr ,

I tried again, and couldn't reproduce this issue. I am not sure what was causing the duplicate logs when i reported it.
