### ISSUE TITLE
Request Header IllegalStateException

### ISSUE THREAD

**Issue by bkookoopuffs** [logstash/logstash-logback-encoder#302]
Currently, my logging has been working correctly. However, when I add the request header to enable logging of all request headers, I receive a illegal state exception error. I've searched online and can't seem to find much information. I've read through the documentation multiple times but cannot find a solution.

Specifically, this part of code is what results in the error: 
```
<encoder class="net.logstash.logback.encoder.LogstashAccessEncoder">
  <fieldNames>
    <requestHeaders>request_headers</requestHeaders>
  </fieldNames>
</encoder>
```

Here is my config file: 

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">

    <include resource="org/springframework/boot/logging/logback/defaults.xml" />

    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />

    <property name="LOG_FILE" value="${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}}/spring.log}"/>

    <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
    	    <customFields>{"app_name":"${APP_NAME:-N/A}","app_version":"${APP_VERSION:-N/A}","hostname":"${HOST:-N/A}","environment":"${environment:-${ENVIRONMENT:-N/A}}"}</customFields>
            <includeContext>false</includeContext>
            <timeZone>UTC</timeZone>
	   </encoder>

      <encoder class="net.logstash.logback.encoder.LogstashAccessEncoder">
        <fieldNames>
            <requestHeaders>request_headers</requestHeaders>
        </fieldNames>
      </encoder>

        <file>${LOG_FILE}</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <fileNamePattern>${LOG_FILE_ROTATION:-${LOG_FILE}%d{yyyy-MM-dd}.%i}</fileNamePattern>
            <maxHistory>${LOG_FILE_ROTATION_MAX_HISTORY:-1}</maxHistory>
            <totalSizeCap>${LOG_FILE_ROTATION_TOTAL_SIZE_CAP:-3GB}</totalSizeCap>
            <maxFileSize>${LOG_FILE_ROTATION_MAX_FILE_SIZE:-1GB}</maxFileSize>
        </rollingPolicy>
    </appender>

    <root level="${LOG_LEVEL:-INFO}">
        <appender-ref ref="CONSOLE" />
        <appender-ref ref="FILE" />
    </root>

</configuration>
```

Error: 
`java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@19:29 - no applicable action for [requestHeaders], current ElementPath  is [[configuration][appender][encoder][fieldNames][requestHeaders]]
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:166)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:67)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:114)
`

**Comment by philsttr** [comment]
What version of logstash-logback-encoder are you using?

**Comment by philsttr** [comment]
Also, it looks like you're trying to configure two encoders for one appender.  This won't work.

LogstashAccessEncoder only works for access events from [logback-access](https://logback.qos.ch/access.html) and would go in `logback-access.xml`

**Comment by bkookoopuffs** [comment]
@philsttr 

My apologies on the late reply. I was using the wrong version of logback. I have also looked into logback-access and realized that it is different and needs its own xml. Thank you very much for your help.
