### ISSUE TITLE
how to read runtime property? ex, port

### ISSUE THREAD

**Issue by yuanxuzhang** [logstash/logstash-logback-encoder#309]
I want to send port info to logstash, how can i do it?

**Comment by philsttr** [comment]
See the [Custom Fields](https://github.com/logstash/logstash-logback-encoder#custom-fields) section of the readme for information about how to add fields to the JSON output for a log event.

**Comment by yuanxuzhang** [comment]
![port](https://user-images.githubusercontent.com/20080272/48384876-37296280-e727-11e8-8882-26c858f8b765.png)
the port in the above, is not my Mservice port; can I overidde it ?
