### ISSUE TITLE
Connected but not sending data?

### ISSUE THREAD

**Issue by kr428** [logstash/logstash-logback-encoder#313]
Folks; unsure where to post this, hope it's not completely O/T here: We're in the midst of moving our ElasticStack setup to new infrastructure. In our current environment, LogstashTcpDocketAppender works as desired. In the new environment, it doesn't. Plain and simple, and it feels a bit stupid. Where are we?

- Logstash and the whole Elastic stack seems to work.
- telnet <host> 4560 works.
- Posting messages there works, too, the messages will appear both in the logstash log file, in the logstash-* index.
- The application using LogstashTcpSocketAppender *says* in the logfile: connected to the remote host.
- However, *no* log output from the Java application ever makes it to the index or even to logstash itself (at least I don't see anything like this in the logstash log file).

This is a bit strange. We're in the process of upgrading from logstash 2.3.4 to 6.5.something. Could this cause the problem? How to debug what's happening here?
TIA,
Kristian

**Comment by philsttr** [comment]
Hey Kristian,

For debugging, there are few things that usually help...

1. Add a [logback status listener](https://logback.qos.ch/manual/configuration.html#automaticStatusPrinting).
   * E.g. `<statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener" />`, and watch for messages on the console
2. Start a simple netcat server somewhere (`nc -lk 4560`), and point the `LogstashTcpSocketAppender`  to that destination to see the raw data of what `LogstashTcpSocketAppender` is sending.
   * This should tell you whether logstash-logback-encoder is behaving the way you want
3. Try manually sending that same stream of data to logstash either with netcat or telnet
   * This should tell you whether logstash is behaving the way you want

Other than that, you could hook up a debugger to logstash-logback-encoder, and watch for what is going on inside (particularly [here](https://github.com/logstash/logstash-logback-encoder/blob/0f9956f0e8c259d013b68292eebf424ec8d1bf92/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L454))

As for debugging _logstash_, you'd have to direct that question over to the logstash community after you've done the above.

**Comment by kr428** [comment]
Hey; thanks a bunch for your help. Status listener actually did the trick: I figured out the project uses DropWizard and had logging configurations both in the DropWizard setup and in a dedicated logback.xml (which was what I tried to modify but which the logger initialized but apparently didn't use). Fixing this fixed my logstash connection "trouble" too. Thanks again! :)
