### ISSUE TITLE
Allow Jackson ObjectMapper to scan for available modules on the classpath

### ISSUE THREAD

**Issue by sdavids13** [logstash/logstash-logback-encoder#315]
We are having the same problem defined here: https://github.com/logstash/logstash-logback-encoder/issues/209

You can safely scan for modules on the classpath and have them added via: `new ObjectMapper()..findAndRegisterModules();`. So, in order to make JDK8 primitives work clients would merely need to add the following dependencies: https://github.com/FasterXML/jackson-modules-java8#maven-dependencies

**Comment by philsttr** [comment]
Thanks for the recommendation!

I wasn't aware of `findAndRegisterModules()`

The next version of logstash-logback-encoder will call it automatically (but can be disabled if needed)
