### ISSUE TITLE
How to merge the logging events of the same thread into one json

### ISSUE THREAD

**Issue by hackeryutu** [logstash/logstash-logback-encoder#318]

**Comment by philsttr** [comment]
Please provide more information.  I don't understand what you are asking.  For example, provide log output of how you would like your log events formatted.

Typically, the thread name is written as part of each log event (e.g. via the [`threadName` provider](https://github.com/logstash/logstash-logback-encoder#providers-for-loggingevents)).  Then you would use a log aggregation/viewing tool downstream to view the log events by thread.
