### ISSUE TITLE
How to use LoggingEventNestedJsonProvider programmatically

### ISSUE THREAD

**Issue by miladamery** [logstash/logstash-logback-encoder#323]
Hi. In our project we use java config to send our logs to elk if needed. our project is based on spring and we did the same thing jhipster did for this purpose.
here is its configuration part.
```java
public void addLogstashAppender(LoggerContext context) {
        log.info("Initializing Logstash logging");

        LogstashTcpSocketAppender logstashAppender = new LogstashTcpSocketAppender();
        logstashAppender.setName("LOGBACK_LOGSTASH");
        logstashAppender.setContext(context);

        LogstashEncoder logstashEncoder = new LogstashEncoder();
        logstashEncoder.addProvider(nestedJsonProvider);
        
        logstashAppender.addDestinations(new InetSocketAddress(jHipsterProperties.getLogging().getLogstash().getHost(), jHipsterProperties.getLogging().getLogstash().getPort()));
        logstashAppender.setIncludeCallerData(true);

        ShortenedThrowableConverter throwableConverter = new ShortenedThrowableConverter();
        throwableConverter.setRootCauseFirst(true);
        logstashEncoder.setThrowableConverter(throwableConverter);

        logstashAppender.setEncoder(logstashEncoder);
        logstashAppender.start();

        // Wrap the appender in an Async appender for performance
        AsyncAppender asyncLogstashAppender = new AsyncAppender();
        asyncLogstashAppender.setContext(context);
        asyncLogstashAppender.setName("ASYNC_LOGSTASH");
        asyncLogstashAppender.setQueueSize(jHipsterProperties.getLogging().getLogstash().getQueueSize());
        asyncLogstashAppender.setIncludeCallerData(true);
        asyncLogstashAppender.addAppender(logstashAppender);
        asyncLogstashAppender.start();

        context.getLogger("org.baharan.framework.common.core.auditing.ElkLogger").addAppender(asyncLogstashAppender);
        context.getLogger("org.hibernate").addAppender(asyncLogstashAppender);
        context.getLogger("org.springframework").addAppender(asyncLogstashAppender);
        context.getLogger("org.springframework").setLevel(Level.ERROR);
        context.getLogger("org.hibernate").setLevel(Level.ERROR);
    }
```
and when i want to log with information more than message i use Markers.
```java
log.info(Markers.appendEntries(logData), message);
```
In this `logData` that i mentioned there is one field called `Description` that is `Map` itself. i need this field be sent as a nestedField but it is sent flat like `Description.operation` and `Description.action` etc.
in [documentation](https://github.com/logstash/logstash-logback-encoder#nested-json-provider) i saw this exists in xml format but i don't know how to this programmetically. thanks in advanced.

**Comment by philsttr** [comment]
If I understand correctly, the class of the `logData` object looks something like this:

```java
class LogData {
    Map Description;
}
```

By default, Jackson (used by logstash-logback-encoder) will serialize Map fields within an object as a nested JSON object.  I'm not aware of any configuration options within logstash-logback-encoder that would force it to output flattened fields like you mention.

Are you looking at the output from logstash-logback-encoder, or something from elasticsearch/kibana?

Can you provide the exact output that is being sent by logstash-logback-encoder?  You could temporarily see it via configuring a ConsoleAppender, or stand up a temporary netcat server (`nc -lk 4560`) and point your tcp appender to it.

**Comment by miladamery** [comment]
Thanks for your answer. I'm very very sorry. this was a bad mistake from me. flatted filed i mentioned is only about how kibana displays data. in actual json everything is correct. Description field is a sub json object in actual json but kibana display it in the way i said. I'm very sorry to bother. put it into me being new tab.
