### ISSUE TITLE
Can't add additional providers to LogstashAccessEncoder

### ISSUE THREAD

**Issue by fkrull** [logstash/logstash-logback-encoder#326]
Unlike with `LogstashEncoder`, you can't add a `<provider>` element to a `LogstashAccessEncoder` to add some additional fields. That means if you want to add additional fields (that aren't possible with `customFields`), you need to either

1) use AccessEventCompositeJsonEncoder and and rebuild the default behaviour of LogstashAccessEncoder or
2) subclass LogstashAccessEncoder and copy the `addProvider` method from LogstashEncoder.

LogstashAccessEncoder should support `<provider>` just like LogstashEncoder.

**Comment by philsttr** [comment]
Fixed for next release

**Comment by fkrull** [comment]
Excellent, thank you!
