### ISSUE TITLE
Treat SSLHandshakeException as a Connection failure

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#327]
When SSLSockets are first created, no handshaking is done. The initial handshake on the connection is initiated in one of three ways:
- calling `startHandshake` on the SSLSocket which explicitly begins handshakes, or
- any attempt to read or write application data on this socket causes an implicit handshake, or
- a call to `getSession` tries to set up a session if there is no currently valid session, and an implicit handshake is done.

In our case, the `openSocket()` creates the `SSLSocket`, connects it to the remote peer then makes it available to the read/write thread (the event dispatcher and the `ReaderCallable`). So the socket is open but communication is not yet fully usable.

A failure to establish the SSL session is therefore detected during the first attempt to write an event in the pipe. Since the connection was established, the system will try to reconnect immediately on the same destination and will *never* move to the next ones (see #193 for similar pattern).

--> My impression is the `openSocket()` method should explicitly invoke `startHandshake()` on the `SSLSocket` before declaring it _connected_. What do you think?

Note: as a workaround, we are registering a `Listener` calling `startHandshake` on the socket passed as argument to its `connectionOpened()` method. It throws a RuntimeException in case of problem which is then considered as a _connection failure_ by the `openSocket()` method. It seems to do the job until a better alternative is found.

**Comment by philsttr** [comment]
Seems reasonable.  Would you like to submit a PR?

**Comment by philsttr** [comment]
#327 Merged

**Comment by philsttr** [comment]
Thanks!
