### ISSUE TITLE
使用logstash-logback-encoder 5.3版本和最新的springboot结合使用报错

### ISSUE THREAD

**Issue by mark988** [logstash/logstash-logback-encoder#333]
Exception in thread "main" java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION

**Comment by philsttr** [comment]
Please include:
* your logback xml file
* version of logback-classic and logback-core

**Comment by mark988** [comment]
thanks
