### ISSUE TITLE
Predicate for Markers

### ISSUE THREAD

**Issue by wsargent** [logstash/logstash-logback-encoder#337]
From reading https://github.com/logstash/logstash-logback-encoder/issues/201

You could have a marker which would only write out to JSON iff a predicate was satified:

```java
// LogstashMarker appendPredicate(String fieldName, Supplier[Boolean] predicate, Supplier[Object] valueSupplier)
Markers.appendPredicate("trace", () -> MDC.get("traceId") != null, () -> MDC.get("traceId"));
```

**Comment by philsttr** [comment]
If my understanding is correct, I believe #201 is more about excluding specific fields within a larger pattern when using the pattern provider, vs excluding the whole pattern.

I don't quite see the need for a predicate like you mentioned.  You could just check the condition outside of the log statement and not append the marker.
