### ISSUE TITLE
Memoized Logstash Markers

### ISSUE THREAD

**Issue by wsargent** [logstash/logstash-logback-encoder#338]
Follow up on https://github.com/logstash/logstash-logback-encoder/issues/334

The deferred logstash marker is good at deferring the processing, but calls out to the supplier for every appender:

https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/marker/DeferredLogstashMarker.java#L46

This is in constrast to a lazy logstash marker, which would call the supplier on the first call, and [memoize](https://en.wikipedia.org/wiki/Memoization) the result thereafter.

This may not require a code change, as you can always call out to a memoization, but should be documented, especially for snapshot values that may change between appender calls.

**Comment by philsttr** [comment]
To keep the api simple, I just added memoization to the deferred marker.
