### ISSUE TITLE
JsonFactoryDecorator#decorate requires downcast to customize ObjectMapper

### ISSUE THREAD

**Issue by MenschNestor** [logstash/logstash-logback-encoder#345]
Hi there,

the following example from the README no longer works since the signature change of `JsonFactoryDecorator#decorate`:

```
public class ISO8601DateDecorator implements JsonFactoryDecorator  {

	@Override
	public JsonFactory decorate(JsonFactory factory) {
		ObjectMapper codec = factory.getCodec();
		codec.setDateFormat(new ISO8601DateFormat());
		return factory;
	}
}
```

`factory.getCodec()` now returns the type `ObjectCodec` instead of `ObjectMapper`. It is no longer possible to customize it without a downcast. This goes for this example as well as for registering Jackson modules etc.

What is the recommended way to register a Jackson module in a type-safe manner now?

**Comment by philsttr** [comment]
I'll update the example.

It is safe to downcast `factory.getCodec()` to `ObjectMapper` as long as you have not [configured the encoder to use a different output format](https://github.com/logstash/logstash-logback-encoder#non-json-formats).
