### ISSUE TITLE
Java 11: Encoder kills application

### ISSUE THREAD

**Issue by hannes-angst** [logstash/logstash-logback-encoder#347]
Sadly, I do not have the time to investigate this further ;(

I have a spring boot 2 project were we log to sysout in json to be collected with fluentd.

**java**

openjdk11

**Dependency**

      <dependency>
          <groupId>net.logstash.logback</groupId>
          <artifactId>logstash-logback-encoder</artifactId>
          <version>6.1</version>
      </dependency>

**Config**

      <?xml version="1.0" encoding="UTF-8"?>
      <configuration debug="true">
        <include resource="org/springframework/boot/logging/logback/default.xml"/>

        <appender name="JSON" class="ch.qos.logback.core.ConsoleAppender">
          <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
              <timestamp timeZone="UTC"/>
              <tags/>
              <mdc/>
              <logLevel/>
              <logLevelValue/>
              <threadName/>
              <message/>
              <stackTrace>...</stackTrace>
            </providers>
          </encoder>
        </appender>

        <root level="INFO">
          <appender-ref ref="JSON"/>
        </root>
      </configuration>

The application would terminated immediately after start without any log or error written.

          17:17:48,542 |-WARN in Logger[org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator] - No appenders present in context [default] for logger [org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator].
          17:17:48,574 |-WARN in ch.qos.logback.core.joran.action.IncludeAction - Could not find resource corresponding to [org/springframework/boot/logging/logback/default.xml]
          17:17:48,574 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
          17:17:48,574 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [JSON]
          17:17:48,582 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventJsonProviders] for [providers] property
          17:17:48,596 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider] for [timestamp] property
          17:17:48,597 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.TagsJsonProvider] for [tags] property
          17:17:48,597 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.MdcJsonProvider] for [mdc] property
          17:17:48,598 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LogLevelJsonProvider] for [logLevel] property
          17:17:48,599 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LogLevelValueJsonProvider] for [logLevelValue] property
          17:17:48,599 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.ThreadNameJsonProvider] for [threadName] property
          17:17:48,600 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.MessageJsonProvider] for [message] property
          17:17:48,602 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.StackTraceJsonProvider] for [stackTrace] property

I figured out that by adding this dependency, the logs get written correctly:

        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.2.11</version>
        </dependency>

**Impact**
If you are using a regular configured spring boot 2 application with `spring-boot-starter-data-rest` this dependency  (`jaxb-api` & Co)  seems to be added by a sub-sub-sub dependency so there is nothing that needs to be done.

**Comment by philsttr** [comment]
What specifically indicates this is a problem in logstash-logback-encoder?

Does the application work if you use a standard logback pattern layout in the ConsoleAppender?
