### ISSUE TITLE
Cannot configure ShortenedThrowableConverter

### ISSUE THREAD

**Issue by jasonab** [logstash/logstash-logback-encoder#348]
My apologies for filing such a speculative issue, but I cannot seem to get the ShortenedThrowableConverter to work, and I am wondering if it is getting overwritten somehow in the configuration. This is using Spring Boot 2.1.5 with Logback 1.2.3 and Logstash 6.1.

My logback.xml is very simple:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
                <maxDepthPerThrowable>30</maxDepthPerThrowable>
                <maxLength>2048</maxLength>
                <shortenedClassNameLength>20</shortenedClassNameLength>
                <!-- generated class names -->
                <exclude>\$\$FastClassByCGLIB\$\$</exclude>
                <exclude>\$\$EnhancerBySpringCGLIB\$\$</exclude>
                <exclude>^sun\.reflect\..*\.invoke</exclude>
                <!-- JDK internals -->
                <exclude>^com\.sun\.</exclude>
                <exclude>^sun\.net\.</exclude>
                <!-- dynamic invocation -->
                <exclude>^net\.sf\.cglib\.proxy\.MethodProxy\.invoke</exclude>
                <exclude>^org\.springframework\.cglib\.</exclude>
                <exclude>^org\.springframework\.transaction\.</exclude>
                <exclude>^org\.springframework\.validation\.</exclude>
                <exclude>^org\.springframework\.app\.</exclude>
                <exclude>^org\.springframework\.aop\.</exclude>
                <exclude>^java\.lang\.reflect\.Method\.invoke</exclude>
                <rootCauseFirst>true</rootCauseFirst>
                <inlineHash>true</inlineHash>
            </throwableConverter>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="STDOUT"/>
    </root>
</configuration>
```

However, none of these exclusions (or any of the configuration) take hold. If I remove the "exclude" tags, I get an error about having no exclusion pattern, so I know that the converter is being instantiated. I do get the error twice for some reason, which makes me wonder if the configuration is getting reset somehow.

I have also tried using the \<stackTrace\> element under \<providers\> but this does not change the behavior. Any suggestions would be appreciated!

**Comment by hannes-angst** [comment]
Quick fix

Try to wrap the shortener in a provider like in this example of the documentation:


      <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
        <providers>
          <mdc/>
          <pattern>
            <pattern>
              {
                "timestamp": "%date{ISO8601}",
                "myCustomField": "fieldValue",
                "relative": "#asLong{%relative}"
              }
            </pattern>
          </pattern>
          <stackTrace>
            <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
              <maxDepthPerThrowable>30</maxDepthPerThrowable>
              <maxLength>2048</maxLength>
              <shortenedClassNameLength>20</shortenedClassNameLength>
              <exclude>^sun\.reflect\..*\.invoke</exclude>
              <exclude>^net\.sf\.cglib\.proxy\.MethodProxy\.invoke</exclude>
              <evaluator class="myorg.MyCustomEvaluator"/>
              <rootCauseFirst>true</rootCauseFirst>
            </throwableConverter>
          </stackTrace>
        </providers>
      </encoder>

**Comment by jasonab** [comment]
Sorry, that part of my comment got elided by the brackets, but I have tried that, and I got the same result.

**Comment by hannes-angst** [comment]
> Sorry, that part of my comment got elided by the brackets, but I have tried that, and I got the same result.

Sorry for my stupid question, but have you changed the encoder class as well?

**Comment by jasonab** [comment]
Unfortunately, changing the encoder class means the pattern doesn't print the stack trace at all (and I tried with several patterns).

```xml
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <mdc/>
                <pattern>
                    <pattern>
                        {
                        "logger": "%logger",
                        "level": "%level",
                        "thread": "%thread",
                        "message": "%message",
                        "stack_trace": "%ex{full}"
                        }
                    </pattern>
                </pattern>
                <stackTrace>
                    <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
                        <maxDepthPerThrowable>30</maxDepthPerThrowable>
                        <maxLength>2048</maxLength>
                        <shortenedClassNameLength>20</shortenedClassNameLength>
                        <!-- generated class names -->
                        <exclude>\$\$FastClassByCGLIB\$\$</exclude>
                        <exclude>\$\$EnhancerBySpringCGLIB\$\$</exclude>
                        <exclude>^sun\.reflect\..*\.invoke</exclude>
                        <!-- JDK internals -->
                        <exclude>^com\.sun\.</exclude>
                        <exclude>^sun\.net\.</exclude>
                        <!-- dynamic invocation -->
                        <exclude>^net\.sf\.cglib\.proxy\.MethodProxy\.invoke</exclude>
                        <exclude>^org\.springframework\.cglib\.</exclude>
                        <exclude>^org\.springframework\.transaction\.</exclude>
                        <exclude>^org\.springframework\.validation\.</exclude>
                        <exclude>^org\.springframework\.app\.</exclude>
                        <exclude>^org\.springframework\.aop\.</exclude>
                        <exclude>^java\.lang\.reflect\.Method\.invoke</exclude>
                        <rootCauseFirst>true</rootCauseFirst>
                        <inlineHash>true</inlineHash>
                    </throwableConverter>
                </stackTrace>
            </providers>
        </encoder>
    </appender>
```

**Comment by philsttr** [comment]
Your configuration file looks correct.  I tried it myself in a simple (non-spring boot app).  Can you provide a complete example project that reproduces the behavior you see?

When you say...
> none of these exclusions (or any of the configuration) take hold

Do you mean that you see json output on the console, but the stacktrace is not shortened as desired?  Or do you not even see json output on the console?

**Comment by jasonab** [comment]
> Do you mean that you see json output on the console, but the stacktrace is not shortened as desired? Or do you not even see json output on the console?

Given my original configuration file, applying the throwableConverter does not change the output at all. Classes are not filtered out, and stack traces are not shortened.

I'm in the middle of something else right now, but hopefully next week I'll have some time to produce a mini project that reproduces this. I assume you could not reproduce with the non-Spring Boot app?

**Comment by philsttr** [comment]
I could not reproduce it. 

Was the output to the console in JSON format?  Meaning that at least the LogstashEncoder is being used?

**Comment by jasonab** [comment]
Yes, the output was the same (in JSON format) with or without the throwableConverter.

It seems that the default converter is somehow overwriting the custom converter, but I cannot track down where that might be happening.

**Comment by jasonab** [comment]
I created a stripped-down Spring Boot project, and see that the converter works in that environment. I'll try to build that project up to the point that I can replicate the issue, whatever it might be.

**Comment by jasonab** [comment]
Here is the culprit:
```java
logger.error("{}", keyValue("exception", e));
```

I have a custom exception handler for Spring that logs exceptions with the above statement. Logstash interprets that value as an exception correctly (in that it logs a stack trace), but it does not apply the stacktrace filter to the exception.

I'm more than happy to be told that I should not log exceptions this way, although I might ask that the documentation give more guidelines for how exceptions should be managed.

**Comment by philsttr** [comment]
I'd recommend logging exceptions the way you [normally log exceptions with slf4j/logback](https://www.baeldung.com/slf4j-log-exceptions)...  By including an extra argument that is not included in the message format pattern.  This will cause logback to record an exception in the `ILoggingEvent`, which will then be [read by the stacktrace json provider](https://github.com/logstash/logstash-logback-encoder/blob/5b52c4498ab14435fb662f05135b23acf92b90a8/src/main/java/net/logstash/logback/composite/loggingevent/StackTraceJsonProvider.java#L62), which uses the throwable converter to [convert the exception to a string field](https://github.com/logstash/logstash-logback-encoder/blob/5b52c4498ab14435fb662f05135b23acf92b90a8/src/main/java/net/logstash/logback/composite/loggingevent/StackTraceJsonProvider.java#L64).

If you use a structured argument for the exception as you have done [in your example](https://github.com/logstash/logstash-logback-encoder/issues/348#issuecomment-513989662), then logback will not interpret the argument as an exception, and will not set the `ILoggingEvent`'s throwable proxy.  In this case, the object is treated as any other POJO, and, Jackson will be used to serialize the exception object.  I'm guessing you're getting the exception serialized as a JSON object, rather than a string as well.

`LogstashEncoder` by default logs exceptions in a [field named `stack_trace`](https://github.com/logstash/logstash-logback-encoder#standard-fields), but you can [customize that field name](https://github.com/logstash/logstash-logback-encoder#customizing-standard-field-names).
If using [`LoggingEventCompositeJsonEncoder`](https://github.com/logstash/logstash-logback-encoder#composite-encoderlayout), then the `stackTrace` provider controls the stacktrace output, and the fieldName can be set on the `stackTrace` provider configuration.

**Comment by jasonab** [comment]
Thanks, Phil, I appreciate your patience on this.

If I might suggest two things, first adding a note/example in the documentation to mention logging exceptions without using kv structures. Second, and I'm not sure how feasible this is, check for a Throwable type before calling Jackson, and logging a warning that the user is serializing a throwable.

Regardless, appreciate your help on this. Logback has been a great help for us.

**Comment by philsttr** [comment]
I just updated the documentation.

I decided against outputting a warning when logging an exception as a structured argument.  There might be a legitimate use case for this somewhere, and I didn't want to have to add a configuration option for "don't log a warning for exceptions logged as structured arguments or markers"
