### ISSUE TITLE
Programatically add JSON Provider

### ISSUE THREAD

**Issue by ilaskaev** [logstash/logstash-logback-encoder#349]
I am looking for a way to programatically add JSON Providers to the logger.

I built a wrapper for the logger that provides custom functionality and a base configuration. I am now working on another library which now has this wrapped logger as a dependency, however I would like to add some specific JSON Providers that are relevant to this library in the form of a custom JSON Provider. 

I know a way of doing this would be to add the providers in the xml, but I am wondering if there is a way to do it programatically during for example, the initialization process of this library.

**Comment by philsttr** [comment]
Logback supports programmatic configuration as an alternative to xml configuration.    See [here for various ways to do so](https://stackoverflow.com/questions/16910955/programmatically-configure-logback-appender/17215011).

The Appenders/Encoders/Layouts provided by logstash-logback-encoder expose methods required to programmatically configure them.  These methods are the exact same methods that logback calls when it reads the xml configuration.  Therefore, everything that is possible in xml is possible programmatically.

Here are some other examples of people programmatically configuring the appenders/encoders/layouts of logstash-logback-encoder:
* https://github.com/logstash/logstash-logback-encoder/issues/323#issue-411185671
* https://github.com/logstash/logstash-logback-encoder/issues/252#issue-263316870

To add a provider, you just need to call [`logstashEncoder.addProvider`](https://github.com/logstash/logstash-logback-encoder/blob/cd62234b98a1037052e423d30b0c6c3b92754ce2/src/main/java/net/logstash/logback/encoder/LogstashEncoder.java#L39) or [`compositeJsonEncoder.getProviders().addProvider`](https://github.com/logstash/logstash-logback-encoder/blob/cd62234b98a1037052e423d30b0c6c3b92754ce2/src/main/java/net/logstash/logback/composite/JsonProviders.java#L63)

**Comment by ilaskaev** [comment]
That seems to work, thank you!
