### ISSUE TITLE
timeZone take no effect and default is not TimeZone of the host Java platform

### ISSUE THREAD

**Issue by cdfive** [logstash/logstash-logback-encoder#352]
version: 6.1

```xml
<appender name="LOGSTASH" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
	<destination>127.0.0.1:9100</destination>
	<encoder class="net.logstash.logback.encoder.LogstashEncoder">
		<timeZone>Asia/Shanghai</timeZone>
		<fieldNames>
			<timestamp>@timestamp</timestamp>
			<version>@version</version>
			<message>message</message>
			<logger>logger_name</logger>
			<thread>thread_name</thread>
			<level>level</level>
			<levelValue>[ignore]</levelValue>
		</fieldNames>
	</encoder>
</appender>
```
My host Java platform's timeZone is Asia/Shanghai, +8:00. 
If no `<timeZone>`, stdout print UTC time.
If add`<timeZone>Asia/Shanghai</timeZone>`, also print UTC time.

[https://github.com/logstash/logstash-logback-encoder/tree/logstash-logback-encoder-6.1#customizing-timestamp](https://github.com/logstash/logstash-logback-encoder/tree/logstash-logback-encoder-6.1#customizing-timestamp)
I refer to the Document Configuration, could someone please give some help?

**Comment by philsttr** [comment]
You mentioned that "stdout print UTC time", but the appender you mentioned is the TCP appender (not a console appender printing to stdout).  Do you also have a console appender configured?

When I try your configuration the encoder outputs the `@timestamp` field in the Asia/Shanghai timezone:

```
{"@timestamp":"2019-07-18T07:05:14.444+08:00"  ...
```

I'd like to confirm that nothing "downstream" is modifying the timestamp (e.g. logstash or elasticsearch or whatever you have that is listening on 9100).  To do so, can you start a simple netcat server using `nc -lk 9100` instead of logstash.  Then run your application and view the output from netcat.

**Comment by cdfive** [comment]
Above is logback's configuration, indeed there is also a console appender.
```xml
<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
	<encoder>
		<pattern>${log.pattern}</pattern>
		<charset>UTF-8</charset>
	</encoder>
</appender>
```
And the time output is right in console.

This my logstash conf: 
```
input {
    tcp {
         host => "127.0.0.1"
         port => 9100
         mode => "server"
         tags => ["tags"]
         codec => json_lines
    }
}
output {
    stdout { codec => rubydebug }
    kafka {
        bootstrap_servers => "localhost:9092"
        codec => json
        topic_id => "xxx"
        compression_type => "snappy"
    }
}
```
Both in logstash stdout and kafka message, @timestamp is UTC time, not my Java platform's timeZone( Asia/Shanghai)
Remove `codec => rubydebug`, still same result.

How did dou view the output, though the output  {stdout {}}?

**Comment by cdfive** [comment]
@philsttr I tried with `nc -lk 9100`, the timeout is right. Is it the reason for stdout, kafka plugins of output?

**Comment by philsttr** [comment]
Ok, so the `LogstashEncoder` of the appender named `LOGSTASH` is behaving as expected, and outputting the time in Asia/Shanghai.

The encoder used for the ConsoleAppender named `CONSOLE` is a `PatternLayoutEncoder`, whose timezone is [set via its pattern](https://logback.qos.ch/manual/layouts.html#conversionWord)

I believe logstash receives the timestamp in Asia/Shanghai time, but when logstash publishes the event to it's outputs, it publishes the event with a timestamp in UTC.  I do not believe logstash provides the ability to configure the timezone it uses when publishing the event to its outputs.

**Comment by cdfive** [comment]
Thank you very much, the `LogstashTcpSocketAppender` is right as expected.
It's confused that why not logstash provide a configure option in stdout or kafka plugin, it's convenient for users to view origin output result.
