### ISSUE TITLE
logback unable to send logs to logstash, using tcp

### ISSUE THREAD

**Issue by X-ration** [logstash/logstash-logback-encoder#356]
cannot use LogstashTcpSocketAppender to send logs to logstash, while logstash started already.

Here is my configuration:
logback.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true"  debug="true">
    <!-- ch.qos.logback.core.ConsoleAppender 表示控制台输出 -->
    <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n</pattern>
        </layout>
    </appender>

    <!-- Logstash配置 -->
    <appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>127.0.0.1:4560</destination>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <customFields>{"appname":"Spring"}</customFields>
        </encoder>
    </appender>
    <logger name="javatest.loggertest" level="info">
    </logger>
    <logger name="javatest.loggertest.LoggerTestMain" level="info" additivity="false">
        <appender-ref ref="stdout"/>
        <appender-ref ref="stash"/>
    </logger>
    <root level="debug">
        <appender-ref ref="stdout" />
        <appender-ref ref="stash"/>
    </root>
</configuration>
```

**Comment by philsttr** [comment]
Do you receive any errors?

Is logstash listening on `127.0.0.1:4560` ?

Can you provide your logstash.conf where you have configured the tcp input with the json_lines codec?

Can you try a test using a simple netcat receiver (instead of logstash)... For example `nc -lk 4560` ?

**Comment by X-ration** [comment]
> Do you receive any errors?
> 
> Is logstash listening on `127.0.0.1:4560` ?
> 
> Can you provide your logstash.conf where you have configured the tcp input with the json_lines codec?
> 
> Can you try a test using a simple netcat receiver (instead of logstash)... For example `nc -lk 4560` ?

OK, I checked the console output and no errors found, it seems connection established, while logstash started and cannot receive any message.
11:19:56,670 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[stash] - Log destination 127.0.0.1:4560: connection established.

I tried `nc 127.0.0.1 4560 < tcp.log` with some lines in `tcp.log`, logstash can receive and output to the console, so I think the problem should refer to logback,

I tried your suggestion `nc -lk 4560`, stopped logstash and started the project, could not receive any msgs.

logstash.conf:
```
input {
  tcp {
    host => "127.0.0.1"
    port => 4560
    codec => json_lines
  }
}

output {
  file {
    path => "/home/adam/test.txt"
  }
  stdout {
  }
}
```

**Comment by X-ration** [comment]
I've justed noticed `the TCP appenders are asynchronous` `..you'll need to cleanly shut down logback when your application exits.`

and 'cleanly shutdown' makes logs sended to logstash. O(∩_∩)O
