### ISSUE TITLE
Marker in combination in OSGi 

### ISSUE THREAD

**Issue by dirkmaarten** [logstash/logstash-logback-encoder#357]
Hi,

To use markers in an OSGi context the net.logstash.logback.marker package needs to be exported as well.

See: https://github.com/logstash/logstash-logback-encoder/blob/5b52c4498ab14435fb662f05135b23acf92b90a8/pom.xml#L336

At the moment this isn't the case  which causes problems while running in an OSGi aware project. I "fixed" this at work in a fork; I'll try to create a branch and pull request later on the week for this project.

Or are there reasons this isn't done?

**Comment by philsttr** [comment]
No reason, it's an oversight.  Feel free to submit a PR.  Otherwise, will get this fixed.
