### ISSUE TITLE
Formatted string in dev, JSON in prod

### ISSUE THREAD

**Issue by kennyjwilli** [logstash/logstash-logback-encoder#362]
Reading JSON logs without a formal viewer is painful. Is there an easy way to have the encoder write nicely formatted, non-JSON log lines in development and JSON formatted logs in production? I cannot figure out a way to get the `LogstashEncoder` or the default encoder to simply log a line that includes any `StructuredArguments`.

**Comment by philsttr** [comment]
For dev vs prod, you can configure different encoders.

If using spring-boot, you can use the [`springProfile`](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#_profile_specific_configuration) element.

If not using spring-boot, you can use [logback's conditional processing](https://logback.qos.ch/manual/configuration.html#conditional).

For the dev enviroment, if you don't want JSON output, you could just configure a standard logback pattern layout.  If you want a simplified JSON output with less fields, then you could use a [composite encoder](https://github.com/logstash/logstash-logback-encoder#composite-encoderlayout), and just include a bare minimum of providers that you want.  You could also consider logging in [YAML format](https://github.com/logstash/logstash-logback-encoder#non-json-formats), which is slightly easier to read.
