### ISSUE TITLE
can we support inner value() function in follow version?

### ISSUE THREAD

**Issue by HakChealKim** [logstash/logstash-logback-encoder#366]
code example will be like -> v("key1", v("key2", value))

the parsing result is ugly ->
"Data":{"key1":{"name":"LS_APPEND_OBJECT","fieldName":"key2"}}}}

can we have an improvement to support it

**Comment by philsttr** [comment]
I'd recommend just using a Map for the inner object.

```java
v("key1", Map.of("key2", value))
```

I have no plans to support nested structured arguments like the example you provided.  Structured arguments are really only meant to be the top-level argument provided to the log methods.
