### ISSUE TITLE
Do we have bug on value API?

### ISSUE THREAD

**Issue by HakChealKim** [logstash/logstash-logback-encoder#368]
The issue we face is that we apply value api to log time but can not 100% see the log field on kibana,
 the time is the time consuming when request  ;

almost 10 lost 1
correct example
    "Msg": {
      "Method": {
        "Name": "apply"
      },
      "Message": "Api call over, used time: 6ms",
      "Data": {
        "timeConsuming": 6
      },
lost timeUsing filed ex:
    "Msg": {
      "Class": "ApiCaller",
      "Message": "Api call over, used time: 88ms",
      "Method": {
        "Name": "apply"
      },
      "Data": {}
    },

**Comment by philsttr** [comment]
Hi, please provide your logback xml configuration file, and the exact output sent from logstash-logback-encoder.  You can view the exact output from logstash-logback-encoder by configuring a console or file appender with the encoder.
