### ISSUE TITLE
is there a way to send failed message to another appender ?

### ISSUE THREAD

**Issue by liurongwei** [logstash/logstash-logback-encoder#370]
when the logstash tcp server cann't be connected , is there a way send the failed message to another appender , eg FileAppender ?

**Comment by philsttr** [comment]
You can provide either a [logback `StatusListener`](http://logback.qos.ch/manual/configuration.html#statusListener) or a [logstash-logback-encoder `TcpAppenderListener`](https://github.com/logstash/logstash-logback-encoder#appender-listeners), and perform additional logging in those listeners.

**Comment by liurongwei** [comment]
When I close the logstash , I got the warning message below:

WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[logstash-compose] - Log destination 127.0.0.1:9601: Waiting 987ms before attempting reconnection.

But in the custom TcpAppenderListener event handle method didn't receive the failed message . my test implemention just empty method . I just want to test when the logstash server down how the message to be deliveried. 

`public class FailureEventAppenderListener implements TcpAppenderListener {

    private Logger log = LoggerFactory.getLogger("logstash-failure");

    /**
     * Called after given appender successfully sent the given event over the TCP connection.
     *
     * @param appender                the appender that sent the event
     * @param socket                  the socket over which the appender sent the event
     * @param deferredProcessingAware the event that was sent
     * @param durationInNanos         the time (in nanoseconds) it took to send the event
     */
    @Override
    public void eventSent(Appender appender, Socket socket, DeferredProcessingAware deferredProcessingAware, long durationInNanos) {

    }

    /**
     * Called when the given appender fails to send the given event over a TCP connection.
     *
     * @param appender                the appender that attempted to send the event
     * @param deferredProcessingAware the event that failed to send
     * @param reason                  what caused the failure
     */
    @Override
    public void eventSendFailure(Appender appender, DeferredProcessingAware deferredProcessingAware, Throwable reason) {
        log.warn("event send failed");
    }

    /**
     * Called after the given appender successfully opens the given socket
     *
     * @param appender the appender that opened the socket
     * @param socket   the socket that was opened
     */
    @Override
    public void connectionOpened(Appender appender, Socket socket) {

    }

    /**
     * Called after the given appender fails to open a socket
     *
     * @param appender the appender that attempted to open a socket
     * @param address  the address to which the appender attempted to connect
     * @param reason   what caused the failure
     */
    @Override
    public void connectionFailed(Appender appender, InetSocketAddress address, Throwable reason) {

    }

    /**
     * Called after the given appender closes the given socket
     * (either due to a reconnect, or shutdown)
     *
     * @param appender the appender that closed the socket
     * @param socket   the socket that was closed
     */
    @Override
    public void connectionClosed(Appender appender, Socket socket) {

    }

    /**
     * Called when the given appender is started.
     *
     * @param appender the appender that was started
     */
    @Override
    public void appenderStarted(Appender appender) {

    }

    /**
     * Called when the given appender is stopped.
     *
     * @param appender the appender that was stopped
     */
    @Override
    public void appenderStopped(Appender appender) {

    }

    /**
     * Called when the given event was successfully appended by the given appender.
     * <p>
     * Note that for Asynchronous appenders, this generally means that the event was
     * accepted for processing, but hasn't finished processing yet.
     *
     * @param appender                the appender when successfully appended the event
     * @param deferredProcessingAware the event that was appended
     * @param durationInNanos         the time (in nanoseconds) it took to append the event
     */
    @Override
    public void eventAppended(Appender appender, DeferredProcessingAware deferredProcessingAware, long durationInNanos) {

    }

    /**
     * Called when the given event was failed to be appended by the given appender.
     *
     * @param appender                the appender when successfully appended the event
     * @param deferredProcessingAware the event that was appended
     * @param reason                  what caused the failure
     */
    @Override
    public void eventAppendFailed(Appender appender, DeferredProcessingAware deferredProcessingAware, Throwable reason) {
        log.warn("event append failed");
    }`



> You can provide either a [logback `StatusListener`](http://logback.qos.ch/manual/configuration.html#statusListener) or a [logstash-logback-encoder `TcpAppenderListener`](https://github.com/logstash/logstash-logback-encoder#appender-listeners), and perform additional logging in those listeners.

**Comment by philsttr** [comment]
The `connectionClosed` callback will be invoked when the tcp connection closes.

Did you log any messages after the connection was closed?

**Comment by liurongwei** [comment]
> The `connectionClosed` callback will be invoked when the tcp connection closes.
> 
> Did you log any messages after the connection was closed?

`public class FailureEventAppenderListener implements TcpAppenderListener {

    private Logger log = LoggerFactory.getLogger("logstash-failure");

    /**
     * Called after given appender successfully sent the given event over the TCP connection.
     *
     * @param appender                the appender that sent the event
     * @param socket                  the socket over which the appender sent the event
     * @param deferredProcessingAware the event that was sent
     * @param durationInNanos         the time (in nanoseconds) it took to send the event
     */
    @Override
    public void eventSent(Appender appender, Socket socket, DeferredProcessingAware deferredProcessingAware, long durationInNanos) {
        log.info("event send");
    }

    /**
     * Called when the given appender fails to send the given event over a TCP connection.
     *
     * @param appender                the appender that attempted to send the event
     * @param deferredProcessingAware the event that failed to send
     * @param reason                  what caused the failure
     */
    @Override
    public void eventSendFailure(Appender appender, DeferredProcessingAware deferredProcessingAware, Throwable reason) {
        log.warn("event send failed");
    }

    /**
     * Called after the given appender successfully opens the given socket
     *
     * @param appender the appender that opened the socket
     * @param socket   the socket that was opened
     */
    @Override
    public void connectionOpened(Appender appender, Socket socket) {
        log.info("connection opened");
    }

    /**
     * Called after the given appender fails to open a socket
     *
     * @param appender the appender that attempted to open a socket
     * @param address  the address to which the appender attempted to connect
     * @param reason   what caused the failure
     */
    @Override
    public void connectionFailed(Appender appender, InetSocketAddress address, Throwable reason) {
        log.info("connection failed");
    }

    /**
     * Called after the given appender closes the given socket
     * (either due to a reconnect, or shutdown)
     *
     * @param appender the appender that closed the socket
     * @param socket   the socket that was closed
     */
    @Override
    public void connectionClosed(Appender appender, Socket socket) {
        log.info("connection closed");
    }

    /**
     * Called when the given appender is started.
     *
     * @param appender the appender that was started
     */
    @Override
    public void appenderStarted(Appender appender) {
        log.info("append started");
    }

    /**
     * Called when the given appender is stopped.
     *
     * @param appender the appender that was stopped
     */
    @Override
    public void appenderStopped(Appender appender) {
        log.info("append stoped");
    }

    /**
     * Called when the given event was successfully appended by the given appender.
     * <p>
     * Note that for Asynchronous appenders, this generally means that the event was
     * accepted for processing, but hasn't finished processing yet.
     *
     * @param appender                the appender when successfully appended the event
     * @param deferredProcessingAware the event that was appended
     * @param durationInNanos         the time (in nanoseconds) it took to append the event
     */
    @Override
    public void eventAppended(Appender appender, DeferredProcessingAware deferredProcessingAware, long durationInNanos) {
        log.info("event appended");
    }

    /**
     * Called when the given event was failed to be appended by the given appender.
     *
     * @param appender                the appender when successfully appended the event
     * @param deferredProcessingAware the event that was appended
     * @param reason                  what caused the failure
     */
    @Override
    public void eventAppendFailed(Appender appender, DeferredProcessingAware deferredProcessingAware, Throwable reason) {
        log.warn("event append failed");
    }
}`

the log show :
`2019-10-25 09:24:21.365  INFO 42240 --- [27.0.0.1:9601-2] logstash-failure                         : event send
2019-10-25 09:24:21.365  INFO 42240 --- [27.0.0.1:9601-2] logstash-failure                         : event appended
2019-10-25 09:24:21.366  INFO 42240 --- [27.0.0.1:9601-2] logstash-failure                         : event send
2019-10-25 09:24:21.366  INFO 42240 --- [27.0.0.1:9601-2] logstash-failure                         : event appended
2019-10-25 09:24:21.366  INFO 42240 --- [27.0.0.1:9601-2] logstash-failure                         : event send
2019-10-25 09:24:21.366  INFO 42240 --- [27.0.0.1:9601-2] logstash-failure                         : event appended
2019-10-25 09:24:21.366  INFO 42240 --- [27.0.0.1:9601-2] logstash-failure                         : connection closed
2019-10-25 09:24:21.367  INFO 42240 --- [27.0.0.1:9601-2] logstash-failure                         : event appended`

**Only the appended and connection closed event fired ,  event eventAppendFailed,eventSendFailure not fired when loging event  .**

Did the message droped when logstash server not serve ?

**Comment by philsttr** [comment]
The appender will buffer events internally until the connection can be re-established.  When the connection is re-established, the buffered messages will be sent.

The event buffer size defaults to 8192, and can be configured by setting `<ringBufferSize>8192</ringBufferSize>` on the appender  (The value must be a power of 2).

`eventSendFailure` will be called if there is an I/O error encountered while sending the event that cannot be automatically recovered.

`eventAppendFailed` will be called when the buffer is full, and new events are attempted to be added to the buffer.

**Comment by liurongwei** [comment]
thanks , I 'll process the eventAppendFailed event to catch the failed message .

**Comment by Fr33Radical** [comment]
Hello,
Is it possible to see the logback.xml configuration file?
