### ISSUE TITLE
No line separator in CompositeJsonLayout

### ISSUE THREAD

**Issue by tommcdo** [logstash/logstash-logback-encoder#374]
`CompositeJsonLayout` does not terminate lines with a line separator. In contrast, [`CompositeJsonEncoder` does](https://github.com/logstash/logstash-logback-encoder/blob/acfab5ea0bc42dd1d958e890b99bdc180a3d9909/src/main/java/net/logstash/logback/encoder/CompositeJsonEncoder.java#L128).

The result is that log output using the layout would look like this:

    {"field":"value1"}{"field":"value2"}

whereas with the encoder, it would look like this:

    {"field":"value1"}
    {"field":"value2"}

I'm not totally sure if `CompositeJsonLayout` *ought to* use a line separator, but my gut feeling is that it should.

Is this an oversight? Or am I perhaps missing something else?

**Comment by philsttr** [comment]
Thanks for the report!

I just added line separator support to `CompositeJsonLayout`.  I left the default as no separator for backwards compatibility purposes for now.  I'll likely change the default to be the same default as `CompositeJsonEncoder` in a future major release.

**Comment by tommcdo** [comment]
Cool, thanks!
