### ISSUE TITLE
[Logback Configuration XML] How to get StructuredArgument in Json Pattern

### ISSUE THREAD

**Issue by falcon-europe** [logstash/logstash-logback-encoder#381]
I have following configuration:

```
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
    <appender name="jsonConsoleAppender" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <pattern>
                    <pattern>
                        {
                            "SESSION_ID": "%mdc{SESSION_UUID}"
                        }
                    </pattern>
                </pattern>
                <!-- log guid support -->
                <!-- StructuredArgument and Marker support -->
                <!--
                <arguments/>
                <logstashMarkers/>
                -->
                <stackTrace>
                    <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
                        <maxDepthPerThrowable>10</maxDepthPerThrowable>
                        <maxLength>2048</maxLength>
                        <shortenedClassNameLength>32</shortenedClassNameLength>
                        <exclude>sun\.reflect\..*\.invoke.*</exclude>
                        <exclude>net\.sf\.cglib\.proxy\.MethodProxy\.invoke</exclude>
                        <rootCauseFirst>true</rootCauseFirst>
                    </throwableConverter>
                </stackTrace>
            </providers>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="jsonConsoleAppender" />
    </root>

</configuration>
```

I cannot figured out how to get value from structured argument property in JSON pattern.
I added for example StructuredArgument log.info("sample log", kv("SAMPLE_KEY", "TEST"));
Thank you for help in advance.

**Comment by philsttr** [comment]
Uncomment the `<arguments/>` element

**Comment by falcon-europe** [comment]
I do not want to put arguments at the end of json, I want to do something similar like with mdc
```
<pattern>
                    <pattern>
                        {
                            "SESSION_ID": "%mdc{SESSION_UUID}",
                            "SAMPLE_KEY": "%mdc{SAMPLE_KEY}"
                        }
                    </pattern>
                </pattern>
```

**Comment by philsttr** [comment]
I don't quite understand what you want.  Can you provide an example of the JSON output that you want when logging `log.info("sample log", kv("SAMPLE_KEY", "TEST"));` ?

**Comment by falcon-europe** [comment]
log.info("sample log", kv("SAMPLE_KEY", "TEST"), kv("SAMPLE_SECOND_KEY", "TEST SECOND"));

I would like to have following JSON output with specific entries order:

```
{
    "SAMPLE_KEY" : "TEST",
    "SESSION_ID" : "ab323dD3d3311Vv",
    "SAMPLE_SECOND_KEY" : "TEST SECOND"
}
```

Is it possible to do it using only pattern?

**Comment by philsttr** [comment]
Unfortunately, the `pattern` provider does not support structured arguments.

The `arguments` provider is the only provider that writes structured arguments.

Output field order is determined by the order in which the `providers` are added.  Therefore, all of the structured arguments are going to be together.  You could put `pattern` providers before and/or after them though.

**Comment by gmariotti** [comment]
@philsttr Apologies in advance for resuming an old issue. Would it be possible to have a `marker` in the `pattern`, instead? What I would like to achieve is to have a custom Marker/StructuredArgument serialized as usual to JSON but wrote as a string.
