### ISSUE TITLE
How to display one key value pair from StructuredArguments logback configuratiom XML

### ISSUE THREAD

**Issue by falcon-europe** [logstash/logstash-logback-encoder#383]
I would like to display only one selected pair from StructuredArguments.
```
{
     "SESSION_ID" : "vknvdke43nnwcke2",
     "TEST_1" : "TEST_1_VALUE"
}
```
Currently when I add <arguments/> tag it displays whole set of StructuredArguments.

```
Map myEntries = Maps.newHashMap();
myEntries.put("TEST_1","TEST_1_VALUE");
myEntries.put("TEST_2","TEST_2_VALUE");
log.info("TEST", entries(myEntries));
```

```
<providers>
    <pattern>
        <pattern>
            {
                "SESSION_ID": "%mdc{SESSION_UUID}"
            }
        </pattern>
    </pattern>
    <arguments/>
</providers>
```

Displays 

```
{
       "SESSION_ID" : "vknvdke43nnwcke2",
       "TEST_1" : "TEST_1_VALUE",
       "TEST_2" : "TEST_2_VALUE"
}
```
Thank you for any help in advance.

**Comment by philsttr** [comment]
It is not currently possible to do this.  The arguments provider adds all structured arguments.  There is currently no way of filtering which arguments are included, or which fields within a structured argument are included.
