### ISSUE TITLE
pattern for LoggingEventPatternJsonProvider 

### ISSUE THREAD

**Issue by deslauriersp** [logstash/logstash-logback-encoder#388]
0

I am trying to programmatically add an LogstashUdpSocketAppender, and I am unable to create a layout with a working pattern

```
private Layout<ILoggingEvent> getLayout() {

    LoggingEventCompositeJsonLayout newLayout = new LoggingEventCompositeJsonLayout();

    LoggingEventPatternJsonProvider patternProvider = new LoggingEventPatternJsonProvider();
    patternProvider.setPattern("{ \"field1\":\"value\" , \"message\":\"%message\"}");

    JsonProviders<ILoggingEvent> providers = new JsonProviders<ILoggingEvent>();        
    providers.addProvider(patternProvider);

    newLayout.setLineSeparator("SYSTEM");
    newLayout.setProviders(providers);

    return newLayout;

}
```
But this does not work, it outputs

> {"field1":"value","message":"%PARSER_ERROR[message]"}

If put the same pattern in a XML config file, it works fine.

Any idea?

**Comment by philsttr** [comment]
Have you called `layout.setContext(...)` and `layout.start()`?

**Comment by deslauriersp** [comment]
Setting the context on the  `LoggingEventPatternJsonProvider patternProvider patternProvider ` fixed my issue.

Thanks for pointing me in the right direction.
