### ISSUE TITLE
LogstashEncoder, includeCallerData tag doesn't output caller data in xml file (v5.3)

### ISSUE THREAD

**Issue by alissapaluska** [logstash/logstash-logback-encoder#390]
**Describe the bug**
When using net.logstash.logback.encoder.LogstashEncoder, and adding <includeCallerData>true<includeCallerData/> in my xml configuration for logging.

`<encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <includeCallerData>true</includeCallerData>
  </encoder>
`

**Expected behavior**
I expect to see caller data but don't.

**Additional context**

* logstash-logback-encoder version 
5.3
* logback version 
1.2.3
* jackson version 
2.10.1
* java version 
1.8

**Comment by philsttr** [comment]
What appender are you using?

Note the [following from the readme](https://github.com/logstash/logstash-logback-encoder#caller-info-fields):

> If the encoder is included inside an asynchronous appender, such as
`AsyncAppender`, `LoggingEventAsyncDisruptorAppender`, or `LogstashTcpSocketAppender`, then
`includeCallerData` must be set to true on the appender as well.

For example:

```xml
<appender name="stash" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
    ...
    <includeCallerData>true</includeCallerData>
    <encoder class="net.logstash.logback.encoder.LogstashEncoder"> 
        <includeCallerData>true</includeCallerData>
    </encoder>
</appender>
```

**Comment by alissapaluska** [comment]
I'm primarily using the ConsoleAppender, and I'd like to use the RollingFileAppender as well.

**Comment by alissapaluska** [comment]
Ahhh, thanks! Looks like I was wrapping the original appender in a an Async, and didn't include the callerData tag in that specific config.
