### ISSUE TITLE
StructuredArguments should have defer

### ISSUE THREAD

**Issue by wsargent** [logstash/logstash-logback-encoder#396]
In the same way that Markers has a `defer` method that will offset JSON serialization until the appender gets it, the `StructuredArguments` should also have a `defer` method that can wrap `StructuredArguments.raw(k, v)`.

**Comment by philsttr** [comment]
Note that a deferred StructuredArgument will have slightly different behavior than a deferred Marker.

Logback will utilize all arguments (including StructuredArguments) in `LoggingEvent.prepareForDeferredProcessing()`, which is called when dispatching a LoggingEvent to another thread in async appenders.

Therefore, a deferred StructuredArgument will always be "realized" in the thread that logged the event.  Whereas a deferred Marker could potentially be "realized" later in another thread.

**Comment by wsargent** [comment]
It still has value, though, because a `defer` won't take effect until Logback has decided the event is actually worth logging.  If the logging event is not accepted by a filter (either explicitly or through logger levels) then `prepareForDeferredProcessing` will never be called.

**Comment by philsttr** [comment]
Agreed.  Just wanted to point out that it won't be exactly the same as a marker.
