### ISSUE TITLE
Output timestamp in floating point seconds since epoch

### ISSUE THREAD

**Issue by gmcelhoe** [logstash/logstash-logback-encoder#399]
**Is your feature request related to a problem? Please describe.**
To output number in a format compatible for https://github.com/logzio/fluent-plugin-logzio , I need to output the timestamp in seconds, not milliseconds.

**Describe the solution you'd like**
In addition to `[UNIX_TIMESTAMP_AS_NUMBER]`, I propose adding `[UNIX_TIMESTAMP_AS_SECONDS]` which will generate an unquoted floating point value in the JSON output.

**Describe alternatives you've considered**
I will probably format the time in the logger in the meantime, but there is a mild efficiency in sending timestamps over formatting the output in the logger.

**Additional context**
If this is an acceptable solution, then I can submit a pull request.

**Comment by philsttr** [comment]
Can you point me to where this time format is documented?

**Comment by wsargent** [comment]
This is available in terse-logback: https://github.com/tersesystems/terse-logback/blob/master/logback-classic/src/main/java/com/tersesystems/logback/classic/TimeSinceEpochConverter.java

https://github.com/tersesystems/terse-logback/blob/master/logback-structured-config/src/main/resources/terse-logback/initial.xml#L40

From there, you can represent it as a number using the `#asDouble` converter...
