### ISSUE TITLE
Error in the regex capturing groups example.

### ISSUE THREAD

**Issue by saltos** [logstash/logstash-logback-encoder#401]
Chapter [Identifying field values to mask by value](https://github.com/logstash/logstash-logback-encoder#identifying-field-values-to-mask-by-value) contains invalid example for the capturing regex groups case.
In the example you use "\1" as the group reference but it does not work. We should use a dollar sign as a reference. Please look at [java.util.regex.Matcher](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#replaceAll(java.lang.String)) documentation.
I've spent some time wondering why "\1" does not work for me.

**Comment by philsttr** [comment]
Fixed.  Thanks for the report!
