### ISSUE TITLE
Renaming MDC field

### ISSUE THREAD

**Issue by contactreji** [logstash/logstash-logback-encoder#403]
I am trying to plug in the encoder with a java app which uses apache camel framework. The framework already has some inbuilt MDC information as shown here -> https://people.apache.org/~dkulp/camel/mdc-logging.html

I want to rename certain fields in the log output. For example, instead of following 

```json
{"application_name":"roma-runtime","timestamp":"2020-05-06T13:48:16.366Z","logger":"org.apache.camel.impl.DefaultCamelContext","level":"INFO","class":"org.apache.camel.impl.DefaultCamelContext","method":"start","file":"DefaultCamelContext.java","line":3186,"thread":"http-nio-8888-exec-3","camel.contextId":"53081f9c-6d51-4f98-8c9d-439de1fcd1db","message":"Total 3 routes, of which 3 are started"}
````

I want camel.contextId to be renamed to integration_id. as follows
```json
{"application_name":"roma-runtime","timestamp":"2020-05-06T13:48:16.366Z","logger":"org.apache.camel.impl.DefaultCamelContext","level":"INFO","class":"org.apache.camel.impl.DefaultCamelContext","method":"start","file":"DefaultCamelContext.java","line":3186,"thread":"http-nio-8888-exec-3","integration_id":"53081f9c-6d51-4f98-8c9d-439de1fcd1db","message":"Total 3 routes, of which 3 are started"}
````

Is there a way I can configure this name mapping in my logback-spring.xml file?

**Comment by philsttr** [comment]
I've added support for this in the next version.

If you need something before the next version is released, you can [disable writing the MDC](https://github.com/logstash/logstash-logback-encoder#mdc-fields),  and add your own [custom `JsonProvider`](https://github.com/logstash/logstash-logback-encoder#custom-json-provider) that outputs the MDC using custom field names.
