### ISSUE TITLE
Handling multi-line log messages

### ISSUE THREAD

**Issue by metacubed** [logstash/logstash-logback-encoder#404]
When configuring handling of newlines in log messages, a useful addition would be the ability to output the `"message"` field as a JSON array, instead of a JSON string.

For example, with either of these logging statements:

```java
logger.error("first line{}second line", System.lineSeparator());
// or
logger.error("first line\nsecond line");
// or
logger.error("first line\r\nsecond line");
```

The output would be consistent:

```yaml
{
    "message": [
        "first line",
        "second line"
    ],
    ...
}
```

This would provide an unambiguous parsing format on the target system instead of relying on the source platform's newline representation.

**Comment by philsttr** [comment]
While this is not directly supported by the existing JsonProviders, you could [disable the output of the current message field](https://github.com/logstash/logstash-logback-encoder#customizing-standard-field-names), and implement this functionality in a [custom JsonProvider](https://github.com/logstash/logstash-logback-encoder#custom-json-provider)


Alternatively, would you be interested in submitting a PR for modifying the existing `MessageJsonProvider` to support this?  You could modify the `MessageJsonProvider` to have an option to split the message on newlines.

**Comment by metacubed** [comment]
@philsttr, thanks for pointing me to the right class. I'll try adding a new option to the `MessageJsonProvider`.

**Comment by metacubed** [comment]
@philsttr, are you ok with adding the [JUnitParams](https://github.com/Pragmatists/JUnitParams) library to this project? It uses the same license, Apache 2.0 - 2004.

It is also recommended by JUnit: [Parameterized tests - See also](https://github.com/junit-team/junit4/wiki/Parameterized-tests#see-also)

**Comment by philsttr** [comment]
I'd rather not, since I don't see much activity on that project, and the last release was close to 3 years ago.

**Comment by metacubed** [comment]
@philsttr, no worries, I just submitted a PR. Please review #413 when convenient.
