### ISSUE TITLE
Logs are not displayed when an exception is passed as a parameter

### ISSUE THREAD

**Issue by robsonbittencourt** [logstash/logstash-logback-encoder#406]
**Describe the bug**
When entering a log with a message and an exception, no output is displayed. When I do not inform the exception, the log is displayed normally.

**To Reproduce**
1. I created a project set up in a simple way to demonstrate the problem.
https://github.com/robsonbittencourt/logstash-encoder-demo

2. Clone and import the project and run the main method. After initialization two log messages are inserted.
![Screenshot from 2020-05-10 23-19-02](https://user-images.githubusercontent.com/1248602/81518528-b7c52100-9314-11ea-8e4b-ae387661f53d.png)

3. But only the message that the exception by parameter was not reported is displayed
![Screenshot from 2020-05-10 23-20-56](https://user-images.githubusercontent.com/1248602/81518633-0e325f80-9315-11ea-9967-620452ab6d74.png)

**Expected behavior**
According to the documentation, the log should be displayed and contain the stacktrace field.

* logstash-logback-encoder version: 6.3
* logback version: 1.2.3
* jackson version: 2.10.4
* java version: 11

**Comment by philsttr** [comment]
I think this is just IntelliJ being "smart", and collapsing the log lines.

Click the little plus (+) icon seen on the left in the second image you posted.

**Comment by robsonbittencourt** [comment]
@philsttr you're right. I missed that detail. What strange behavior from IDE.

Thank you very much for the quick response, and sorry for the inconvenience.
