### ISSUE TITLE
Support for yaml based configuration

### ISSUE THREAD

**Issue by contactreji** [logstash/logstash-logback-encoder#408]
I see that you have xml based configuration as shown here - https://github.com/logstash/logstash-logback-encoder/blob/master/src/test/resources/logback-test.xml

Just curious to know if the library supports yaml based configuration instead of XML. If not, would that be considered down the road?

- Reji Mathews

**Comment by philsttr** [comment]
logstash-logback-encoder relies on logback for configuration.  Logback configuration supports xml, groovy, and programmatic.  You'll need to file a request for logback for additional configuration formats.
