### ISSUE TITLE
StructuredArguments default configuration

### ISSUE THREAD

**Issue by philanimalandrews** [logstash/logstash-logback-encoder#410]
**Describe the bug**
I read the docs and tried to use the StructuredArguments feature but could not get it to output any keyValue(..) or value(..) to the JSON output.
It appears that this does not work out of the box and I need to add this to the logback.xml :-

```
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder class="net.logstash.logback.encoder.LogstashEncoder">
        **<provider class="net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider"/>**
    </encoder>
</appender>
```

This is not mentioned at all in the docs and it was only by googling and finding `https://stackoverflow.com/questions/52426121/logstash-logback-event-specific-custom-fields-using-structuredarguments-are-no`  that I managed to get it to work.

**Expected behavior**
Either this could be enabled by default or at the very least it should be mentioned in the documentation just before the examples for keyValue(..)  etc..

* what output did you expect
To work out of the box in the absence of documentation

* logstash-logback-encoder version
* logback version
* jackson version
* java version

**Comment by philsttr** [comment]
Are you using the latest version (6.3)?  If not, please try again with the latest version.
