### ISSUE TITLE
Allow more direct access to ObjectMapper or allow controlling its creation

### ISSUE THREAD

**Issue by joca-bt** [logstash/logstash-logback-encoder#415]
We use Logstash Logback Encoder to log all requests to our API into Elasticsearch.

Our service (Spring-based) has an object mapper with several customizations: lots of feature toggles, custom modules, custom naming strategy, etc. and we would like to re-use that object mapper with all its configurations in our Logstash Logback Encoder. Although we can access Logstash Logback Encoder's object mapper via

```
... implements JsonFactoryDecorator {
    @Override
    public JsonFactory decorate(JsonFactory factory) {
        ObjectMapper objectMapper = (ObjectMapper) factory.getCodec();
        ...
   }
}
```

we would like to be able to replace it entirely or have full control over its creation. For example, re-use the object mapper we use for serializing and deserializing all requests and responses in Logstash Logback Encoder. Right now we have to keep two and make sure we configure them the same way.

Another use case is when we don't fully own the object mapper and get it via dependency injection from an interface if we're offering our service as a library, for example. In that case it's more difficult to make sure the object mapper used by Logstash Logback Encoder matches our global one. For example, in Spring we can just customize the object mapper as here or we can totally control its creation.

We're also doing it programatically (since we configure both Jackson and Logback programatically instead of via configuration files):

```
LoggingEventCompositeJsonEncoder encoder = new LoggingEventCompositeJsonEncoder();
encoder.setJsonFactoryDecorator(...);
```

**Comment by philsttr** [comment]
Hi @joca-bt ,

You can return a different `JsonFactory` from a `JsonFactoryDecorator` with a different `ObjectMapper` configured.  As an example, you can take a look at the [decorator that switches from JSON to Smile format](https://github.com/logstash/logstash-logback-encoder/blob/d24b58e3612ff352fd765c55ecd491007dc71a7a/src/main/java/net/logstash/logback/decorate/smile/SmileJsonFactoryDecorator.java#L33-L36).

**Comment by joca-bt** [comment]
We ended up replacing the object mapper used by the default json factory, this way we keep the customizations made by logstash (`JsonGenerator.Feature.FLUSH_PASSED_TO_STREAM`), and just swap the object mapper.
