### ISSUE TITLE
DSL-JSON as a possible backend

### ISSUE THREAD

**Issue by wsargent** [logstash/logstash-logback-encoder#418]
I realize this is well and truly impractical, but DSL-JSON appears to have some interesting performance characteristics for serialization:

https://github.com/cowtowncoder/java-json-performance-benchmarks/wiki

https://github.com/fabienrenaud/java-json-benchmark

http://www.cowtowncoder.com/blog/archives/2011/05/entry_455.html

https://blog.dsl-platform.com/improving-java-json-speed/

**Comment by philsttr** [comment]
This is not really feasible.  logstash-logback-encoder is very tightly coupled with jackson.
