### ISSUE TITLE
Logmessage size limit

### ISSUE THREAD

**Issue by philbert** [logstash/logstash-logback-encoder#42]
Hi,
i got some error messages which are quite large cause of appending the complete stack trace.
unfortunately there seems to be a size limit - max char count i successfully transmitted to logstash was 8704. bigger messages will be truncated which results in a malformed json object and
logstash cannot parse and store it (u will never notice unless u put logstash into debug mode)
according to the syslog protocol spec (http://tools.ietf.org/html/rfc5424#page-9) there is max message length.

would be nice if we could here find out where the size limit comes from and try to prevent malformed json, by for example create a warning/handling for bigger messages

**Comment by philsttr** [comment]
I know this is not explicitly what you asked for, but it will help your situation... There is a new ability to shorten stacktraces.  See the documentation in [README.md](https://github.com/logstash/logstash-logback-encoder#customizing-stack-traces).  Although, it's still in a snapshot version, and hasn't been released quite yet.

Will keep this issue open until there is a hard limit.  But shortening stacktraces should help out in the meantime.

**Comment by philsttr** [comment]
I'm going to close this issue now.

While not providing an absolute maximum for log event length, logstash-logback-encoder does provide lots of configurability to shorten your events.

The primary cause for large events is stacktraces.  See the new `ShortenedThrowableConverter` for how you can place various limits on stacktraces.  Specifically, you can limit the depth of each throwable, exclude specific stackframes, and put a hard limit on the maximum number of characters in a stacktrace.

You can also exclude any of the default fields included in the JSON output if you want to shorten events further.  See [README.md](https://github.com/logstash/logstash-logback-encoder#customizing-standard-field-names) for more info.

For user-provided fields and user-provided field values, logstash-logback-encoder does not have the proper context to know what fields to shorten or how to shorten them.  Therefore, it is up to the user to ensure that they are short enough for proper logging.
