### ISSUE TITLE
Too many objects net.logstash.logback.appender.AsyncDisruptorAppender$LogEvent

### ISSUE THREAD

**Issue by cherrishccl** [logstash/logstash-logback-encoder#420]
Logstash had created too many objects when I used logstash to print logs. Is it normal?

jmap -histo 18640|head -20

num     #instances         #bytes  class name
----------------------------------------------
   1:       3145728       50331648  net.logstash.logback.appender.AsyncDisruptorAppender$LogEvent
   2:        625235       49270472  [C
   3:         31023       31172624  [I
   4:        122457       19960632  [Ljava.lang.Object;
   5:         42784       12753960  [B
   6:        499141       11979384  java.lang.String

**Comment by jack-z** [comment]
hi ,bro
how did you solved the problem?
