### ISSUE TITLE
Quotes in stack trace are not being escaped.

### ISSUE THREAD

**Issue by marcuslange** [logstash/logstash-logback-encoder#441]
**Describe the bug**
Quotes in stack trace are not being escaped.

**To Reproduce**
1. Use this `logback.xml` configuration...
```xml
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender" >
            <filter class="ch.qos.logback.core.filter.EvaluatorFilter">
                <evaluator class="com.swacorp.crew.planning.common.logging.logback.PatternMatchingLogEventEvaluator">
                    <pattern><!--omitted--></pattern>
                    <threshold>WARN</threshold>
                </evaluator>
                <OnMismatch>NEUTRAL</OnMismatch>
                <OnMatch>DENY</OnMatch>
            </filter>
            <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
                <providers>
                    <timestamp>
                        <timeZone>UTC</timeZone>
                    </timestamp>
                    <pattern>
                        <omitEmptyFields>true</omitEmptyFields>
                        <pattern>
                            {
                            "service": "${springAppName:-}",
                            "traceId": "%X{X-B3-TraceId:-}",
                            "spanId": "%X{X-B3-SpanId:-}",
                            "parentId": "%X{X-B3-ParentSpanId:-}"
                            }
                        </pattern>
                    </pattern>
                    <message/>
                    <loggerName>
                        <shortenedLoggerNameLength>200</shortenedLoggerNameLength>
                    </loggerName>
                    <threadName/>
                    <logLevel/>
                    <logLevelValue/>
                    <stackTrace>
                        <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
                            <maxDepthPerThrowable>30</maxDepthPerThrowable>
                            <maxLength>4096</maxLength>
                            <shortenedClassNameLength>200</shortenedClassNameLength>
                            <rootCauseFirst>true</rootCauseFirst>
                            <inlineHash>true</inlineHash>
                        </throwableConverter>
                    </stackTrace>
                    <throwableClassName>
                        <useSimpleClassName>true</useSimpleClassName>
                    </throwableClassName>
                    <logstashMarkers/>
                </providers>
            </encoder>
        </appender>
```
2. Execute this logger statement (e.g. `logger.debug(...)`) ...
exception with message like "blah with name "foo" is not valid"

3. See error, or unexpected output
Stack trace contain the message with unescaped quotes. We see this a lot in exception from postgresql and the spring resttemplate(exceptionmessage is the JSON error response) 

**Expected behavior**
* what output did you expect
For quotes in a stack trace to either be escaped or encoded.

**Additional context**

* logstash-logback-encoder version 6.4
* logback version 1.2.3
* jackson version 2.11.2
* java version 11

**Comment by marcuslange** [comment]
appender config.
`
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender" >
            <filter class="ch.qos.logback.core.filter.EvaluatorFilter">
                <evaluator class="com.swacorp.crew.planning.common.logging.logback.PatternMatchingLogEventEvaluator">
                    <pattern></pattern>
                    <threshold>WARN</threshold>
                </evaluator>
                <OnMismatch>NEUTRAL</OnMismatch>
                <OnMatch>DENY</OnMatch>
            </filter>
            <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
                <providers>
                    <timestamp>
                        <timeZone>UTC</timeZone>
                    </timestamp>
                    <pattern>
                        <omitEmptyFields>true</omitEmptyFields>
                        <pattern>
                            {
                            "service": "${springAppName:-}",
                            "traceId": "%X{X-B3-TraceId:-}",
                            "spanId": "%X{X-B3-SpanId:-}",
                            "parentId": "%X{X-B3-ParentSpanId:-}"
                            }
                        </pattern>
                    </pattern>
                    <message/>
                    <loggerName>
                        <shortenedLoggerNameLength>200</shortenedLoggerNameLength>
                    </loggerName>
                    <threadName/>
                    <logLevel/>
                    <logLevelValue/>
                    <stackTrace>
                        <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
                            <maxDepthPerThrowable>30</maxDepthPerThrowable>
                            <maxLength>4096</maxLength>
                            <shortenedClassNameLength>200</shortenedClassNameLength>
                            <rootCauseFirst>true</rootCauseFirst>
                            <inlineHash>true</inlineHash>
                        </throwableConverter>
                    </stackTrace>
                    <throwableClassName>
                        <useSimpleClassName>true</useSimpleClassName>
                    </throwableClassName>
                    <logstashMarkers/>
                </providers>
            </encoder>
        </appender>
`

**Comment by philsttr** [comment]
Can you provide example output that you receive? 

When I tried your config with this log statement...

```java
LOGGER.error("Log Message", new RuntimeException("Error \"Message\""));
```

...I received the following output, which has the quotes escaped...
```json
{"@timestamp":"2020-10-06T23:26:08.337Z","service":"springAppName_IS_UNDEFINED","message":"Log Message","logger_name":"net.logstash.logback.Main","thread_name":"main","level":"ERROR","level_value":40000,"stack_trace":"<#5bf3e980> java.lang.RuntimeException: Error \"Message\"\n\tat net.logstash.logback.Main.main(Main.java:28)\n","throwable_class":"RuntimeException"}

```

**Comment by marcuslange** [comment]
This can be closed. It looks to be something happening in fluentbit. Sorry for this disruption.
