### ISSUE TITLE
About EventClearingEventHandler

### ISSUE THREAD

**Issue by AngryMills** [logstash/logstash-logback-encoder#447]
Hi,
I want to ask some help about `EventClearingEventHandler`.
`EventClearingEventHandler`'s description ：Clears the event after a delegate event handler has processed the event,
 so that the event can be garbage collected.
Why `EventClearingEventHandler.onEvent` has the content ：delegate.onEvent(event, sequence, endOfBatch);
```
        @Override
        public void onEvent(LogEvent<Event> event, long sequence, boolean endOfBatch) throws Exception {
            try {
                delegate.onEvent(event, sequence, endOfBatch);
            } finally {
                /*
                 * Clear the event so that it can be garbage collected.
                 */
                event.event = null;
            }
        }
```
When `AbstractLogstashTcpSocketAppender.onEvent` occurs , It may cause reopen socket , then makes some problem.
Thanks for answering.

**Comment by AngryMills** [comment]
some problems like this.When first socket connection established,every ten seconds will log 'after 20 seconds try to attemp reconnection' , then 20s later connection established again，So repeatedly. Network is ok , is it a normal phenomenon?
Maybe how to close logback-self WARN log.
11:48:54,484 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination xxx.com:4562: connection established.
11:49:04,524 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination xxx.com:4562: Waiting 19949ms before attempting reconnection.
11:49:24,477 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination xxx.com:4562: connection established.
11:49:34,478 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination xxx.com:4562: Waiting 19995ms before attempting reconnection.
Thanks for answering.

**Comment by AngryMills** [comment]
I solve this problem.
When different jars use logback.xml and logstash-logback-encoder.jar ,manual loading logback.xml like below.
`LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
        try {
            // assume SLF4J is bound to logback in the current environment
            URL url = LogbackConfigLoader.class.getClassLoader().getResource(LOGBACK_CONFIG);
            JoranConfigurator configurator = new JoranConfigurator();
            configurator.setContext(context);
            // Call context.reset() to clear any previous configuration, e.g. default
            // configuration. For multi-step configuration, omit calling context.reset().
            context.reset();
            configurator.doConfigure(url);
        } catch (JoranException je) {
            // StatusPrinter will handle this
            LogUtil.log("LogbackConfigLoader error=" + je);
        } `
But manual loaded jar has a different logstash-logback-encoder version with applicaiton jar.
applicaiton jar : 5.3
manual loaded jar: 6.4
The applicaiton jar has a logback.xml with another LogstashTcpSocketAppender,I don't know is it related to this
When both jar use 6.4 , both appear WARN Log.
When both jar use 5.3 , it's OK.
Has any idea?
Thanks for answering.

**Comment by philsttr** [comment]
Hi @AngryMills 

It is not normal for a connection to be re-established unless the connection is closed or broken for some reason.

Can you provide your logback.xml?

**Comment by AngryMills** [comment]
> Hi @AngryMills
> 
> It is not normal for a connection to be re-established unless the connection is closed or broken for some reason.
> Also the "connection established" message [should be an INFO message](https://github.com/logstash/logstash-logback-encoder/blob/c6b3af90757977850aa94bb7305f40355ab4db60/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L738), not a WARN message.
> 
> Can you provide your logback.xml?

Thanks for answering.
Normal logback level is WARN,can't see the "connection established" message,I modify the source and build another jar for logging more some message.
I can make sure the connection is OK, and message can be received by server.
When I add more log message , I find the readerFuture will throw SocketReadTimeout Exception.
I guess something close the outputstream.
I develop a javaagent plugin ,when using , a few applications had this problem.
My jar has own classloader for loading logback.xml in mine.
And some springboot applications load their logback.xml in theirs.
Use like : java -javaagent:agent.jar -jar xxx.jar
The two jars are independent and they both config LogstashTcpSocketAppender，maybe it has nothing to do with two jar packages .I try to delete the springboot application‘s logback.xml and had same problem(make sure the agent.jar's warn log).
So agent.jar has the warn message with logstash-logback-encoder-6.4 , and influence only a few applications.
But logstash-logback-encoder-5.3 is OK.
this is agent's logback.xml
<appender name="SLEUTH-INFO" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>${sleuth.url}</destination>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <includeCallerData>false</includeCallerData>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>INFO</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>
    </appender>
    
    <appender name="SLEUTH-INFO-ASYNC" class="ch.qos.logback.classic.AsyncAppender">
        <discardingThreshold>20</discardingThreshold>
        <queueSize>5000</queueSize>
        <neverBlock>true</neverBlock>
        <appender-ref ref="SLEUTH-INFO"/>
    </appender>
Looking forward to answering.

**Comment by philsttr** [comment]
I'd suggest adding `debug="true"` to your logback.xml configuration element (for example, `<configuration debug="true">`), as described in the [logback configuration manual](http://logback.qos.ch/manual/configuration.html#dumpingStatusData).  This will cause all INFO level status messages to be printed on the console.

Can you provide all the logback status messages you see on the console after enabling logback debug?

Also note that you do not need the `AsyncAppender`.  The `LogstashTcpSocketAppender` is asynchronous already, so it does not need to be wrapped in another asynchronous appender.  See this note in the [README.md](https://github.com/logstash/logstash-logback-encoder#tcp-appenders)...
> Internally, the TCP appenders are asynchronous (using the LMAX Disruptor RingBuffer). All the encoding and TCP communication is delegated to a single writer thread. There is no need to wrap the TCP appenders with another asynchronous appender (such as AsyncAppender or LoggingEventAsyncDisruptorAppender).

**Comment by AngryMills** [comment]
Thanks for answering.
I add `debug="true"` to logback.xml,this is the logback.xml 

<configuration debug="true">

    <appender name="SLEUTH-INFO" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <destination>sleuth.com:4510</destination>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <includeCallerData>false</includeCallerData>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <level>INFO</level>
            <onMatch>ACCEPT</onMatch>
            <onMismatch>DENY</onMismatch>
        </filter>
    </appender>

    <logger name="mapi-sleuth-log" level="info" additivity="false">
        <appender-ref ref="SLEUTH-INFO"/>
    </logger>
</configuration>

This is the message.
10:32:42,406 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
10:32:42,406 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
10:32:42,406 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/data/sleuth-agent/reporter/sleuth-agent-reporter-flume.jar!/logback.xml]
10:32:42,491 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@357246de - URL [jar:file:/data/sleuth-agent/reporter/sleuth-agent-reporter-flume.jar!/logback.xml] is not of type file
10:32:42,633 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [net.logstash.logback.appender.LogstashTcpSocketAppender]
10:32:42,692 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SLEUTH-INFO]
10:32:44,494 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sleuth-sleuth-log] to INFO
10:32:44,494 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [sleuth-sleuth-log] to false
10:32:44,495 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SLEUTH-INFO] to Logger[sleuth-sleuth-log]
10:32:44,497 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:32:44,498 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination sleuth.com:4510: connection established.
10:32:44,501 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@36f0f1be - Registering current configuration as safe fallback point
10:32:44,494 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sleuth-sleuth-log] to INFO
10:32:44,494 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [sleuth-sleuth-log] to false
10:32:44,495 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SLEUTH-INFO] to Logger[sleuth-sleuth-log]
10:32:44,497 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:32:44,498 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination sleuth.com:4510: connection established.
10:32:44,501 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@36f0f1be - Registering current configuration as safe fallback point
10:32:44,509 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@75f9eccc - URL [jar:file:/data/sleuth-agent/reporter/sleuth-agent-reporter-flume.jar!/logback.xml] is not of type file
10:32:44,515 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [net.logstash.logback.appender.LogstashTcpSocketAppender]
10:32:44,515 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SLEUTH-INFO]
10:32:44,525 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [sleuth-sleuth-log] to INFO
10:32:44,525 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [sleuth-sleuth-log] to false
10:32:44,525 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SLEUTH-INFO] to Logger[sleuth-sleuth-log]
10:32:44,525 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
10:32:44,526 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5d47c63f - Registering current configuration as safe fallback point
10:32:44,526 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination sleuth.com:4510: connection established.
...
10:32:54,527 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination sleuth.com:4510: destination terminated the connection. Reconnecting.
10:32:54,529 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination sleuth.com:4510: Waiting 19998ms before attempting reconnection.
...
10:33:14,532 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination sleuth.com:4510: connection established.
10:33:24,532 |-INFO in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination sleuth.com:4510: destination terminated the connection. Reconnecting.
10:33:24,532 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[SLEUTH-INFO] - Log destination sleuth.com:4510: Waiting 19995ms before attempting reconnection.
I can't see what's wrong in the message.
When I modify source ,I find ReaderCallable.class will thirow SocketTimeoutException here in version 6.4.

       private class ReaderCallable implements Callable<Void> {
      
        private final InputStream inputStream;
        
        public ReaderCallable(InputStream inputStream) {
            super();
            this.inputStream = inputStream;
        }
        
        @Override
        public Void call() throws Exception {
            updateCurrentThreadName();
            try {
                while (true) {
                    try {
                        if (inputStream.read() == -1) {
                            /*
                             * End of stream reached, so we're done.
                             */
                            return null;
                        }
                    } catch (SocketTimeoutException e) {
                        /*
                         * ignore, and try again
                         */
                    } catch (Exception e) {
                        /*
                         * Something else bad happened, so we're done.
                         */
                        throw e;
                    }
                }
            } finally {
            }
        }
    }

I really don't know why.
Looking forward to answering.

**Comment by philsttr** [comment]
If a SocketTimeoutException occurs, the ReaderCallable will [continue to loop, since SocketTimeoutExceptions are ignored](https://github.com/logstash/logstash-logback-encoder/blob/ab1ddcb6ce6aae784f8bc4d2638b3e373bb36b16/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L442-L445).  There must be [some other exception occurring](https://github.com/logstash/logstash-logback-encoder/blob/ab1ddcb6ce6aae784f8bc4d2638b3e373bb36b16/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L446-L450) OR the [end of the stream is reached](https://github.com/logstash/logstash-logback-encoder/blob/ab1ddcb6ce6aae784f8bc4d2638b3e373bb36b16/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L436-L441).

**Comment by AngryMills** [comment]
> If a SocketTimeoutException occurs, the ReaderCallable will [continue to loop, since SocketTimeoutExceptions are ignored](https://github.com/logstash/logstash-logback-encoder/blob/ab1ddcb6ce6aae784f8bc4d2638b3e373bb36b16/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L442-L445). There must be [some other exception occurring](https://github.com/logstash/logstash-logback-encoder/blob/ab1ddcb6ce6aae784f8bc4d2638b3e373bb36b16/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L446-L450) OR the [end of the stream is reached](https://github.com/logstash/logstash-logback-encoder/blob/ab1ddcb6ce6aae784f8bc4d2638b3e373bb36b16/src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java#L436-L441).
Thanks for answering.
I will try to find out why this happens in different version
