### ISSUE TITLE
No log produced when including <uuid/>

### ISSUE THREAD

**Issue by dcerbino** [logstash/logstash-logback-encoder#453]
**Describe the bug**
everitiing work well unless I add uuid inside providers in LoggingEventCompositeJsonEncoder

**To Reproduce**
1. Use this 
[logback-spring.xml.zip](https://github.com/logstash/logstash-logback-encoder/files/5683954/logback-spring.xml.zip)

2. uncomment uuid line 55
3. See unexpected output

20:40:23,722 |-INFO in ch.qos.logback.classic.joran.action.ContextNameAction - Setting logger context name as [D-C-P-T]
20:40:23,724 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
20:40:23,724 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
20:40:23,744 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventJsonProviders] for [providers] property
20:40:23,750 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.SequenceJsonProvider] for [sequence] property
20:40:23,751 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.LogstashVersionJsonProvider] for [version] property
20:40:23,751 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.ContextNameJsonProvider] for [contextName] property
20:40:23,763 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider] for [timestamp] property
20:40:23,765 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggerNameJsonProvider] for [loggerName] property
20:40:23,766 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LogLevelJsonProvider] for [logLevel] property
20:40:23,766 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.CallerDataJsonProvider] for [callerData] property
20:40:23,767 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.ThreadNameJsonProvider] for [threadName] property
20:40:23,767 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.MdcJsonProvider] for [mdc] property
20:40:23,768 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.ArgumentsJsonProvider] for [arguments] property
20:40:23,769 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.StackTraceJsonProvider] for [stackTrace] property
20:40:23,774 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.StackHashJsonProvider] for [stackHash] property
20:40:23,775 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.MessageJsonProvider] for [message] property
20:40:23,803 |-WARN in Logger[org.springframework.boot.diagnostics.FailureAnalyzers] - No appenders present in context [D-C-P-T] for logger [org.springframework.boot.diagnostics.FailureAnalyzers].

**Expected behavior**
Normal log in json format.

* what output did you expect
"id": "(uuid)" on each event

**Additional context**
I'using Spring boot 2.4.0
* logstash-logback-encoder 6.5
* logback 1.2.3
* jackson 2.11.3
* java 11

**Comment by philsttr** [comment]
When I tried your configuration, the output showed the `uuid` field correctly in the json output.

Ensure you have the following dependency on your classpath:

[`com.fasterxml.uuid:java-uuid-generator`](https://mvnrepository.com/artifact/com.fasterxml.uuid/java-uuid-generator/4.0.1)

**Comment by dcerbino** [comment]
Thank @philsttr Not it works. 
The question is why you do not declare it under your dependencies?

**Comment by philsttr** [comment]
Great!

It's an [optional dependency](https://github.com/logstash/logstash-logback-encoder/blob/a3980403a9269b5fdcfd0381d96034bb154fa850/pom.xml#L173-L181) since the only thing that needs it is the uuid provider, which is not used by many people.  This keeps the logstash-logback-encoder dependency tree lean for users who do not use the uuid provider.

I updated the readme to mention the dependency.
