### ISSUE TITLE
LoggingEventAsyncDisruptorAppender should flush appenders implementing Flushable at end of a batch

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#454]
Similar to #346, it would be nice if `LoggingEventAsyncDisruptorAppender`also flushes appenders implementing `java.io.Flushable` at the end of a batch.

I came across this issue because we have some custom appenders not extending OutputStreamAppender that would benefit from an explicit flush as well... What do you think ?

**Comment by philsttr** [comment]
Seems reasonable to me.  Would you be willing to submit a PR?

**Comment by philsttr** [comment]
Closed by #457
