### ISSUE TITLE
Possible NullPointerException in DelegatingAsyncDisruptorAppender when flushing appenders

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#455]
The DelegatingAsyncDisruptorAppender may throw a NullPointerException at line https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/appender/DelegatingAsyncDisruptorAppender.java#L69 in the appender's output stream is `null`. 

This may appear very odd, but appenders like the RollingFileAppender may have a `null` output stream during rollover or even after if it failed to rotate the underlying file... I'm pretty sure the FileAppender will throw an exception before the DelegatingAsyncDisruptorAppender had a chance to flush at the end of the batch - so there is no point in checking for a null output stream. At least not until the FileAppender is "fixed" and can handle the null case gracefully...

**Comment by philsttr** [comment]
> so there is no point in checking for a null output stream

So you're saying don't check for a null outputstream in DelegatingAsyncDisruptorAppender?  What would the fix be then?

**Comment by brenuart** [comment]
That's not what I meant... I should have say "... _it **seems** there is no point in checking for a null output stream because it is likely an exception would be thrown earlier anyway_...

The `OutputStreamAppender#getOutputStream()` doesn't say anything about whether it may or not return a null output stream. IMHO it would be safer to check for null anyway.

My example around the RollingFileAppender is from experience. The output stream can be null for a very short time during rollover (fair enough) - but it can stay null for longer when it fails to roll. In this case the appender is usually broken and won't be able to recover by itself.

Sorry for not being clear the first time :-(

**Comment by philsttr** [comment]
Closed by #457
