### ISSUE TITLE
#tryJson{...} breaks actual JSON message

### ISSUE THREAD

**Issue by didien** [logstash/logstash-logback-encoder#480]
**Describe the bug**
When the tryJson operation is used, JSON quotes are escaped, which breaks the object.

**To Reproduce**
1. Use this `logback.xml` configuration...
```
        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <pattern>
                    <pattern>
                        {
                            "message": "#tryJson{%message}"
                        }
                    </pattern>
                </pattern>
            </providers>
        </encoder>
```
2. Execute this logger statement 
`logger.info("this is a test");`
`logger.info("{\"type\":\"example\",\"msg\":\"example of json message with type\"}");`
3. See error, or unexpected output
```
17:52:36.175 [main] INFO  xxx.AppenderTest - {"type":"example","msg":"example of json message with type"}
{
  "message" : "{\"type\":\"example\",\"msg\":\"example of json message with type\"}"
}
17:52:36.181 [main] INFO  xxx.AppenderTest - this is a test
{
  "message" : "this is a test"
}
```
**Expected behavior**
I'm expecting tryJson to return a non escaped JSON object when it's one, like asJson does.
```
17:54:09.345 [main] INFO  xxx.AppenderTest - {"type":"example","msg":"example of json message with type"}
{
  "message" : {
    "type" : "example",
    "msg" : "example of json message with type"
  }
}
17:54:09.354 [main] INFO  xxx.AppenderTest - this is a test
{
  "message" : "this is a test"
}
```

**Additional context**
* logstash-logback-encoder 6.6
* logback 1.2.3
* jackson 2.2.3
* java 1.7

**Comment by philsttr** [comment]
You need to use a more recent version of jackson.   logstash-logback-encoder 6.6 was built and tested with jackson 2.12.0.  

When I tried your encoder configuration and logger statements with:
* logstash-logback-encoder 6.6
* logback 1.2.3
* jackson 2.2.3
* java 11

I was able to reproduce the output you received.

When I tried your encoder configuration and logger statements with:
* logstash-logback-encoder 6.6
* logback 1.2.3
* jackson 2.12.0
* java 11

I received the expected output:

```
{"message":"this is a test"}
{"message":{"type":"example","msg":"example of json message with type"}}
```
