### ISSUE TITLE
MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O

### ISSUE THREAD

**Issue by virengujariya** [logstash/logstash-logback-encoder#500]
**Describe the bug**
```
Execution failed for task ':app:dexBuilderDebug'.
> Could not resolve all files for configuration ':app:detachedConfiguration2'.
   > Failed to transform jetified-logstash-logback-encoder-6.6.jar to match attributes {artifactType=ext-dex-dexBuilderDebug, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for DexingExternalLibArtifactTransform: /Users/virengujariya/.gradle/caches/transforms-2/files-2.1/17b5c51844cfd8c22c76c0a3eaa88ecf/jetified-logstash-logback-encoder-6.6.jar.
         > Error while dexing.
```

**To Reproduce**
1. Add logstash as dependency to app's `build.gradle` file in Android project
`implementation "net.logstash.logback:logstash-logback-encoder:6.6"`
Make sure following options are set
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
```
2. Sync your gradle, clean and build your project
3. See error `com.android.tools.r8.a: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)`

**Expected behavior**
Android project should build successfully

* what output did you expect
Android project should build successfully

**Additional context**
Android project's version setup is as per following
```
compileSdkVersion 30
defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
}
```

* logstash-logback-encoder version `6.6`
* logback version `1.2.3`
* java version `1.8`

**Comment by philsttr** [comment]
logstash-logback-encoder does not use MethodHandle

https://github.com/logstash/logstash-logback-encoder/search?q=MethodHandle

I'd suggest trying to find exactly what is using MethodHandle, and filing an issue in that library.

**Comment by mdietrichstein** [comment]
`logstash-logback-encoder` contains a (shaded) version of `com.lmax.disruptor:3.4.4` which in turn relies on some reflection methods: https://github.com/LMAX-Exchange/disruptor/blob/3.4.4/src/main/java/com/lmax/disruptor/util/ThreadHints.java

As a quick fix, I forked the project and removed the dependency on lmax. This meant that I also had to remove all appenders. This works for me since I only care about the encoders.

If you are in the same situation, you can add my fork via jitpack: https://github.com/mdietrichstein/logstash-logback-encoder

**Comment by virengujariya** [comment]
> `logstash-logback-encoder` contains a (shaded) version of `com.lmax.disruptor:3.4.4` which in turn relies on some reflection methods: https://github.com/LMAX-Exchange/disruptor/blob/3.4.4/src/main/java/com/lmax/disruptor/util/ThreadHints.java
> 
> As a quick fix, I forked the project and removed the dependency on lmax. This meant that I also had to remove all appenders. This works for me since I only care about the encoders.
> 
> If you are in the same situation, you can add my fork via jitpack: https://github.com/mdietrichstein/logstash-logback-encoder

Thanks, I didn't end up using this lib in the end :)
