### ISSUE TITLE
Missing "," JSON object separator always produce an invalid json

### ISSUE THREAD

**Issue by sebasacuna** [logstash/logstash-logback-encoder#502]
**Describe the bug**
When I try to generate the json file it is an ivalid json because do not have the comma for separate the json objects

**To Reproduce**
This is the logback.xml

`<configuration>

    <property name="LOG_PATH" value="log-file"/>
    <property name="HOME_LOG" value="logfile"/>

    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>
                %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(%M){cyan} %clr(:%X{Execution-Time} %X{TRANSACTION}){faint} %m%n%wEx
            </Pattern>
        </layout>
    </appender>

    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
        <file>${HOME_LOG}</file>
        <append>true</append>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%15.15t] %-40.40logger{39} :%X{Execution-Time}  %X{TRANSACTION} %m%n%wEx</pattern>
        </encoder>
    </appender>

    <appender name="jsonAppender" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <File>${LOG_PATH}</File>

        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <jsonGeneratorDecorator class="net.logstash.logback.decorate.PrettyPrintingJsonGeneratorDecorator"/>
            <providers>
                <timestamp>
                    <fieldName>Timestamp</fieldName>
                </timestamp>
                <pattern>
                    
                    <omitEmptyFields>false</omitEmptyFields>
                    <pattern>
                        {
                        "Consumer-Enterprise-Code": "XX",
                        "Consumer-Country-Code": "XX",
                        "Channel-Name": "%mdc{EMPTY}",
                        "Consumer-Sys-Code": "%mdc{EMPTY}",
                        "Consumer-UserId-Code": "%mdc{EMPTY}",
                        "Trace-Process-Id": "%mdc{TRANSACTION}",
                        "Trace-Event-Id": "%mdc{EMPTY}",
                        "Trace-Source-Id": "%mdc{EMPTY}",
                        "App-Code": "MS Send SMS",
                        "Execution-Time":"%mdc{Execution-Time}",
                        "Level":"%level",
                        "thread": "%thread",
                        "traceId": "%mdc{TRANSACTION}",
                        "Message": "#tryJson{%message}",
                        "Status":"%mdc{STATUS}"
                        }
                    </pattern>
                </pattern>
                <mdc/>
                <arguments/>
            </providers>

        </encoder>
        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <maxIndex>1</maxIndex>
            <fileNamePattern>${LOG_PATH}.%i</fileNamePattern>
        </rollingPolicy>
        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
        </triggeringPolicy>
    </appender>

    <logger name="jsonLogger" additivity="false" level="DEBUG">
        <appender-ref ref="jsonAppender"/>
    </logger>

    <root level="INFO">
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="FILE"/>
    </root>

</configuration>`

this produce the next json

```
{
  "Timestamp" : "2021-02-19T05:17:48.010-03:00",
  "Consumer-Enterprise-Code" : "BB",
  "Consumer-Country-Code" : "CC",
  "Channel-Name" : "",
  "Consumer-Sys-Code" : "",
  "Consumer-UserId-Code" : "",
  "Trace-Process-Id" : "123123",
  "Trace-Event-Id" : "",
  "Trace-Source-Id" : "",
  "App-Code" : "MS X XX",
  "Execution-Time" : "",
  "Level" : "INFO",
  "thread" : "http-nio-9080-exec-5",
  "traceId" : "123123",
  "Message" : {
    "msg" : "STEP GENERATE BEARER TOKEN: "
  },
  "Status" : "",
  "MSG" : "STEP GENERATE BEARER TOKEN: =",
  "TRANSACTION" : "123123"
}
{
  "Timestamp" : "2021-02-19T05:17:48.010-03:00",
  "Consumer-Enterprise-Code" : "BB",
  "Consumer-Country-Code" : "CC",
  "Channel-Name" : "",
  "Consumer-Sys-Code" : "",
  "Consumer-UserId-Code" : "",
  "Trace-Process-Id" : "123123",
  "Trace-Event-Id" : "",
  "Trace-Source-Id" : "",
  "App-Code" : "MS X XX",
  "Execution-Time" : "",
  "Level" : "INFO",
  "thread" : "http-nio-9080-exec-5",
  "traceId" : "123123",
  "Message" : {
    "msg" : "STEP GENERATE BEARER TOKEN: "
  },
  "Status" : "",
  "MSG" : "STEP GENERATE BEARER TOKEN: =",
  "TRANSACTION" : "123123"
}
```

If you can see I expect to see the missing comma ","

```
{
  "Timestamp" : "2021-02-19T05:17:48.010-03:00",
  "Consumer-Enterprise-Code" : "BB",
  "Consumer-Country-Code" : "CC",
  "Channel-Name" : "",
  "Consumer-Sys-Code" : "",
  "Consumer-UserId-Code" : "",
  "Trace-Process-Id" : "123123",
  "Trace-Event-Id" : "",
  "Trace-Source-Id" : "",
  "App-Code" : "MS X XX",
  "Execution-Time" : "",
  "Level" : "INFO",
  "thread" : "http-nio-9080-exec-5",
  "traceId" : "123123",
  "Message" : {
    "msg" : "STEP GENERATE BEARER TOKEN: "
  },
  "Status" : "",
  "MSG" : "STEP GENERATE BEARER TOKEN: =",
  "TRANSACTION" : "123123"
} , <------------  THE MISSING COMMA PRODUCE AN INVALID JSON
{
  "Timestamp" : "2021-02-19T05:17:48.010-03:00",
  "Consumer-Enterprise-Code" : "BB",
  "Consumer-Country-Code" : "CC",
  "Channel-Name" : "",
  "Consumer-Sys-Code" : "",
  "Consumer-UserId-Code" : "",
  "Trace-Process-Id" : "123123",
  "Trace-Event-Id" : "",
  "Trace-Source-Id" : "",
  "App-Code" : "MS X XX",
  "Execution-Time" : "",
  "Level" : "INFO",
  "thread" : "http-nio-9080-exec-5",
  "traceId" : "123123",
  "Message" : {
    "msg" : "STEP GENERATE BEARER TOKEN: "
  },
  "Status" : "",
  "MSG" : "STEP GENERATE BEARER TOKEN: =",
  "TRANSACTION" : "123123"
}
```

logstash-logback-encoder version 6.6
logback version 6.6

java version 1.8

**Comment by philsttr** [comment]
Note that adding a comma between json objects does not make it valid json, since there is no leading [ and a trailing ] for an array.

Having said that, you can add comma after each object by [configuring a suffix or line separator](https://github.com/logstash/logstash-logback-encoder#prefixsuffixseparator)

**Comment by sebasacuna** [comment]
Thanks for the respond @philsttr when a tried to add the prefix have the follow error , it is the same xml with this

<configuration>

    <property name="LOG_PATH" value="log-file"/>
    <property name="HOME_LOG" value="logfile"/>

    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <layout class="ch.qos.logback.classic.PatternLayout">
            <Pattern>
                %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(%M){cyan} %clr(:%X{Execution-Time} %X{TRANSACTION}){faint} %m%n%wEx
            </Pattern>
        </layout>
    </appender>

    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
        <file>${HOME_LOG}</file>
        <append>true</append>
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%15.15t] %-40.40logger{39} :%X{Execution-Time}  %X{TRANSACTION} %m%n%wEx</pattern>
        </encoder>
    </appender>

    <conversionRule conversionWord="syslogStart" converterClass="ch.qos.logback.classic.pattern.SyslogStartConverter" />

    <appender name="tcp" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
        <remoteHost>127.0.0.1</remoteHost>
        <port>9060</port>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder">
            <prefix class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                <layout class="ch.qos.logback.classic.PatternLayout">
                    <pattern>@cee:</pattern>
                </layout>
            </prefix>
        </encoder>
    </appender>


    <appender name="jsonAppender" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <File>${LOG_PATH}</File>

        <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <jsonGeneratorDecorator class="net.logstash.logback.decorate.PrettyPrintingJsonGeneratorDecorator"/>
            <providers>
                <timestamp>
                    <fieldName>Timestamp</fieldName>
                </timestamp>
                <pattern>
                    
                    <omitEmptyFields>false</omitEmptyFields>
                    <pattern>
                        {
                        "Example": "test",
                        "Example2": "test2"
                        }
                    </pattern>
                </pattern>
            </providers>

        </encoder>
        <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
            <maxIndex>1</maxIndex>
            <fileNamePattern>${LOG_PATH}.%i</fileNamePattern>
        </rollingPolicy>
        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
        </triggeringPolicy>
    </appender>

    <logger name="jsonLogger" additivity="false" level="DEBUG">
        <appender-ref ref="jsonAppender"/>
    </logger>

    <root level="INFO">
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="FILE"/>
    </root>

</configuration>

```
Exception in thread "main" java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@30:79 - no applicable action for [prefix], current ElementPath  is [[configuration][appender][encoder][prefix]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@31:70 - no applicable action for [layout], current ElementPath  is [[configuration][appender][encoder][prefix][layout]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@32:30 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][prefix][layout][pattern]]
ERROR in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Could not create component [encoder] of type [net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder] java.lang.ClassNotFoundException: net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder
ERROR in ch.qos.logback.core.joran.spi.Interpreter@43:113 - no applicable action for [jsonGeneratorDecorator], current ElementPath  is [[configuration][appender][encoder][jsonGeneratorDecorator]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@44:24 - no applicable action for [providers], current ElementPath  is [[configuration][appender][encoder][providers]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@45:28 - no applicable action for [timestamp], current ElementPath  is [[configuration][appender][encoder][providers][timestamp]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@46:32 - no applicable action for [fieldName], current ElementPath  is [[configuration][appender][encoder][providers][timestamp][fieldName]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@48:26 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][providers][pattern]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@50:38 - no applicable action for [omitEmptyFields], current ElementPath  is [[configuration][appender][encoder][providers][pattern][omitEmptyFields]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@51:30 - no applicable action for [pattern], current ElementPath  is [[configuration][appender][encoder][providers][pattern][pattern]]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[jsonAppender] - No encoder set for the appender named "jsonAppender".
```

**Comment by philsttr** [comment]
Your prefix configuration worked for me.

This error in the output you provided indicates that something might not be correct in your classpath:

```
java.lang.ClassNotFoundException: net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder
```

Double check to ensure you have logstash-logback-encoder, logback-classic, and logback-core on you classpath.  More details [here](https://github.com/logstash/logstash-logback-encoder#including-it-in-your-project)
