### ISSUE TITLE
Documentation does not mention StackHashJsonProvider

### ISSUE THREAD

**Issue by will-sargent-eero** [logstash/logstash-logback-encoder#506]
**Describe the bug**

StackHashJsonProvider is mentioned in the stack-hash document:

https://github.com/logstash/logstash-logback-encoder/blob/master/stack-hash.md#stackhashjsonprovider

but there is ~no~minimal (the "more info") reference from the main documentation to stack-hash.md:

https://github.com/logstash/logstash-logback-encoder#customizing-stack-traces

So a user is not going to know that it's even possible to represent a stack hash as JSON by looking at the main README as there is no reference to it.

**Comment by philsttr** [comment]
There's a link to the stack hash document in

* [Customizing Stack Traces](https://github.com/logstash/logstash-logback-encoder#customizing-stack-traces)
* [Providers for LoggingEvents](https://github.com/logstash/logstash-logback-encoder#providers-for-loggingevents)

Where else would you recommend?

**Comment by will-sargent-eero** [comment]
The link to the stack hash documents are fine in and of themselves, it's more a question of providing a visible option in the documentation itself.

So in https://github.com/logstash/logstash-logback-encoder#customizing-stack-traces it should be

"Computing and inlining hexadecimal hashes for each exception stack using `inlineHash` or `stackHash` provider (more info)"
