### ISSUE TITLE
About dynamic refresh address implementation

### ISSUE THREAD

**Issue by SkyMoreStars** [logstash/logstash-logback-encoder#513]
<destination>${logStash}</destination>
I have a logstash address, which is constantly changing because it is deployed in AWS ECS, which is a task definition. If I want to dynamically refresh the access address, what should I do? I look forward to your reply! @philsttr

**Comment by SkyMoreStars** [comment]
`<destination>${logStash}</destination>`

**Comment by brenuart** [comment]
Destinations are DNS resolved at the time the appender is configured. This means that subsequent changes in the DNS name<->ip binding will not be discovered after the appender is started. This is definitely something we should address in future versions.
As for now, I'm afraid there is no built-in solution for your use case.
