### ISSUE TITLE
Support for Android?

### ISSUE THREAD

**Issue by Yurii-Liakhor** [logstash/logstash-logback-encoder#546]
Is any solution to run it from Android min-api 16?

**Comment by philsttr** [comment]
Hi @Yurii-Liakhor

I'm not familiar with Android development.  Would you consider contributing a PR to address the problems you encounter on Android?

**Comment by Yurii-Liakhor** [comment]
To do this, I would like to understand in which part of the library the error occurs.
All I know is that when assembling an application with this library, an error appears:
`com.android.tools.r8.a: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)`

**Comment by Yurii-Liakhor** [comment]
> Hi @Yurii-Liakhor
> 
> I'm not familiar with Android development. Would you consider contributing a PR to address the problems you encounter on Android?
To do this, I would like to understand in which part of the library the error occurs.
All I know is that when assembling an application with this library, an error appears:
`com.android.tools.r8.a: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)`

**Comment by philsttr** [comment]
See #500 .  It looks like the shaded lmax-disruptor dependency uses MethodHandle.  The disruptor is used for the appenders offered by logstash-logback-encoder, so it can't be removed.

Some options for you:

* File an issue with https://github.com/LMAX-Exchange/disruptor to remove its MethodHandle usage.  After it is removed there, and released, dependabot will automatically update logstash-logback-encoder to use the new version.
OR
* Use the fork of logstash-logback-encoder as mentioned [here](https://github.com/logstash/logstash-logback-encoder/issues/500#issuecomment-851862671).  (Note you will not be able to use the appenders.)
