### ISSUE TITLE
JsonParseException: Unrecognized token 

### ISSUE THREAD

**Issue by reyfren06** [logstash/logstash-logback-encoder#552]
Hello All, 

In my project we are using the 5.1 version of logstash-logback-encoder and when we receive a high volume of requests concurrently, in our monitoring tool (dynatrace) we see the next error: 

   Unrecognized token 'Consumer': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: (String)"Consumer input message to the time *****T***** - queue: authorisationRequest.

Unrecognized token 'offlinetxn': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: (String)"offlinetxn flag is false"; line: 1, column: 11]

For these two case the original trace is : 

log.info("Consumer input message to the time {} - queue: {} ", timeStart, queueName);

log.info("offlinetxn flag is false");

we don't understand why this error happens and how we can fix it.  For our next version we have upgraded the version of net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder to 6.6

My logback file is simple: 

<encoder
                class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
            <providers>
                <timestamp />
                <pattern>
                    <pattern>
                        {
                        "level": "%level",
                        "thread": "%thread",
                        "logger": "%logger",
                        "traceId": "%X{traceId:-}",
                        "spanId": "%X{spanId:-}",
                        "message":"%message",
                        "json_message":
                        "#asJson{%message}",
                        "exception": "%ex"

Could you help me with this issue. 

Thank you in advance.

**Comment by brenuart** [comment]
`#asJson{%message}` expects the log message to be in JSON format... which is not the case in your example.
A valid example from the doc is:
```
LOGGER.info("{\"type\":\"example\",\"msg\":\"example of json message with type\"}");
```

This will produce something like:
```
{
  "level": "INFO",
  ...
  "message":  "{\"type\":\"example\",\"msg\":\"example of json message with type\"}",
  "json_message": {
    "type": "example",
    "msg": "example of json message with type"
  }
}
```

**Comment by brenuart** [comment]
@reyfren06 Are you ok with this answer or do you need further assistance?

**Comment by reyfren06** [comment]
Only one question more. How can I fix this issue directly from the logback file without change the jackson properties, so I can avoid or skip those errors if I want to make logging without to be json string.

**Comment by brenuart** [comment]
I should be enough to remove the line `"#asJson{%message}"` from the config file.

**Comment by reyfren06** [comment]
I don't want to do that, because I want to convert to Json format all object or messages without converted it previously. I was referring to something like this :

DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES

Or other properties for it doesn't get any failure when the library tries to convert to json format.

**Comment by brenuart** [comment]
Honestly I don't understand your use case that much...

`#asJson{}` should be used only when the `message` part of the log event contains a _valid_ JSON - not a plain random string. The only option that comes to my mind is to use something like the StructuredArguments to hold the object you'd like to add to the final JSON. Something like this:

```
Foo foo  = new Foo();
logger.info("log message {}", StructuredArguments.value("foo", foo));
```

This will add the _foo_ properties to the JSON output in addition to the other properties you configured in the logback configuration file (don't forget to remove the `#toJson{}` line tho).
Check the documentation for similar alternatives around the same theme...
