### ISSUE TITLE
"dependency-reduced-pom.xml" is generated in the root of the project instead of "/target"

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#555]
The Maven Shade plugin is configured to produce a _dependency reduced_ POM where dependencies to shaded artefacts are removed. This _reduced_ POM is created in the root of the project structure instead of in the /target directory where build artefacts usually go. In general it is "bad practice" for the build to modify files outside of the build directory...

Proposition is to configure the shade plugin to save the reduced pom in the project build directory.

Note: as it is atm, the reduced pom won't be removed by a `mvn clean`...

**Comment by brenuart** [comment]
Hmmm.. storing the reduced pom other than in the project root is not a good idea. As per the plugin documentation:
> setting a value for this parameter with a directory other than ${basedir} will change the value of ${basedir} for all executions that come after the shade execution. This is often not what you want. This is considered an open issue with this plugin.

And indeed, the checkstyle plugin that currently comes after the shade plugin is now unable to find the rules file located a `src/checkstyle/checkstyle.xml` (resolved relative to ${basedir} which is now elsewhere...

Probably better to keep things as they are atm (reduced pom in the project root). Maybe we could just configure the clean plugin to remove this file as well...

**Comment by philsttr** [comment]
+1 to configuring the clean plugin
