### ISSUE TITLE
Add import order in checkstyle rules

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#556]
It would be nice to have checkstyle enforce the ordering of import statements as well. People are using different IDEs with different defaults. We we don't impose a particular order, imports will be constantly reorder with every commit...

Here is a first proposition:

1. static imports first
2. -blank line-
2. `java.*`
3. -blank line-
4. `javax.*`
5. -blank line-
6. `net.logstash.*`
7. -blank line-
8. `org.*`
9. -blank line-
10. anything else

Each group is sorted alphabetically.

Example:
```
import static java.util.Objects.requireNonNull;

import java.util.ArrayList;
import java.util.List;

import net.logstash.logback.appender.listener.AppenderListener;
import net.logstash.logback.status.LevelFilteringStatusListener;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.lmax.disruptor.EventFactory;
import com.lmax.disruptor.EventHandler;

import ch.qos.logback.access.spi.IAccessEvent;
import ch.qos.logback.classic.AsyncAppender;
```

Corresponding checkstyle rule:

```
        <module name="ImportOrder">
            <property name="groups" value="/^java\./,javax,net.logstash,org,com"/>
            <property name="ordered" value="true"/>
            <property name="separated" value="true"/>
            <property name="option" value="above"/>
            <property name="sortStaticImportsAlphabetically" value="true"/>
        </module>
```

**Comment by philsttr** [comment]
I personally like less groups.

```
static imports first
-blank line-
java.*
-blank line-
anything else
```

However, running that config means 179 checkstyle errors in 92 files.

Running with your proposal is 114 errors in 78 files, which means less code churn.  So, I'm good with your proposal, although (minor comment) I think all the groups can use prefixes instead of regexes `value="java.,javax.,net.logstash,org,com"`

**Comment by brenuart** [comment]
No matter how many files are affected - more than 50% will have to be changed anyway... 
I'm also in favour of less groups but like the idea of having a separate group with `net.logstash` packages. 

What about this:
```
static imports first
-blank line-
java.*
-blank line-
net.logstash.*
-blank line-
anything else
```

**Comment by philsttr** [comment]
> more than 50% will have to be changed anyway

Good point. 

> What about this:

Sounds good to me.  Let's go with that.
