### ISSUE TITLE
Usage on application server

### ISSUE THREAD

**Issue by senty** [logstash/logstash-logback-encoder#61]
Hi,

did you tried this awesome encoded on application server. I have today tried it on JBOSS EAP 6.1 and no success -> logback coul not be configured due to jboss exception : ClassNotFound on used appender.

tried to add jar file with logstasdh encoder :
- to war file
- to jboss modules

Is possible that there is conflict with inner jboss logging system ?

**Comment by neilprosser** [comment]
I'm not a JBoss user so I've not tried including it. Are you able to post the stack-trace you get when you start up, it might help us diagnose the issue.

**Comment by philsttr** [comment]
Hi @senty,

logstash-logback-encoder requires the following jars to be on the runtime classpath:

    jackson-databind / jackson-core / jackson-annotations
    logback-classic / logback-core / logback-access (if using access logging)
    slf4j-api

You will get `ClassNotFoundException`s if they are not on the classpath.

Closing this issue.

**Comment by senty** [comment]
Sorry for delayed answer. Tested now with all dependencies that you mentioned & latest version encoder -> everything work perfectly
thank you very much
