### ISSUE TITLE
Mask value of stacktrace does not work as expected

### ISSUE THREAD

**Issue by nilsmagnus** [logstash/logstash-logback-encoder#641]
**Describe the bug**
I expected the valueMask to mask the string in the stacktrace as well as the message. It does not.

**To Reproduce**

1. Use this `logback.xml` configuration
```
<configuration>
  <appender name="json" class="ch.qos.logback.core.ConsoleAppender">
    <encoder class="net.logstash.logback.encoder.LogstashEncoder">
      <jsonGeneratorDecorator class="net.logstash.logback.mask.MaskingJsonGeneratorDecorator">
        <!---  apikey=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx1234f)  -->

        <valueMask>
          <value>(.*apikey=)(.{36})(.*)</value>
          <mask>$1***$3</mask>
        </valueMask>
      </jsonGeneratorDecorator>

    </encoder>
  </appender>

  <root level="info">
    <appender-ref ref="json" />
  </root>
</configuration>
```

2. Execute this logger statement `log.error("message key is apikey=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx1234f", new RuntimeException("stacktrace key is apikey=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx1234f"));`
3. The output for the stacktrace is not masked, but the message is:
```
{"@timestamp":"2021-09-10T12:31:27.400+02:00","@version":"1","message":"message key is apikey=***","logger_name":"com.example.Main","thread_name":"main","level":"ERROR","level_value":40000,"stack_trace":"java.lang.RuntimeException: stacktrace key is apikey=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx1234f\n\tat com.example.MainKt.main(Main.kt:45)\n\tat com.example.MainKt.main(Main.kt)\n"}
```

**Expected behavior**
The output for the `stack_trace` should not contain the apikey.

**Additional context**

* logstash-logback-encoder 6.6
* logback 1.2.5
* jackson 2.12.2
* java 15

**Comment by brenuart** [comment]
Hi Nils. Thanks for the report.

I think your issue is related to https://github.com/logstash/logstash-logback-encoder/issues/400, and the comment https://github.com/logstash/logstash-logback-encoder/issues/400#issuecomment-868872288 in particular.

The good news is I could reproduce your issue following your instructions with 6.6 but *not* with the current development version (7.0-SNAPSHOT) anymore. In the meantime I'm afraid your only option is to write a custom `ValueMasker` yourself like this:

```
public class StackTraceValueMasker implements ValueMasker {
    @Override
    public Object mask(JsonStreamContext context, Object value) {
        if (context.getCurrentName().equals("stack_trace")) {
            return <masked value>;
        }
        else {
            return value;
        }
    }
}
```

and register it in your configuration as follows:

```
<jsonGeneratorDecorator class="net.logstash.logback.mask.MaskingJsonGeneratorDecorator">
    ...
    <valueMasker class="....StackTraceValueMasker"/>
</jsonGeneratorDecorator>
```

**Comment by nilsmagnus** [comment]
Ok, that solution is ok for me. Closing this issue and waiting for the 7.0 release :+1:

**Comment by brenuart** [comment]
@nilsmagnus 7.0 shouldn't be too long now... stay tuned ;-)
