### ISSUE TITLE
Output @timestamp is using local timezone offset instead of UTC.

### ISSUE THREAD

**Issue by talvey** [logstash/logstash-logback-encoder#66]
This is a fairly minor issue, but I'd like the generated @timestamp field to use UTC (zero offset).

The easiest approach would be to simply change the LogstashAbstractFormatter class as follows

**From**
```java```
protected static final FastDateFormat ISO_DATETIME_TIME_ZONE_FORMAT_WITH_MILLIS = FastDateFormat.getInstance("yyyy-MM-dd'T'HH:mm:ss.SSSZZ");
```
**To**
```java```
protected static final FastDateFormat ISO_DATETIME_TIME_ZONE_FORMAT_WITH_MILLIS = FastDateFormat.getInstance("yyyy-MM-dd'T'HH:mm:ss.SSSZZ", TimeZone.getTimeZone("UTC"));
```

Alternatively, you could provide a "useUTCOffset" flag or something similar in the ```LogstashFormatter``` and ```LogstashLayout``` and allow the user to choose similar to the  includeMdc flag.  Thoughts?

I'd be happy to submit a pull request for either solution.

**Comment by philsttr** [comment]
Implemented ability to specify timezone.

See [here](https://github.com/logstash/logstash-logback-encoder#customizing-timezone)

**Comment by talvey** [comment]
Perfect!  Thank you for the quick support.
