### ISSUE TITLE
PatternJsonProvider: provide a #asBoolean operation

### ISSUE THREAD

**Issue by brenuart** [logstash/logstash-logback-encoder#693]
It may be handy to provide a `#asBoolean` operation to convert the input into a JSON boolean value.
Conversion rule would be:
- case insensitive
- `"true"`, `"1"`, `"yes"` and `"y"` are converted to Boolean.TRUE
- `null` is converted to `null`
- anything else is converted to Boolean.FALSE

**Comment by brenuart** [comment]
@philsttr Your opinion about the conversion rules?

**Comment by philsttr** [comment]
Seems fine.

I believe `#asJson{true}`  `#asJson{false}` (or something that evaluates to `true` or `false` within the braces) currently convert to a JSON boolean value.  But having a boolean-specific conversion for more possible values seems good.

**Comment by brenuart** [comment]
_Small note:_
Operations operate on the result of applying a PatternLayout to the argument between `{}`. A PatternLayout never returns null but an empty string when the input is empty (or missing). The `null` conversion rule is therefore not relevant...
Instead we should convert an empty string into a `null` result instead of FALSE to denote the absence of value.
