### ISSUE TITLE
Memory issue due to connection problems

### ISSUE THREAD

**Issue by AxelBe** [logstash/logstash-logback-encoder#70]
Hi,

we faced a serious memory problem with the ````LogstashTcpSocketAppender```` in connection with Logback classic. It occurs in case of connection problems to the Logstash server. The reason is the queue holding references of log events waiting to be delivered. The queue stores by default up to 10000 ````ILoggingEvent```` instances. These log events hold references to arguments passed via formatted messages like ````LOG.warn("Error processing {}", myBigObject);````. As you can imagine these argument objects can be some with real big objects trees linked. 

Besides the amount of memory that is blocked with these objects it is also a garbage collection issue, because there is no chance to clean up these hard referenced object trees. In our case the application crashed at 2000 items in the queue allocating 6 GB heap!

Another issue is that if these argument objects are mutable, holding them for later processing will create log messages that do not reflect the state of the input object any more!

I think passing such objects to the log events as a user is ok since it is compliant with the interface ````ILoggingEvent````, the appender is responsible to handle them with care. 

This issue is also a problem of the original Logback ````ch.qos.logback.core.net.SocketAppender````, I just want to make you aware of it!

My fix for us was to 
* encode events directly to byte arrays when they come in 
* introduce a socket timeout for sockets (I got the advice that this is always very important because there are situations where the socket really stucks and will never come back)

Below I attached my patch of ````LogstashTcpSocketAppender```` of (maven) release version v 3.5.

Best regards,
Axel

````patch
Index: trunk/proj/src/main/java/net/logstash/logback/appender/LogstashTcpSocketAppender.java
===================================================================
diff -u -N -r8288 -r8290
--- trunk/proj/src/main/java/net/logstash/logback/appender/LogstashTcpSocketAppender.java	(.../LogstashTcpSocketAppender.java)	(revision 8288)
+++ trunk/proj/src/main/java/net/logstash/logback/appender/LogstashTcpSocketAppender.java	(.../LogstashTcpSocketAppender.java)	(revision 8290)
@@ -14,11 +14,13 @@
 package net.logstash.logback.appender;
 
 import java.io.BufferedOutputStream;
+import java.io.ByteArrayOutputStream;
 import java.io.IOException;
 import java.io.OutputStream;
 import java.net.ConnectException;
 import java.net.InetAddress;
 import java.net.Socket;
+import java.net.SocketTimeoutException;
 import java.net.UnknownHostException;
 import java.util.concurrent.BlockingQueue;
 import java.util.concurrent.ExecutionException;
@@ -34,7 +36,6 @@
 import ch.qos.logback.classic.net.SocketAppender;
 import ch.qos.logback.classic.spi.ILoggingEvent;
 import ch.qos.logback.core.AppenderBase;
-import ch.qos.logback.core.CoreConstants;
 import ch.qos.logback.core.encoder.Encoder;
 import ch.qos.logback.core.net.DefaultSocketConnector;
 import ch.qos.logback.core.net.SocketConnector;
@@ -54,10 +55,16 @@
  * 
  * @author <a href="mailto:mirko.bernardoni@gmail.com">Mirko Bernardoni</a>
  * @since 11 Jun 2014 (creation date)
+ * 
+ * This is a patched version of the original in library  net.logstash.logback/logstash-logback-encoder/3.5. We faced a memory issue because the 
+ * blocking queue was holding (a large number of) object references in the parameters array of the LoggingEvent items in case of network problems.
+ * I implemented:
+ *   - serialization of the events directly to byte[] (free them for garbage collection)
+ *   - handling of socket timeout, this causes the fallback to the connection retry loop
  */
 public class LogstashTcpSocketAppender extends AppenderBase<ILoggingEvent>
         implements Runnable, SocketConnector.ExceptionHandler {
-    
+      
     private static final PreSerializationTransformer<ILoggingEvent> PST = new LoggingEventPreSerializationTransformer();
     
     /**
@@ -105,7 +112,7 @@
 
     private int queueSize = DEFAULT_QUEUE_SIZE;
     
-    private BlockingQueue<ILoggingEvent> queue;
+    private BlockingQueue<byte[]> queue;
     
     private String peerId;
     
@@ -211,11 +218,13 @@
         
         if (errorCount == 0) {
             encoder.start();
-            queue = new LinkedBlockingQueue<ILoggingEvent>(queueSize);
+            queue = new LinkedBlockingQueue<byte[]>(queueSize);
             peerId = "remote peer " + remoteHost + ":" + port + ": ";
             task = getContext().getExecutorService().submit(this);
             super.start();
         }
+        
+        addInfo("Started patched version of " + this.getClass());
     }
     
     /**
@@ -241,19 +250,31 @@
             return;
         
         try {
-            event.prepareForDeferredProcessing();
-            if (includeCallerData) {
-                event.getCallerData();
-            }
+            if (queue.remainingCapacity() > 0) {
+                event.prepareForDeferredProcessing();
+                if (includeCallerData) {
+                    event.getCallerData();
+                }
 
-            final boolean inserted = queue.offer(event,
-                    eventDelayLimit.getMilliseconds(), TimeUnit.MILLISECONDS);
-            if (!inserted) {
-                addInfo("Dropping event due to timeout limit of ["
-                        + eventDelayLimit + "] being exceeded");
+                // Serialize the event to bytes to make sure to not collect
+                // references to outdated classes in its internal parameters
+                // array
+                ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
+                encoderInit(outputStream);
+                this.encoder.doEncode(event);
+
+                final boolean inserted = queue.offer(outputStream.toByteArray(), eventDelayLimit.getMilliseconds(),
+                        TimeUnit.MILLISECONDS);
+                if (!inserted) {
+                    addInfo("Dropping event due to timeout limit of [" + eventDelayLimit + "] being exceeded");
+                }
+            } else {
+                addInfo("Dropping event due to full queue");
             }
         } catch (InterruptedException e) {
             addError("Interrupted while appending event to SocketAppender", e);
+        } catch (IOException e) {
+            addError("Error serializing the log event", e);
         }
     }
     
@@ -307,7 +328,7 @@
             return s;
         } catch (ExecutionException e) {
             return null;
-        }
+        } 
     }
     
     /**
@@ -320,26 +341,21 @@
         try {
             socket.setSoTimeout(acceptConnectionTimeout);
             outputStream = new BufferedOutputStream(socket.getOutputStream());
-            encoderInit(outputStream);
-            socket.setSoTimeout(0);
+
             addInfo(peerId + "connection established");
-            int counter = 0;
             while (true) {
-                ILoggingEvent event = queue.take();
-                this.encoder.doEncode(event);
+                byte[] event = queue.take();
+                outputStream.write(event);
                 outputStream.flush();
-                if (++counter >= CoreConstants.OOS_RESET_FREQUENCY) {
-                    // Failing to reset the object output stream every now and
-                    // then creates a serious memory leak.
-                    outputStream.flush();
-                    counter = 0;
-                }
             }
+        } catch (SocketTimeoutException ex) {
+            addWarn("Socket time out during event dispatch: " + ex);
         } catch (IOException ex) {
             addInfo(peerId + "connection failed: " + ex);
         } finally {
             if (outputStream != null) {
                 encoderClose(outputStream);
+                CloseUtil.closeQuietly(outputStream);
             }
             CloseUtil.closeQuietly(socket);
             socket = null;
@@ -467,7 +483,7 @@
      * @param acceptConnectionTimeout
      *            timeout value in milliseconds
      */
-    void setAcceptConnectionTimeout(int acceptConnectionTimeout) {
+    public void setAcceptConnectionTimeout(int acceptConnectionTimeout) {
         this.acceptConnectionTimeout = acceptConnectionTimeout;
     }
````

**Comment by philsttr** [comment]
Hi @AxelBe,

While your recommendation does have its merits, I don't totally agree with your implementation.

As a general practice, I would recommend against passing mutable objects to a logger (well, not so much mutable objects, but rather mutable objects which are likely to change).  There is no guarantee (by logback, by logstash-logback-encoder, or by any other logging framework) that the event is logged synchronously.  For example, if you use logback's (or log4j's) `AsyncAppender`,  you will encounter the same "out-of-date" problem.  So, this is not something that is unique to the logstash-logback-encoder, but more of a general logging practice.

Performing the encoding inline (prior to the handoff to another thread) also removes one of the key advantages of using an asynchronous appender like `AsyncAppender` or `LogstashTcpSocketAppender`.  By offloading the encoding and transmission to a separate thread, it frees up the logging thread to continue its processing faster.  Most often you want the main thread to be processing as fast as possible, with little impact from logging.

So, there is definitely a performance/memory trade-off at play here.

At the moment, I would like to keep this trade-off leaning in the favor of performance.  The memory side of things can be managed in other ways.  Specifically:

1) If you need to log data from mutable objects, I would recommend converting them to a non-mutable form first.  This is just a general logging best-practice, as I mentioned earlier.  The could be accomplished as easily as this:

```
if (LOG.isWarnEnabled()) {
    LOG.warn("Error processing {}", myBigObject.toString());.
}
```

2) If the objects being passed to the logger are still huge, then I would just recommend tuning down the size of the queue.  Obviously, this comes at a cost of possibly losing more messages during network interruptions.

3) If you can't stand to lose messages, the I would recommend logging to disk instead, and having another agent (perhaps logstash itself) read from disk and send the messages over the wire.



Ideally, there would be some sort of "buffer to memory first, then buffer to disk if memory is full" queue, but that behavior does not exist at the moment.  Perhaps that's a good feature request though.

And as a side note, I definitely agree that timeouts should be configurable. I'll definitely get that incorporated.

And one last minor side note.  In the future, if you don't mind, we would prefer if you would submit patches via a git pull request, rather than a diff.

**Comment by AxelBe** [comment]
Hi Phil,

Thanks for looking into this! The slowdown of the main thread with my approach is really a point I have to rethink. Maybe I try to find the big memory consumers and implement some monitoring of the queue for the future. In bigger projects you not always know who passes what to the logger.

Best,
Axel

**Comment by AxelBe** [comment]
Update. 
I changed my fix of the object allocation problem by wrapping the events in the queue into an ````ILoggingEvent```` that ensures ````toString()```` on all the argument items (similar action to ````ILoggingEvent.prepareForDeferredProcessing()````
````java
class StringArgumentArrayLoggingEvent implements ILoggingEvent {

    private final ILoggingEvent baseEvent;
    private final Object[] overlayedArgumentArray;

    StringArgumentArrayLoggingEvent(ILoggingEvent baseEvent) {
        this.baseEvent = baseEvent;
        this.overlayedArgumentArray = toStringArgumentsArray(baseEvent);
    }

    @Override
    public Object[] getArgumentArray() {
        return overlayedArgumentArray;
    }
  
    @Override
    public String getMessage() {
        return baseEvent.getMessage();
    }
    
    [... all the getters forwarded ...]

    private static Object[] toStringArgumentsArray(ILoggingEvent event) {
        
        Object[] argumentArray = event.getArgumentArray();
        if (argumentArray != null) {
            
            for (int i = 0; i < argumentArray.length; i++) {
                
                Object object = argumentArray[i];
                
                if (!(object instanceof String)) {
                    // convert to string to detach heavy object structures
                    argumentArray[i] = object.toString();
                }
            }           
        }    
        return argumentArray;
    }    
}
````
