### ISSUE TITLE
remoteHost is resolved only once

### ISSUE THREAD

**Issue by dimas** [logstash/logstash-logback-encoder#77]
TCP appender resolves hostname in its start() method and then just uses remoteAddress.

This way a running application cannot adapt to the changing circumstances like you are removing one server from DNS round robin for example. Or Amazon doing some reconfiguration in their ELBs (which, I assume can lead to change of CNAMEs to which ELB name resolves).

I would probably do DNS resolution in the openSocket() instead. Although this may lead to a successful start with an invalid hostname, I do not really see it as a problem - in the end, it will just log hostname resolution exception 5 times and will keep trying to resolve it every 30 seconds. It is not very much worse than not starting appender at all.

**Comment by philsttr** [comment]
Fixed for 4.2
