### ISSUE TITLE
UDP Appender to have pattern configurability

### ISSUE THREAD

**Issue by gsziklai** [logstash/logstash-logback-encoder#80]
Referencing #72 :
"I realize it's a little confusing. I'd like to make the UDP appender be configured just like the TCP appender (and most every other logback appender). Meaning, you would have to configure a layout/encoder within the appender. However, I can't change it due to backwards compatibility issues."

How about introducing a new UDP appender that extends LogstashSocketAppender with the above functionalities? I know that it hurts symmetry, but it would be really useful. We would like to customize the output with the power of CompositeJsonEncoder, yet not give up the speed of UDP.

If this is not in your roadmap, how would you suggest implementing this to remain inline and compatible with your future releases?

**Comment by philsttr** [comment]
Hi @gsziklai,

It is somewhat possible to use the pattern provider with the `LogstashSocketAppender` today.  Although, it's a bit of a hack, and not at all ideal.

For example:

```xml
<appender name="stash" class="net.logstash.logback.appender.LogstashSocketAppender">
  <host>MyAwesomeSyslogServer</host>
  <port>514</port>
  <provider class="net.logstash.logback.composite.loggingevent.LoggingEventPatternJsonProvider">
    <pattern>
        {
          "foo": "bar"
        }
    </pattern>
  </provider>
</appender>
```

To implement this a bit better, I would probably insert a class in the hierarchy between `SyslogAppenderBase` and `LogstashSocketAppender` that took any type of Layout.

`LogstashSocketAppender` is highly tied to a `LogstashLayout`, so extending `LogstashSocketAppender` would not be the best option if a different layout was used.

I haven't thought through the complete implementation, but that's just what comes to mind first.  If you want to give it a shot, please feel free to submit a pull request.  I probably won't be able to get to it for a while.

**Comment by gsziklai** [comment]
Thank you. The configuration option you provided works for us.
