### ISSUE TITLE
Replacing line feed characters to another one

### ISSUE THREAD

**Issue by cemo** [logstash/logstash-logback-encoder#83]
I have started use your library with another library's appender. Their socket appender is replacing linefeed character with a unicode character. However Jackson is replacing `\n` with `\\n`. Is it possible to configure this?

**Comment by philsttr** [comment]
I'm not sure I understand what you are asking.  Can you provide examples?  (For example, your java code that is logging messages, and the JSON output).

If you're talking about the newline character at the end of an event (after the JSON object has been closed with a `}`), then for a `CompositeJsonEncoder` or `LogstashEncoder`, this can be configured by using the `lineSeparator` property.  By default, it is the system's line separator.  See [here](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/encoder/CompositeJsonEncoder.java#L225) for the possible values.

For example:

```xml
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
  <lineSeparator>UNIX</lineSeparator>
</encoder>
```


If you're talking about line feed characters within JSON string values, then Jackson must escape them (as `\n`), since JSON does not allow line feed characters within string values.  If your string contains the literal `\n` (not the new line character, but a backslash and an `n`), then Jackson will escape the backslash as `\\n` to indicate that this is not a newline character.

**Comment by cemo** [comment]
Sorry for poor description. I am using a commercial hosted log solution and  using an appender with your `LogstashLayout`:

```
<appender name="ME" class="some.commercial.log.Appender">
      <Debug>False</Debug>
      <Token>${MY_TOKEN}</Token>
      <Ssl>False</Ssl>
      <facility>USER</facility>

      <layout class="net.logstash.logback.layout.LogstashLayout">
         <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
            <maxDepthPerThrowable>30</maxDepthPerThrowable>
            <maxLength>2048</maxLength>
            <shortenedClassNameLength>20</shortenedClassNameLength>
            <exclude>sun\.reflect\..*\.invoke.*</exclude>
            <exclude>net\.sf\.cglib\.proxy\.MethodProxy\.invoke</exclude>
            <rootCauseFirst>true</rootCauseFirst>
         </throwableConverter>
      </layout>

   </appender>
```

In order to display multine line strings they have a nice feature. If a line contains  `\u2028` it is displayed as a new line. This is pretty nice for formatting JSON objects containing `Stacktrace`.  Here is a part of my stacktrace, please note that `\n\t` strings inside:

```
o.s.w.s.m.m.a.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:777)\n\tat o.s.w.s.m.m.a.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:706)\n\tat o.s.w.s.m.m.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)\n\tat 
```

I would like to configure that line feed characters with be replaced with `\u2028` not `\n\t` in `LogstashLayout`. 

Hope that this makes clearer.

**Comment by philsttr** [comment]
Hi @cemo,

You can configure Jackson's `JsonFactory` to use custom escape codes.  And logstash-logback-encoder allows you to customize a `JsonFactory` using a `JsonFactoryDecorator`.

For example, create your own `JsonFactoryDecorator`:

```java
import com.fasterxml.jackson.core.SerializableString;
import com.fasterxml.jackson.core.io.CharacterEscapes;
import com.fasterxml.jackson.core.io.SerializedString;
import com.fasterxml.jackson.databind.MappingJsonFactory;

import net.logstash.logback.decorate.JsonFactoryDecorator;

public class CustomEscapeJsonFactoryDecorator implements JsonFactoryDecorator {

    private static class CustomCharacterEscapes extends CharacterEscapes {
        
        private static final SerializedString ESCAPE_LF = new SerializedString("\u2028");
        private static final SerializedString ESCAPE_CR = new SerializedString("");
        
        private final int[] escapeCodesForAscii;
        

        private CustomCharacterEscapes() {
            escapeCodesForAscii = standardAsciiEscapesForJSON();
            escapeCodesForAscii[(int) '\n'] = ESCAPE_CUSTOM; 
            escapeCodesForAscii[(int) '\r'] = ESCAPE_CUSTOM; 
        }
        
        @Override
        public SerializableString getEscapeSequence(int ch) {
            switch (ch) {
                case '\n':
                    return ESCAPE_LF;
                case '\r':
                    /*
                     * Don't output anything for carriage return, since we're
                     * collapsing \r\n into just \u2028.
                     */
                    return ESCAPE_CR;
                default:
                    /*
                     * For all other chars, return a non-escaped string.
                     * This shouldn't be called since the generator uses
                     * JsonGenerator.Feature.ESCAPE_NON_ASCII,
                     * 
                     */
                    return new SerializedString(new String(new char[] {(char) ch})); 
            }
        }
        
        @Override
        public int[] getEscapeCodesForAscii() {
            return escapeCodesForAscii;
        }
    }
    
    @Override
    public MappingJsonFactory decorate(MappingJsonFactory factory) {
        factory.setCharacterEscapes(new CustomCharacterEscapes());
        return factory;
    }

}

```

Then configure logstash-logback-encoder to use it:

```xml
<layout class="net.logstash.logback.layout.LogstashLayout">
    ...
    <jsonFactoryDecorator class="CustomEscapeJsonFactoryDecorator"/>
</layout>
```

Note that I haven't done much testing on this, so use at your own risk.

**Comment by cemo** [comment]
Thank you so much. It worked like a charm. BTW this repo is useful as much as logback :) I have removed all my dirty code with your implementation. Thanks for sharing.

**Comment by SawyerFord** [comment]
Hi 


      `{"@timestamp":"2018-01-31T19:21:27.624+04:00","@version":1,"message":"{\"type\":\"API_REQUEST\",\"uid\":\"35f53fe5-7c63-4936-a617-14601073a5f7\",\"sessionId\":\"9E998B68C5A6D66C30D215DE0B4B5EF3\",\"remoteAddress\":\"0:0:0:0:0:0:0:1\",\"methodType\":\"POST\",\"headers\":\"{content-length=76, accept-language=en-US,en;q=0.9, cookie=JSESSIONID=50D17B32E96A6A8850F2A5FD52A4C07D, postman-token=a5be9806-a0a6-3905-e45d-2bea9036f3ed, origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop, accept=*/*, host=localhost:3080, connection=keep-alive, content-type=application/json, cache-control=no-cache, accept-encoding=gzip, deflate, br, user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36}\",\"uri\":\"/user/login\",\"query\":null,\"contentType\":\"application/json\",\"requestTime\":\"2018-01-31 19:21:26.024\",\"responseTime\":\"2018-01-31 19:21:27.604\",\"executionTimeMillisecond\":1580,\"requestPayload\":\"{\\n  \\\"\\": \\\"+971\\\",\\n  \\\"phone\\\": \\\"545901009\\\",\\n  \\\"employeeType\\\": \\\"PHONE\\\"\\n }\",\"responsePayload\":\"{\\\"status\\\":\\\"FAIL\\\",\\\"statusCode\\\":1000,\\\"message\\\":\\\"Internal Server Error\\\",\\\"desc\\\":\\\"FAIL\\\",\\\"debug\\\":\\\"org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: non null key required\\\\n\\\\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)\\\\n\\\\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)\\\\n\\\\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:648)\\\\n\\\\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)\\\\n\\\\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:729)\\\\n\\\\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)\\\\n\\\\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)\\\\n\\\\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\\\\n\\\\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)\\\\n\\\\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)\\\\n\\\\tat`
