### ISSUE TITLE
Renaming HOSTNAME field

### ISSUE THREAD

**Issue by moulliet** [logstash/logstash-logback-encoder#84]
I'd like existing 'HOSTNAME' field output by the LogstashTcpSocketAppender to be renamed to 'host'

I've seen the documentation for [customizing field names](https://github.com/logstash/logstash-logback-encoder/#custom_field_names), and I haven't figured out the incantation to change the hostname.

Is it supported?

Thanks!

**Comment by philsttr** [comment]
The `HOSTNAME` field in the output actually comes from logback's context.  You can "rename" it by disabling context properties from being included, and adding your own host field...

```xml
<includeContext>false</includeContext>
<customFields>{"host":"${HOSTNAME}"}</customFields>
```

**Comment by moulliet** [comment]
Thanks, that did the trick :)
