### ISSUE TITLE
How to output logstash.logback.marker.Markers to console

### ISSUE THREAD

**Issue by mhamrah** [logstash/logstash-logback-encoder#90]
I'm using the appendEntries() function in Markers._ to add custom fields to the json output. This works, but I'd also like this data outputted to the console with Logback's ConsoleAppender.  Is this possible? The closest I've gotten is added a %marker tag to the ConsoleAppender's encoder pattern, but that just outputs LS_MAP_FIELDS.

Thanks,

Mike

**Comment by balihoo-gens** [comment]
I have a similar issue using the LoggingEventCompositeJsonEncoder. I specified a custom pattern as in the [documentation](https://github.com/logstash/logstash-logback-encoder#composite-encoderlayout): 
```
 <appender name="balihoo" class="ch.qos.logback.core.rolling.RollingFileAppender">
    ...
   <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
      <providers>
        <mdc/>
        <pattern>
          <pattern>
            {
              "timestamp": "%date{\"yyyy-MM-dd'T'HH:mm:ss,SSSXXX\", UTC}",
              "level": "%level",
              "logger": "%logger",
              "message": "%message",
              "logstashMarkers": "%marker"
            }
          </pattern>
        </pattern>
        <stackTrace>
          <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
            <maxDepthPerThrowable>30</maxDepthPerThrowable>
            <maxLength>2048</maxLength>
            <shortenedClassNameLength>20</shortenedClassNameLength>
            <rootCauseFirst>true</rootCauseFirst>
          </throwableConverter>
        </stackTrace>
      </providers>
    </encoder>
</appender>
```
which results in logmessages like this:

```
{"timestamp":"2015-04-07T22:42:05,213Z","level":"INFO","logger":"coordinator","message":"started task processing","logstashMarkers":"LS_OBJECT_FIELDS"}
```
Interestingly, log messages that do not include extra fields show an empty string, so it is trying to deal with it:

```
{"timestamp":"2015-04-07T22:42:05,213Z","level":"INFO","logger":"coordinator","message":"end task processing","logstashMarkers":""}
```
How do I change my config to get my custom fields to show up?

**Comment by philsttr** [comment]
@mhamrah, Unfortunately, there is no [conversion word](http://logback.qos.ch/manual/layouts.html#conversionWord) that can be used with logback's [PatternLayout](http://logback.qos.ch/manual/layouts.html#ClassicPatternLayout) to output the [logstash markers](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/marker/Markers.java).  The logstash markers can only be used with the [encoders/layouts provided by logstash-logback-encoder](https://github.com/logstash/logstash-logback-encoder#usage), such as `LoggingEventCompositeJsonEncoder` or `LogstashEncoder`.  So, you would need to use one of these encoders/layouts with the console appender to get these markers to output on the console.


@balihoo-gens, to output the logstash markers with the `LoggingEventCompositeJsonEncoder`, instead of declaring a field in a pattern with a conversion word, you need to use the `logstashMarkers` provider like this:

```xml
   <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
      <providers>
        <mdc/>
        <pattern>
          <pattern>
            {
              "timestamp": "%date{\"yyyy-MM-dd'T'HH:mm:ss,SSSXXX\", UTC}",
              "level": "%level",
              "logger": "%logger",
              "message": "%message"
            }
          </pattern>
        </pattern>
        <logstashMarkers/>
        <stackTrace>
          <throwableConverter class="net.logstash.logback.stacktrace.ShortenedThrowableConverter">
            <maxDepthPerThrowable>30</maxDepthPerThrowable>
            <maxLength>2048</maxLength>
            <shortenedClassNameLength>20</shortenedClassNameLength>
            <rootCauseFirst>true</rootCauseFirst>
          </throwableConverter>
        </stackTrace>
      </providers>
    </encoder>
```

**Comment by balihoo-gens** [comment]
@philsttr Thanks for your quick response. Unfortunately the fields do not show up, even with the provider added (I had tried that first, but did not include that in my description above, apologies).

 Is it possible I am not using a compatible appender? I am using the ch.qos.logback.core.rolling.RollingFileAppender

I extracted my usage into a [simple test project](https://github.com/balihoo-gens/logstash_test) with the [full xml file](https://github.com/balihoo-gens/logstash_test/blob/master/src/main/resources/logback.xml).

The [resulting log file](https://github.com/balihoo-gens/logstash_test/blob/master/logstash_test.log) has the exceptions, but the additional fields do not show.

When I take all the providers out except for the `<logstashMarkers/>` one, I get empty log entries: `{}`

**Comment by balihoo-gens** [comment]
@philsttr I got extra fields to show up by using `append("test", "one")` rather than `appendFields(Json.obj("test" -> "one"))`. I can work with this for now, but would prefer to be able to use appendFields

**Comment by philsttr** [comment]
What type of object does `Json.obj("test" -> "one")` return?

**Comment by balihoo-gens** [comment]
it is a Scala Play framework [play.api.libs.json.JsObject](https://www.playframework.com/documentation/2.0/api/scala/play/api/libs/json/JsObject.html), which should translate to a Jackson node (via [Jerkson](https://github.com/codahale/jerkson/)), but maybe that is not as straightforward as I thought.

`appendEntries(Json.obj("test" -> "one").as[Map[String,String]])` also works.

Looks like this functionality works fine, I just need to look into the type conversion further. Would there be any debug messages anywhere that complain about the conversion?

**Comment by philsttr** [comment]
Probably no debug messages.

The code that handles appendFields is [here](https://github.com/logstash/logstash-logback-encoder/blob/master/src/main/java/net/logstash/logback/marker/ObjectFieldsAppendingMarker.java), if you need to a place to start investigating.

**Comment by philsttr** [comment]
Closing this issue.

Not planning on adding non-JSON output for the logstash markers.

Also, this issue was not originally focused on the Scala Play `JsObject`.  If you would like support for this, please submit a pull request or another issue.

**Comment by mrsarm** [comment]
This should be taken into consideration again, it's annoying to use the JSON output in development environments, specially when you have stacktraces in the log it's really hard to read, but many as me don't have another option because the logs are sent to an ingestion pipeline where JSON is a more suitable format (and it's cool to have this output in these cases, but not for development).

**Comment by axonbrent** [comment]
`%markers` outputs the entire list (as JSON).

We need a way to access the individual fields.

**Comment by brenuart** [comment]
@axonbrent This issue is closed since long. Please open another with a description of your issue and link to this one if needed. Thx.
