### ISSUE TITLE
Using LoggingEventAsyncDisruptorAppender + includeCallerInfo doesn't work

### ISSUE THREAD

**Issue by alex-sherwin** [logstash/logstash-logback-encoder#91]
The documentation simply states that you can use

```
<includeCallerInfo>true</includeCallerInfo>
```

Inside an encoder, but when wrapped with `net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender` it doesn't work.

Through some basic debugging I found that you must set the encoder with

```
<includeCallerInfo>true</includeCallerInfo>
```

And the `net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender` config with (note the different naming as well)
```
<includeCallerData>true</includeCallerData>
```

A complete sample config that works for me is
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration debug="false" scan="true">
  <contextListener class="ch.qos.logback.classic.jul.LevelChangePropagator"/>
  <appender name="logstash" class="net.logstash.logback.appender.LoggingEventAsyncDisruptorAppender">
    <includeCallerData>true</includeCallerData>
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
      <encoder class="net.logstash.logback.encoder.LogstashEncoder">
        <includeCallerInfo>true</includeCallerInfo>
      </encoder>
    </appender>
  </appender>
  <root level="all">
    <appender-ref ref="logstash"/>
  </root>
</configuration>
```

**Comment by philsttr** [comment]
Thanks for filing this!

I clarified the documentation, introduced `includeCallerData` (to be consistent with logback), and deprecated `includeCallerInfo`
