### ISSUE TITLE
Kinesis Appender

### ISSUE THREAD

**Issue by sihil** [logstash/logstash-logback-encoder#95]
We use AWS fairly heavily and would be interested in seeing a new appender that wrote to an AWS Kinesis stream.

There is already a logstash plugin that consumes events from a Kinesis stream (see https://github.com/codekitchen/logstash-input-kinesis). Being able to write to a stream would nicely decouple event producers from logstash and allow us to spin up multiple ELK stacks consuming the same log data (for testing and transitioning for example).

I'd be happy to look at implementing this - although some pointers as how best to go about doing so in the current Appender hierarchy would be welcome.

I'd also be interested in hearing from anyone else who might find this interesting.

**Comment by philsttr** [comment]
Hi @sihil,

I'd suggest making a separate project for a kinesis logback appender (similar to how [there is one for log4j](https://github.com/awslabs/kinesis-log4j-appender)).

It's fairly simple to create a logback appender.  Just subclass `UnsynchronizedAppenderBase` or `AppenderBase`.  The appender should be able to configured to use any encoder, just like most other appenders.

**Comment by sihil** [comment]
Hi @philsttr,

Thought you might like to know that my colleague @kenoir has created a logback appender as suggested. It's available at https://github.com/guardian/kinesis-logback-appender.

Regards,
Simon
